// Generated by CoffeeScript 1.7.1
var AreaCircle, VisibleCircle;

VisibleCircle = (function() {
  function VisibleCircle(svg) {
    this.svg = svg;
    this.visible = false;
    this.circle = this.svg.append('circle').attr({
      cx: svg.attr('width') / 2,
      cy: svg.attr('height') / 2
    });
  }

  VisibleCircle.prototype.render = function() {
    return this.circle.attr({
      r: this.visible ? 100 : 0
    });
  };

  return VisibleCircle;

})();

AreaCircle = (function() {
  function AreaCircle(svg) {
    this.svg = svg;
    this.area = 0;
    this.circle = this.svg.append('circle').attr({
      cx: svg.attr('width') / 2,
      cy: svg.attr('height') / 2
    });
  }

  AreaCircle.prototype.render = function() {
    return this.circle.attr({
      r: Math.sqrt(this.area)
    });
  };

  return AreaCircle;

})();

$(function() {
  var areaCircle, propTween, visibleCircle;
  window.svgForVisibleCircle = d3.select('svg.forVisibleCircle');
  window.svgForAreaCircle = d3.select('svg.forAreaCircle');
  visibleCircle = new VisibleCircle(svgForVisibleCircle);
  areaCircle = new AreaCircle(svgForAreaCircle);
  propTween = function(object, propName, newValue, renderer) {
    return function() {
      var interpolator, oldValue;
      oldValue = object[propName];
      console.log('propTween', oldValue);
      interpolator = d3.interpolate(oldValue, String(newValue));
      return function(t) {
        object[propName] = interpolator(t);
        return renderer();
      };
    };
  };
  areaCircle.render();
  return d3.transition().duration(1000).tween('area', propTween(areaCircle, 'area', 100 * 100, function() {
    return areaCircle.render();
  })).transition().duration(1000).tween('area', propTween(areaCircle, 'area', 0, function() {
    return areaCircle.render();
  }));
});
