// Generated by CoffeeScript 1.7.1
var ColoringGame, RegionMap, Script,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Script = (function() {
  function Script(_arg) {
    this.stepNames = _arg.stepNames, this.steps = _arg.steps, this.afterUpdate = _arg.afterUpdate;
    this.currentStepName = null;
  }

  Script.prototype.enterStep = function(newStepName) {
    var relevantSelections, selection, stepDiff, trans, _base, _i, _len;
    if (!this.currentStepName) {
      this.quasiEnterStepAbruptly(newStepName);
    } else {
      stepDiff = this.indexFromStepName(newStepName) - this.indexFromStepName(this.currentStepName);
      if (stepDiff === 1) {
        trans = function(obj) {
          obj.interrupt();
          return obj.transition().duration(1000);
        };
        if (typeof (_base = this.steps)[newStepName] === "function") {
          _base[newStepName](trans);
        }
      } else if (stepDiff === -1) {
        relevantSelections = this.quasiEnterStepSilently(newStepName);
        console.log('relevantSelections', relevantSelections);
        for (_i = 0, _len = relevantSelections.length; _i < _len; _i++) {
          selection = relevantSelections[_i];
          console.log('selection = ', selection.attr('class'));
          console.log('  attr:', selection.__script_attr__);
          console.log('  style:', selection.__script_style__);
          selection.interrupt();
          selection.transition().duration(1000).attr(selection.__script_attr__).style(selection.__script_style__);
          selection.__script_attr__ = void 0;
          selection.__script_style__ = void 0;
        }
      } else {
        this.quasiEnterStepAbruptly(newStepName);
      }
    }
    this.afterUpdate();
    return this.currentStepName = newStepName;
  };

  Script.prototype.quasiEnterStepAbruptly = function(newStepName) {
    var i, stepName, trans, _base, _i, _len, _ref, _results;
    trans = function(obj) {
      obj.interrupt().transition();
      return obj;
    };
    _ref = this.stepNames.slice(0, +this.stepNames.indexOf(newStepName) + 1 || 9e9);
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      stepName = _ref[i];
      _results.push(typeof (_base = this.steps)[stepName] === "function" ? _base[stepName](trans) : void 0);
    }
    return _results;
  };

  Script.prototype.quasiEnterStepSilently = function(newStepName) {
    var i, relevantSelections, stepName, trans, _base, _i, _len, _ref;
    relevantSelections = [];
    trans = function(obj) {
      var pseudoSelection;
      if (!(__indexOf.call(relevantSelections, obj) >= 0)) {
        relevantSelections.push(obj);
      }
      if (obj.__script_attr__ == null) {
        obj.__script_attr__ = {};
      }
      if (obj.__script_style__ == null) {
        obj.__script_style__ = {};
      }
      pseudoSelection = {
        attr: function(hash) {
          _.extend(obj.__script_attr__, hash);
          return pseudoSelection;
        },
        style: function(hash) {
          _.extend(obj.__script_style__, hash);
          return pseudoSelection;
        }
      };
      return pseudoSelection;
    };
    _ref = this.stepNames.slice(0, +this.stepNames.indexOf(newStepName) + 1 || 9e9);
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      stepName = _ref[i];
      if (typeof (_base = this.steps)[stepName] === "function") {
        _base[stepName](trans);
      }
    }
    return relevantSelections;
  };

  Script.prototype.indexFromStepName = function(stepName) {
    return this.stepNames.indexOf(stepName);
  };

  return Script;

})();

ColoringGame = (function() {
  ColoringGame.prototype.colors = ['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)'];

  ColoringGame.prototype.cursors = ['red', 'blue', 'green', 'purple', 'orange', 'yellow'];

  function ColoringGame(_arg) {
    this.regionMap = _arg.regionMap, this.svg = _arg.svg, this.regionIdSubset = _arg.regionIdSubset;
    this.parts = {};
    this.currentColor = void 0;
    this.currentCursor = void 0;
    this.shownIncomplete = false;
    this.shownSpoilerMoreThanFour = false;
    this.shownSpoilerFour = false;
    this.bestScoreSoFar = 1000;
    this.shouldWiggle = false;
    this.isWiggling = false;
    this.wigglePeriodMs = 800;
    this.shouldAnimateNodeColoring = false;
    this.isAnimatingNodeColoring = false;
    this.animateNodeColoringPeriodMs = 500;
    this.animateNodeColoringOrder = [];
    this.canDragNodes = false;
    if (this.regionIdSubset) {
      this.regionData = _.filter(this.regionMap.regionData, (function(_this) {
        return function(d) {
          var _ref;
          return _ref = d.id, __indexOf.call(_this.regionIdSubset, _ref) >= 0;
        };
      })(this));
      this.edgeData = _.filter(this.regionMap.edgeData, (function(_this) {
        return function(d) {
          var _ref, _ref1;
          return (_ref = d[0].id, __indexOf.call(_this.regionIdSubset, _ref) >= 0) && (_ref1 = d[1].id, __indexOf.call(_this.regionIdSubset, _ref1) >= 0);
        };
      })(this));
    } else {
      this.regionData = this.regionMap.regionData;
      this.edgeData = this.regionMap.edgeData;
    }
  }

  ColoringGame.prototype.render = function(viaUser) {
    var forbidden, neighborRegion, nodeDrag, numColorsUsed, region, solidTransformersEnter, _i, _j, _len, _len1, _ref, _ref1;
    this.parts.edges = this.svg.selectAll(".edge").data(this.edgeData);
    this.parts.edges.enter().append('line').classed('edge', true).each(function(d) {
      return $(this).qtip({
        content: {
          text: d[0].name + " neighbors " + d[1].name
        },
        position: {
          my: 'bottom center',
          target: 'mouse'
        },
        style: {
          classes: 'qtip-dark'
        }
      });
    });
    this.parts.edges.attr({
      x1: function(d) {
        return d[0].nodeCenter[0];
      },
      y1: function(d) {
        return d[0].nodeCenter[1];
      },
      x2: function(d) {
        return d[1].nodeCenter[0];
      },
      y2: function(d) {
        return d[1].nodeCenter[1];
      }
    });
    forbidden = [];
    _ref = this.regionData;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      region = _ref[_i];
      if (region.fill === this.currentColor) {
        _ref1 = region.neighbors;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          neighborRegion = _ref1[_j];
          forbidden.push(neighborRegion);
        }
      }
    }
    this.parts.solidTransformers = this.svg.selectAll('.solidTransformer').data(this.regionData, function(d) {
      return d.id;
    });
    solidTransformersEnter = this.parts.solidTransformers.enter().append('g').classed('solidTransformer', true).append('path').classed('solid', true).attr({
      "class": function(d) {
        return "solid " + d.id;
      },
      d: this.regionMap.path
    });
    this.parts.solids = this.parts.solidTransformers.select('.solid');
    if (!this.parts.borders) {
      this.parts.borders = this.svg.append("path").classed('borders', true).datum(this.regionMap.borderDatum).attr({
        d: this.regionMap.path
      });
    }
    if (!this.isWiggling) {
      this.wiggleLoop();
    }
    this.parts.solids.style({
      opacity: 1,
      fill: function(d) {
        return d.fill || 'white';
      },
      mask: function(d) {
        if (d.shade) {
          return 'url(#mask-yes-fill)';
        }
      },
      cursor: (function(_this) {
        return function(d) {
          if (_this.currentCursor) {
            return "url(" + _this.currentCursor + (__indexOf.call(forbidden, d) >= 0 ? '_cross' : '') + ".png) 8 30, auto";
          }
        };
      })(this)
    }).on('click', (function(_this) {
      return function(d) {
        if (_this.currentColor && !(__indexOf.call(forbidden, d) >= 0)) {
          d.fill = _this.currentColor;
          return _this.render(true);
        }
      };
    })(this)).on('mouseenter', (function(_this) {
      return function(d) {
        var _k, _len2, _ref2;
        if (__indexOf.call(forbidden, d) >= 0) {
          _ref2 = _this.regionData;
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            region = _ref2[_k];
            region.shade = (__indexOf.call(d.neighbors, region) >= 0) && (region.fill === _this.currentColor);
          }
          return _this.render();
        }
      };
    })(this)).on('mouseleave', (function(_this) {
      return function(d) {
        if (__indexOf.call(forbidden, d) >= 0) {
          _this.regionMap.clearShades();
          return _this.render();
        }
      };
    })(this));
    nodeDrag = d3.behavior.drag().origin(function(d) {
      var x, y, _ref2;
      _ref2 = d.nodeCenter, x = _ref2[0], y = _ref2[1];
      return {
        x: x,
        y: y
      };
    }).on("drag", (function(_this) {
      return function(d) {
        var x, y;
        if (_this.canDragNodes) {
          x = Math.max(0, Math.min(_this.svg.attr('width'), d3.event.x));
          y = Math.max(0, Math.min(_this.svg.attr('height'), d3.event.y));
          d.nodeCenter = [x, y];
          return _this.render();
        }
      };
    })(this));
    this.parts.nodes = this.svg.selectAll(".node").data(this.regionData, function(d) {
      return d.id;
    });
    this.parts.nodes.enter().append("circle").attr('class', function(d) {
      return 'node ' + d.id;
    }).attr({
      r: 0
    }).each(function(d) {
      return $(this).qtip({
        content: {
          text: d.name
        },
        position: {
          my: 'bottom center',
          at: 'top center'
        },
        style: {
          classes: 'qtip-dark'
        }
      });
    }).call(nodeDrag);
    this.parts.nodes.attr({
      cx: function(d) {
        return d.nodeCenter[0];
      },
      cy: function(d) {
        return d.nodeCenter[1];
      }
    }).style({
      fill: function(d) {
        if (!d.fill) {
          if (__indexOf.call(forbidden, d) >= 0) {
            return 'lightgray';
          } else {
            return 'white';
          }
        } else {
          return d.fill;
        }
      }
    });
    if (!this.isAnimatingNodeColoring) {
      this.animateNodeColoringLoop();
    }
    numColorsUsed = this.regionMap.getNumColorsUsed();
    d3.select('#color-count .num-place').text(numColorsUsed);
    if (!this.regionMap.uncoloredRegionsPresent() && numColorsUsed < this.bestScoreSoFar) {
      this.bestScoreSoFar = numColorsUsed;
      if (viaUser) {
        window.addBubble('colored-with-n', {
          n: numColorsUsed
        });
        if (this.shownIncomplete && !this.shownSpoilerMoreThanFour && numColorsUsed > 4) {
          this.shownSpoilerMoreThanFour = true;
          return window.addBubble('spoiler-more-than-four');
        } else if (this.shownIncomplete && !this.shownSpoilerFour && numColorsUsed === 4) {
          this.shownSpoilerFour = true;
          return window.addBubble('spoiler-four');
        } else {
          return window.addBubble('solid-coloring');
        }
      }
    }
  };

  ColoringGame.prototype.getScared = function() {
    var _ref;
    if (!this.shownIncomplete) {
      this.shownIncomplete = true;
      if (this.regionMap.uncoloredRegionsPresent()) {
        window.addBubble('incomplete');
      }
      if ((4 < (_ref = this.bestScoreSoFar) && _ref < 1000)) {
        this.shownSpoilerMoreThanFour;
        window.addBubble('spoiler-more-than-four');
      }
      if (this.bestScoreSoFar === 4) {
        this.shownSpoilerFour = true;
        return window.addBubble('spoiler-four');
      }
    }
  };

  ColoringGame.prototype.wiggleLoop = function() {
    var path, pointTransform, pointTransform1, pointTransform2, time, transform;
    if (this.shouldWiggle) {
      window.setTimeout(((function(_this) {
        return function() {
          return _this.wiggleLoop();
        };
      })(this)), this.wigglePeriodMs);
      this.isWiggling = true;
      time = (new Date()).getTime();
      pointTransform1 = function(x, y) {
        return [x + 30 * Math.sin(time / 800) * Math.sin(y / 20), y];
      };
      pointTransform2 = function(x, y) {
        return [x, y + Math.sin(time / 1150) * (x - 200) * (x - 200) / 300];
      };
      pointTransform = _.sample([pointTransform1, pointTransform2]);
      transform = d3.geo.transform({
        point: function(x, y) {
          var _ref;
          return (_ref = this.stream).point.apply(_ref, pointTransform(x, y));
        }
      });
      path = d3.geo.path().projection({
        stream: (function(_this) {
          return function(listener) {
            return _this.regionMap.projection.stream(transform.stream(listener));
          };
        })(this)
      });
    } else {
      this.isWiggling = false;
      path = this.regionMap.path;
    }
    return this.parts.solids.transition().duration(this.wigglePeriodMs).attr({
      d: path
    });
  };

  ColoringGame.prototype.animateNodeColoringLoop = function() {
    var next, timeout;
    if (this.shouldAnimateNodeColoring) {
      this.isAnimatingNodeColoring = true;
      if (this.animateNodeColoringOrder.length) {
        next = this.animateNodeColoringOrder.pop();
        this.parts.nodes.filter(function(d) {
          return d === next;
        }).style({
          fill: function(d) {
            return d.fill;
          }
        });
      } else {
        this.animateNodeColoringOrder = _.shuffle(this.regionData);
        this.parts.nodes.style({
          fill: 'white',
          stroke: 'black'
        });
      }
      timeout = this.animateNodeColoringPeriodMs * (!this.animateNodeColoringOrder.length ? 2 : 1);
      return window.setTimeout(((function(_this) {
        return function() {
          return _this.animateNodeColoringLoop();
        };
      })(this)), timeout);
    } else {
      this.isAnimatingNodeColoring = false;
      return this.parts.nodes.style({
        fill: function(d) {
          return d.fill;
        },
        stroke: 'none'
      });
    }
  };

  return ColoringGame;

})();

RegionMap = (function() {
  function RegionMap(_arg) {
    var id, neighborId, neighborIds, region, region1, region2, x, y, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3;
    this.json = _arg.json, this.objName = _arg.objName, this.oneWayAdjacencies = _arg.oneWayAdjacencies, this.projection = _arg.projection, this.idToName = _arg.idToName;
    this.regionData = topojson.feature(this.json, this.json.objects[this.objName]).features;
    this.borderDatum = topojson.mesh(this.json, this.json.objects[this.objName]);
    this.path = d3.geo.path().projection(this.projection);
    if (this.idToName) {
      _ref = this.regionData;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        region = _ref[_i];
        region.name = this.idToName[region.id];
      }
    }
    _ref1 = this.regionData;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      region = _ref1[_j];
      _ref2 = this.path.centroid(region), x = _ref2[0], y = _ref2[1];
      region.center = [x, y];
      if (region.id === 'BRA') {
        x += 25;
      }
      if (region.id === 'SUR') {
        x += 8;
      }
      if (region.id === 'GUF') {
        x += 16;
      }
      region.nodeCenter = [x, y];
    }
    this.countriesById = _(this.regionData).chain().map(function(d) {
      return [d.id, d];
    }).object().value();
    this.edgeData = [];
    _ref3 = this.oneWayAdjacencies;
    for (id in _ref3) {
      neighborIds = _ref3[id];
      region1 = this.getRegionById(id);
      for (_k = 0, _len2 = neighborIds.length; _k < _len2; _k++) {
        neighborId = neighborIds[_k];
        region2 = this.getRegionById(neighborId);
        this.edgeData.push([region1, region2]);
        (region1.neighbors || (region1.neighbors = [])).push(region2);
        (region2.neighbors || (region2.neighbors = [])).push(region1);
      }
    }
  }

  RegionMap.prototype.getRegionById = function(id) {
    return this.countriesById[id];
  };

  RegionMap.prototype.getNumColorsUsed = function() {
    return _(this.regionData).chain().pluck('fill').compact().uniq().value().length;
  };

  RegionMap.prototype.uncoloredRegionsPresent = function() {
    return _(this.regionData).any(function(d) {
      return !d.fill;
    });
  };

  RegionMap.prototype.clearFills = function() {
    var region, _i, _len, _ref, _results;
    _ref = this.regionData;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      region = _ref[_i];
      _results.push(region.fill = false);
    }
    return _results;
  };

  RegionMap.prototype.clearShades = function() {
    var region, _i, _len, _ref, _results;
    _ref = this.regionData;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      region = _ref[_i];
      _results.push(region.shade = false);
    }
    return _results;
  };

  return RegionMap;

})();

$(function() {
  return d3.json("sa_topo.json", function(error, sa) {
    var activateSection, coloringGame, controller, countryMap, duration, enterSection, height, idToName, leaveSection, miniDiagram1, miniDiagram2, oneWayAdjacencies, paletteHeight, paletteWidth, projection, scene, script, sectionNames, svg, width;
    if (error) {
      return console.error(error);
    }
    width = 400;
    height = 600;
    svg = d3.select("#graphics").append("svg").attr("width", width).attr("height", height);
    projection = d3.geo.mercator().center([-58.6, -25.2]).scale(400).translate([width / 2, height / 2]);
    oneWayAdjacencies = {
      ARG: ['BOL', 'BRA', 'CHX', 'PRY', 'URY'],
      BOL: ['BRA', 'CHX', 'PER', 'PRY'],
      BRA: ['COL', 'GUF', 'GUY', 'PER', 'PRY', 'SUR', 'URY', 'VEN'],
      CHX: ['PER'],
      COL: ['ECD', 'PER', 'VEN'],
      ECD: ['PER'],
      GUF: ['SUR'],
      GUY: ['SUR', 'VEN'],
      PER: [],
      PRY: [],
      SUR: [],
      URY: [],
      VEN: []
    };
    idToName = {
      ARG: 'Argentina',
      BOL: 'Bolivia',
      BRA: 'Brazil',
      CHX: 'Chile',
      COL: 'Columbia',
      ECD: 'Ecuador',
      GUF: 'French Guiana',
      GUY: 'Guyana',
      PER: 'Peru',
      PRY: 'Paraguay',
      SUR: 'Suriname',
      URY: 'Uruguay',
      VEN: 'Venezuela'
    };
    countryMap = new RegionMap({
      json: sa,
      objName: 'sa_geo',
      oneWayAdjacencies: oneWayAdjacencies,
      projection: projection,
      idToName: idToName
    });
    coloringGame = new ColoringGame({
      regionMap: countryMap,
      svg: svg
    });
    window.coloringGame = coloringGame;
    coloringGame.render();
    miniDiagram1 = new ColoringGame({
      regionMap: countryMap,
      svg: d3.select('svg.miniDiagram1'),
      regionIdSubset: ['COL', 'VEN']
    });
    setInterval((function() {
      return miniDiagram1.render();
    }), 500);
    miniDiagram1.render();
    miniDiagram1.parts.borders.style({
      display: 'none'
    });
    miniDiagram2 = new ColoringGame({
      regionMap: countryMap,
      svg: d3.select('svg.miniDiagram2'),
      regionIdSubset: ['COL', 'VEN']
    });
    setInterval((function() {
      return miniDiagram2.render();
    }), 500);
    miniDiagram2.render();
    miniDiagram2.parts.borders.style({
      display: 'none'
    });
    miniDiagram2.parts.solids.style({
      display: 'none'
    });
    miniDiagram2.parts.nodes.attr({
      r: 10
    });
    paletteWidth = 118;
    paletteHeight = 80;
    window.palette = svg.append("g").classed("palette", true).attr({
      transform: utils.translate(width - paletteWidth, 0)
    }).style({
      opacity: 0
    });
    palette.append("rect").attr({
      width: paletteWidth,
      height: paletteHeight
    }).style({
      fill: 'lightgray'
    });
    palette.selectAll(".swatch").data(coloringGame.colors).enter().append("rect").classed("swatch", true).attr({
      x: function(d, i) {
        return 38 * (i % 3) + 5;
      },
      y: function(d, i) {
        return 38 * (~~(i / 3)) + 5;
      },
      width: 32,
      height: 32
    }).style({
      fill: function(d, i) {
        return d;
      },
      cursor: 'pointer'
    }).on({
      click: function(d, i) {
        coloringGame.currentColor = d;
        coloringGame.currentCursor = coloringGame.cursors[i];
        return coloringGame.render();
      }
    });
    d3.select("#clear-colors-link a").on('click', function() {
      countryMap.clearFills();
      return coloringGame.render();
    });
    controller = new ScrollMagic();
    scene = new ScrollScene({
      triggerElement: "h1",
      triggerHook: 0
    }).setPin("#graphics").addTo(controller);
    duration = 0;
    window.addBubble = function(templateName, templateParameters) {
      var bubbleHtml;
      bubbleHtml = _.template($('script.' + templateName).html())(templateParameters);
      $(bubbleHtml).hide().appendTo('[data-section=coloring] .chat').fadeIn('slow');
      return duration = $('#chat-container-container').innerHeight() - $('#chat-container').outerHeight();
    };
    $(window).on('resize', function() {
      return $('[data-section=coloring]').height($(window).innerHeight());
    });
    $(window).triggerHandler('resize');
    new ScrollScene({
      triggerElement: '#chat-container-container',
      triggerHook: 0,
      duration: function() {
        return duration;
      }
    }).setPin("#chat-container-container #chat-container").addTo(controller);
    new ScrollScene({
      triggerElement: '[data-section=coloring]',
      triggerHook: 0.2,
      duration: 0
    }).on('enter', function() {
      return coloringGame.getScared();
    }).addTo(controller);
    sectionNames = function() {
      return d3.selectAll('[data-section]:not(.removed)')[0].map(function(x) {
        return d3.select(x).attr('data-section');
      });
    };
    window.solidsTransform = function(mode) {
      var scalingRatio, shouldTranslate;
      shouldTranslate = (mode === 'smaller') || (mode === 'disappear');
      scalingRatio = (function() {
        switch (mode) {
          case 'original':
            return 1;
          case 'smaller':
            return 0.8;
          case 'disappear':
            return 0;
        }
      })();
      console.log('        solidsTransform', scalingRatio);
      return function(d) {
        var nx, ny, scalingTransform, translationTransform, x, y, _ref, _ref1;
        _ref = d.center, x = _ref[0], y = _ref[1];
        _ref1 = d.nodeCenter, nx = _ref1[0], ny = _ref1[1];
        translationTransform = shouldTranslate ? utils.translate(nx - x, ny - y) : utils.translate(0, 0);
        scalingTransform = utils.scaleAround(scalingRatio, x, y);
        return translationTransform + scalingTransform;
      };
    };
    script = new Script({
      stepNames: sectionNames(),
      steps: {
        intro: function(trans) {
          coloringGame.shouldWiggle = false;
          coloringGame.shouldAnimateNodeColoring = false;
          trans(coloringGame.parts.borders).style({
            opacity: 1
          });
          trans(window.palette).style({
            opacity: 0
          });
          trans(d3.select('#clear-colors-link')).style({
            opacity: 0
          });
          trans(d3.select('#color-count')).style({
            opacity: 0
          });
          trans(coloringGame.parts.solids).style({
            opacity: 0
          });
          trans(coloringGame.parts.solidTransformers).attr({
            transform: solidsTransform('original')
          });
          trans(coloringGame.parts.nodes).attr({
            r: 0
          });
          return trans(coloringGame.parts.edges).style({
            opacity: 0
          });
        },
        coloring: function(trans) {
          trans(window.palette).style({
            opacity: 1
          });
          trans(d3.select('#clear-colors-link')).style({
            opacity: 1
          });
          trans(d3.select('#color-count')).style({
            opacity: 1
          });
          return trans(coloringGame.parts.solids).style({
            opacity: 1
          });
        },
        colored_regions: function(trans) {
          var colorIndex, defaultColoring, id, _results;
          trans(coloringGame.parts.borders).style({
            opacity: 0
          });
          trans(window.palette).style({
            opacity: 0
          });
          trans(d3.select('#clear-colors-link')).style({
            opacity: 0
          });
          coloringGame.currentColor = null;
          coloringGame.currentCursor = null;
          countryMap.clearShades();
          if (countryMap.uncoloredRegionsPresent() || countryMap.getNumColorsUsed() > 4) {
            defaultColoring = {
              ARG: 0,
              BOL: 2,
              BRA: 1,
              CHX: 1,
              COL: 2,
              ECD: 1,
              GUF: 2,
              GUY: 2,
              PER: 3,
              PRY: 3,
              SUR: 3,
              URY: 2,
              VEN: 3
            };
            _results = [];
            for (id in defaultColoring) {
              colorIndex = defaultColoring[id];
              _results.push(countryMap.getRegionById(id).fill = coloringGame.colors[colorIndex]);
            }
            return _results;
          }
        },
        wiggle: function(trans) {
          return coloringGame.shouldWiggle = true;
        },
        unwiggle: function(trans) {
          return coloringGame.shouldWiggle = false;
        },
        smaller_colored_regions: function(trans) {
          console.log('smaller_colored_regions solids transform');
          trans(coloringGame.parts.solidTransformers).attr({
            transform: solidsTransform('smaller')
          });
          return trans(coloringGame.parts.edges).style({
            opacity: 1
          });
        },
        nodes: function(trans) {
          console.log('nodes solids transform');
          trans(coloringGame.parts.solidTransformers).attr({
            transform: solidsTransform('disappear')
          });
          return trans(coloringGame.parts.nodes).attr({
            r: 10
          });
        },
        empty_nodes: function(trans) {
          coloringGame.parts.nodes.style({
            cursor: 'auto'
          });
          coloringGame.shouldAnimateNodeColoring = true;
          return coloringGame.canDragNodes = false;
        },
        definitions: function(trans) {
          coloringGame.parts.nodes.style({
            cursor: 'pointer'
          });
          return coloringGame.canDragNodes = true;
        }
      },
      afterUpdate: function() {
        return coloringGame.render(false);
      }
    });
    activateSection = function(sectionName, hard) {
      $("section.scroll").removeClass("active");
      $("section.scroll[data-section=" + sectionName + "]").addClass("active");
      script.enterStep(sectionName, hard);
    };
    enterSection = function(sectionName) {
      var currentSectionNames, index, thumbnail;
      currentSectionNames = sectionNames();
      index = currentSectionNames.indexOf(sectionName);
      if (index > -1 && index < currentSectionNames.length - 1) {
        activateSection(currentSectionNames[index + 1], false);
      }
      thumbnail = d3.select('section[data-section=' + sectionName + '] .section-thumbnail');
      return thumbnail.transition().duration(600).style({
        opacity: 0.75
      });
    };
    leaveSection = function(sectionName) {
      if (__indexOf.call(sectionNames(), sectionName) >= 0) {
        activateSection(sectionName, false);
      }
    };
    d3.selectAll('[data-section]').each(function() {
      var sectionName;
      sectionName = d3.select(this).attr('data-section');
      return new ScrollScene({
        triggerElement: this,
        triggerHook: 0,
        duration: 0
      }).on('enter', function() {
        return enterSection(sectionName);
      }).on('leave', function() {
        return leaveSection(sectionName);
      }).addTo(controller);
    });
    activateSection(sectionNames()[0], true);
  });
});
