// Generated by CoffeeScript 1.7.1
var ColoredRegion, ColoringGameMapView, ColoringGamePaletteView, ColoringGameRegionView, ColoringGameRegionsView, ColoringGameSvgView, ColoringGameView, DOM, Region, RegionColor, RegionsData, colors, cx, drawGrid, howManySvg, instanceOf, layoutPropType, reactCreateClass, sqSize, xtend,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

DOM = React.DOM;

instanceOf = React.PropTypes.instanceOf;

cx = React.addons.classSet;

xtend = utils.xtend, reactCreateClass = utils.reactCreateClass;

RegionsData = (function() {
  function RegionsData(_arg) {
    var id, neighborId, neighborIds, region1, region2, _i, _len, _ref;
    this.json = _arg.json, this.objName = _arg.objName, this.oneWayAdjacencies = _arg.oneWayAdjacencies, this.projection = _arg.projection;
    this.jsonFeatures = topojson.feature(this.json, this.json.objects[this.objName]).features;
    window.json = this.json;
    this.jsonBorder = topojson.mesh(this.json, this.json.objects[this.objName]);
    this.path = d3.geo.path().projection(this.projection);
    this.regions = _.map(this.jsonFeatures, (function(_this) {
      return function(jsonFeature) {
        return new Region(jsonFeature, _this.path);
      };
    })(this));
    this.regionsById = _(this.regions).chain().map(function(d) {
      return [d.id, d];
    }).object().value();
    this.edgeData = [];
    _ref = this.oneWayAdjacencies;
    for (id in _ref) {
      neighborIds = _ref[id];
      region1 = this.getRegionById(id);
      for (_i = 0, _len = neighborIds.length; _i < _len; _i++) {
        neighborId = neighborIds[_i];
        region2 = this.getRegionById(neighborId);
        this.edgeData.push([region1, region2]);
        (region1.neighbors || (region1.neighbors = [])).push(region2);
        (region2.neighbors || (region2.neighbors = [])).push(region1);
      }
    }
  }

  RegionsData.prototype.getRegionById = function(id) {
    return this.regionsById[id];
  };

  return RegionsData;

})();

Region = (function() {
  function Region(jsonFeature, pathMaker) {
    var x, y, _ref;
    this.jsonFeature = jsonFeature;
    this.name = jsonFeature.properties.name;
    this.id = jsonFeature.id;
    _ref = pathMaker.centroid(jsonFeature), x = _ref[0], y = _ref[1];
    this.center = [x, y];
    if (this.id === 'BRA') {
      x += 25;
    }
    if (this.id === 'SUR') {
      x += 8;
    }
    if (this.id === 'GUF') {
      x += 16;
    }
    this.nodeCenter = [x, y];
  }

  return Region;

})();

ColoredRegion = (function(_super) {
  __extends(ColoredRegion, _super);

  function ColoredRegion(region, color, forbidden) {
    this.color = color;
    this.forbidden = forbidden;
    _.extend(this, region);
  }

  return ColoredRegion;

})(Region);

RegionColor = (function() {
  function RegionColor(cssColor, brushCursorPrefix) {
    this.cssColor = cssColor;
    this.brushCursorPrefix = brushCursorPrefix;
  }

  return RegionColor;

})();

layoutPropType = React.PropTypes.shape({
  width: React.PropTypes.number.isRequired,
  height: React.PropTypes.number.isRequired
});

ColoringGameSvgView = reactCreateClass('ColoringGameSvgView', {
  propTypes: {
    layout: layoutPropType.isRequired,
    regionsData: instanceOf(RegionsData).isRequired
  },
  render: function() {
    return DOM.svg({
      width: this.props.layout.width,
      height: this.props.layout.height
    }, ColoringGameView(xtend(this.props, {
      ref: 'coloringGame'
    })));
  }
});

ColoringGameView = reactCreateClass('ColoringGameView', {
  propTypes: {
    layout: layoutPropType.isRequired,
    regionsData: instanceOf(RegionsData).isRequired,
    colors: React.PropTypes.arrayOf(RegionColor).isRequired
  },
  getInitialState: function() {
    return {
      brushColor: null,
      coloring: {}
    };
  },
  render: function() {
    var coloredRegions, pathMaker, _ref;
    pathMaker = this.props.regionsData.path;
    coloredRegions = this.getColoredRegions();
    return DOM.g({}, ColoringGameMapView(xtend(this.props, {
      pathMaker: pathMaker,
      coloredRegions: coloredRegions,
      brushCursorPrefix: (_ref = this.state.brushColor) != null ? _ref.brushCursorPrefix : void 0,
      colorRegion: this.colorRegion
    })), this.props.layout.colorable ? ColoringGamePaletteView(xtend(this.props, {
      setBrushColor: this.setBrushColor
    })) : void 0);
  },
  getColoredRegions: function() {
    var color, coloredRegions, forbiddenRegionIds, neighborRegion, region, regionId, _i, _len, _ref, _ref1;
    forbiddenRegionIds = [];
    _ref = this.state.coloring;
    for (regionId in _ref) {
      color = _ref[regionId];
      if (color === this.state.brushColor) {
        _ref1 = this.props.regionsData.getRegionById(regionId).neighbors;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          neighborRegion = _ref1[_i];
          forbiddenRegionIds.push(neighborRegion.id);
        }
      }
    }
    coloredRegions = (function() {
      var _j, _len1, _ref2, _ref3, _results;
      _ref2 = this.props.regionsData.regions;
      _results = [];
      for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
        region = _ref2[_j];
        _results.push(new ColoredRegion(region, this.state.coloring[region.id], (_ref3 = region.id, __indexOf.call(forbiddenRegionIds, _ref3) >= 0)));
      }
      return _results;
    }).call(this);
    return coloredRegions;
  },
  setBrushColor: function(color) {
    return this.setState({
      brushColor: color
    });
  },
  colorRegion: function(region) {
    var newColoring;
    newColoring = _.clone(this.state.coloring);
    newColoring[region.id] = this.state.brushColor;
    return this.setState({
      coloring: newColoring
    });
  }
});

ColoringGamePaletteView = reactCreateClass('ColoringGamePaletteView', {
  render: function() {
    var color, i, paletteHeight, paletteWidth, width, _ref;
    _ref = this.props.layout, width = _ref.width, paletteWidth = _ref.paletteWidth, paletteHeight = _ref.paletteHeight;
    return DOM.g({
      className: 'palette',
      transform: utils.translate(width - paletteWidth, 0),
      style: {
        opacity: 1
      }
    }, DOM.rect({
      className: 'background',
      width: paletteWidth,
      height: paletteHeight
    }), (function() {
      var _i, _len, _ref1, _results;
      _ref1 = this.props.colors;
      _results = [];
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        color = _ref1[i];
        _results.push((function(_this) {
          return function(color, i) {
            return DOM.rect({
              key: color.cssColor,
              className: 'swatch',
              width: 32,
              height: 32,
              x: 38 * (i % 3) + 5,
              y: 38 * (~~(i / 3)) + 5,
              style: {
                fill: color.cssColor,
                cursor: 'pointer'
              },
              onClick: function() {
                return _this.props.setBrushColor(color);
              }
            });
          };
        })(this)(color, i));
      }
      return _results;
    }).call(this));
  }
});

ColoringGameMapView = reactCreateClass('ColoringGameMapView', {
  propTypes: {
    coloredRegions: React.PropTypes.arrayOf(instanceOf(ColoredRegion)).isRequired,
    regionsData: instanceOf(RegionsData).isRequired,
    pathMaker: React.PropTypes.func.isRequired
  },
  render: function() {
    return DOM.g({}, ColoringGameRegionsView(this.props), DOM.path({
      className: 'borders',
      d: this.props.pathMaker(this.props.regionsData.jsonBorder)
    }));
  }
});

ColoringGameRegionsView = reactCreateClass('ColoringGameRegionsView', {
  propTypes: {
    coloredRegions: React.PropTypes.arrayOf(instanceOf(ColoredRegion)).isRequired,
    pathMaker: React.PropTypes.func.isRequired
  },
  render: function() {
    var coloredRegion;
    return DOM.g({
      className: 'regions'
    }, (function() {
      var _i, _len, _ref, _results;
      _ref = this.props.coloredRegions;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        coloredRegion = _ref[_i];
        _results.push(ColoringGameRegionView({
          key: coloredRegion.id,
          coloredRegion: coloredRegion,
          pathMaker: this.props.pathMaker,
          brushCursorPrefix: this.props.brushCursorPrefix,
          colorRegion: this.props.colorRegion
        }));
      }
      return _results;
    }).call(this));
  }
});

ColoringGameRegionView = reactCreateClass('ColoringGameRegionView', {
  propTypes: {
    coloredRegion: instanceOf(ColoredRegion).isRequired,
    brushCursorPrefix: React.PropTypes.string
  },
  render: function() {
    var brushCursorSuffix, color, cursor, forbidden, jsonFeature, _ref;
    _ref = this.props.coloredRegion, forbidden = _ref.forbidden, jsonFeature = _ref.jsonFeature, color = _ref.color;
    brushCursorSuffix = forbidden ? '_cross' : '';
    cursor = this.props.brushCursorPrefix ? 'url(' + this.props.brushCursorPrefix + brushCursorSuffix + '.png) 8 30, auto' : void 0;
    return DOM.g({
      className: 'region'
    }, DOM.g({
      className: 'fill-transformer'
    }, DOM.path({
      className: 'fill',
      d: this.props.pathMaker(jsonFeature),
      style: {
        fill: color != null ? color.cssColor : void 0,
        cursor: cursor
      },
      onClick: (function(_this) {
        return function() {
          if (!forbidden) {
            return _this.props.colorRegion(_this.props.coloredRegion);
          }
        };
      })(this)
    })), DOM.circle({
      className: 'node'
    }));
  }
});

howManySvg = d3.select('#cartographer-howmany').append('svg').style({
  'margin-left': 20,
  'margin-top': 40
}).attr({
  height: 190
});

colors = ['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)'];

sqSize = 30;

drawGrid = function(colorMaker, hTrans, vTrans, text1, text2) {
  var i, j, _i, _j;
  for (i = _i = 0; _i < 3; i = ++_i) {
    for (j = _j = 0; _j < 4; j = ++_j) {
      howManySvg.append('rect').attr({
        transform: utils.translate(sqSize * i + 1 + hTrans, sqSize * j + 1 + vTrans),
        width: sqSize,
        height: sqSize
      }).style({
        fill: colorMaker(i, j),
        stroke: 'black'
      });
    }
  }
  howManySvg.append('text').attr({
    transform: utils.translate(hTrans + sqSize * 1.5, sqSize * 4.8 + vTrans)
  }).style({
    'text-anchor': 'middle'
  }).text(text1);
  return howManySvg.append('text').attr({
    transform: utils.translate(hTrans + sqSize * 1.5, -15 + vTrans)
  }).style({
    'text-anchor': 'middle'
  }).text(text2);
};

drawGrid((function(i, j) {
  return colors[i % 3 + 3 * (j % 2)];
}), sqSize * 5.5, 30, '(worse)', '6 colors');

drawGrid((function(i, j) {
  return colors[i % 2 + 2 * (j % 2)];
}), 0, 30, '(better)', '4 colors');

howManySvg.append('text').attr({
  transform: utils.translate(sqSize * 3 + 40, 30 + sqSize * 2)
}).style({
  'alignment-baseline': 'central',
  'text-anchor': 'middle',
  'font-size': 55
}).text('>');

d3.json("sa_topo.json", function(error, sa) {
  var args, colorPairs, coloringGameSvgView, layout, oneWayAdjacencies, oxfordJoin, projection, regionsData;
  if (error) {
    return console.error(error);
  }
  layout = {
    width: 400,
    height: 600,
    paletteWidth: 118,
    paletteHeight: 80
  };
  projection = d3.geo.mercator().center([-58.6, -25.2]).scale(400).translate([layout.width / 2, layout.height / 2]);
  oneWayAdjacencies = {
    ARG: ['BOL', 'BRA', 'CHX', 'PRY', 'URY'],
    BOL: ['BRA', 'CHX', 'PER', 'PRY'],
    BRA: ['COL', 'GUF', 'GUY', 'PER', 'PRY', 'SUR', 'URY', 'VEN'],
    CHX: ['PER'],
    COL: ['ECD', 'PER', 'VEN'],
    ECD: ['PER'],
    GUF: ['SUR'],
    GUY: ['SUR', 'VEN'],
    PER: [],
    PRY: [],
    SUR: [],
    URY: [],
    VEN: []
  };
  regionsData = new RegionsData({
    json: sa,
    objName: 'sa_geo',
    oneWayAdjacencies: oneWayAdjacencies,
    projection: projection
  });
  colorPairs = _.zip(['rgb(228,26,28)', 'rgb(55,126,184)', 'rgb(77,175,74)', 'rgb(152,78,163)', 'rgb(255,127,0)', 'rgb(255,255,51)'], ['red', 'blue', 'green', 'purple', 'orange', 'yellow']);
  colors = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = colorPairs.length; _i < _len; _i++) {
      args = colorPairs[_i];
      _results.push((function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(RegionColor, args, function(){}));
    }
    return _results;
  })();
  React.render(ColoringGameSvgView({
    layout: layout,
    regionsData: regionsData,
    colors: colors
  }), d3.select('#cartographer-outlines').node());
  coloringGameSvgView = React.render(ColoringGameSvgView({
    layout: xtend(layout, {
      colorable: true
    }),
    regionsData: regionsData,
    colors: colors
  }), d3.select('#cartographer-coloring').node());
  oxfordJoin = function(items, conjunction) {
    var i, item, toJoin;
    if (items.length === 0) {
      return '';
    } else if (items.length === 1) {
      return items[0];
    } else if (items.length === 2) {
      return items[0] + " " + conjunction + ' ' + items[1];
    } else {
      toJoin = (function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = items.length; _i < _len; i = ++_i) {
          item = items[i];
          if (i < items.length - 1) {
            _results.push(item);
          } else {
            _results.push(conjunction + ' ' + item);
          }
        }
        return _results;
      })();
      return toJoin.join(', ');
    }
  };
  window.oxfordJoin = oxfordJoin;
  return d3.select('#cartographer-done').on('click', function() {
    var coloring, coloringGame, message, numColors, uncoloredRegions, uncoloredRegionsMessage;
    coloringGame = coloringGameSvgView.refs.coloringGame;
    regionsData = coloringGame.props.regionsData;
    coloring = coloringGame.state.coloring;
    uncoloredRegions = _(regionsData.regions).filter(function(r) {
      return !(r.id in coloring);
    });
    message = uncoloredRegions.length ? (uncoloredRegionsMessage = oxfordJoin(_(uncoloredRegions).pluck('name'), 'or'), "Close, but you haven't colored " + uncoloredRegionsMessage + ". (White doesn't count as a color, smart-aleck.)") : (numColors = _(coloring).chain().values().unique().value().length, "Nice! You pulled it off with " + numColors + " colors. Do you think it's possible to do better than that? Give that some thought.");
    return d3.select('#cartographer-done-msg').html(message);
  });
});
