// Generated by CoffeeScript 1.7.1
var AbstractNode, AtomType, DOM, EditorNodeViewContext, EvaluationContext, ExpressionView, FanOutView, ForEachNode, ForEachNodeView, FunctionNode, ImmutableRecordExtending, ImmutableRecordFromKeys, IntegerType, MinusNode, MysteryNode, NodeHarnessView, NodeListView, NodeView, NodeViewContext, PT, PickNode, PickNodeView, RangeNode, SetType, SingletonNode, SymbolReferenceNode, ToolboxNodeViewContext, TupleNode, TupleType, Type, TypingContext, UndefinedValue, UnknownType, Value, addTyping, cx, nodeViewPropTypes, reactCreateClass, testEvaluationContext, testNode, testTypingContext, testView, xtend,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DOM = React.DOM;

PT = React.PropTypes;

cx = React.addons.classSet;

xtend = utils.xtend, reactCreateClass = utils.reactCreateClass, ImmutableRecordExtending = utils.ImmutableRecordExtending, ImmutableRecordFromKeys = utils.ImmutableRecordFromKeys;

Value = (function() {
  function Value(contents) {
    this.contents = contents;
  }

  Value.prototype.isUndefined = function() {
    return false;
  };

  return Value;

})();

UndefinedValue = (function() {
  function UndefinedValue() {}

  UndefinedValue.prototype.isUndefined = function() {
    return true;
  };

  return UndefinedValue;

})();

Type = (function() {
  function Type() {}

  Type.prototype.toString = function() {
    throw 'Not implemented!';
  };

  Type.prototype.equals = function(other) {
    throw 'Not implemented!';
  };

  return Type;

})();

AtomType = (function(_super) {
  __extends(AtomType, _super);

  function AtomType() {
    return AtomType.__super__.constructor.apply(this, arguments);
  }

  AtomType.prototype.toString = function() {
    return "ATOM";
  };

  AtomType.prototype.equals = function(other) {
    return other instanceof AtomType;
  };

  return AtomType;

})(Type);

IntegerType = (function(_super) {
  __extends(IntegerType, _super);

  function IntegerType() {
    return IntegerType.__super__.constructor.apply(this, arguments);
  }

  IntegerType.prototype.toString = function() {
    return "INTEGER";
  };

  IntegerType.prototype.equals = function(other) {
    return other instanceof IntegerType;
  };

  return IntegerType;

})(Type);

TupleType = (function(_super) {
  __extends(TupleType, _super);

  function TupleType(elementTypes) {
    this.elementTypes = elementTypes;
    console.log('tupletype', this.elementTypes.toJS());
    this.elementTypes.forEach((function(_this) {
      return function(type) {
        if (!(type instanceof Type)) {
          throw 'Invalid type';
        }
      };
    })(this));
  }

  TupleType.prototype.toString = function() {
    return "TUPLE(" + this.elementTypes.invoke('toString').join(', ') + ")";
  };

  TupleType.prototype.equals = function(other) {
    if (!(other instanceof TupleType)) {
      return false;
    }
    if (!(this.elementTypes.size === other.elementTypes.size)) {
      return false;
    }
    return this.elementTypes.zip(other.elementTypes).every(function(type1, type2) {
      return type1.equals(type2);
    });
  };

  return TupleType;

})(Type);

SetType = (function(_super) {
  __extends(SetType, _super);

  function SetType(elementType) {
    this.elementType = elementType;
    if (!(elementType instanceof Type)) {
      throw 'Invalid type';
    }
  }

  SetType.prototype.toString = function() {
    return "SET(" + this.elementType.toString() + ")";
  };

  SetType.prototype.equals = function(other) {
    if (!(other instanceof SetType)) {
      return false;
    }
    return this.elementType.equals(other.elementType);
  };

  return SetType;

})(Type);

UnknownType = (function(_super) {
  __extends(UnknownType, _super);

  function UnknownType() {
    return UnknownType.__super__.constructor.apply(this, arguments);
  }

  UnknownType.prototype.toString = function() {
    return "UNKNOWN";
  };

  UnknownType.prototype.equals = function(other) {
    return true;
  };

  return UnknownType;

})(Type);

EvaluationContext = (function(_super) {
  __extends(EvaluationContext, _super);

  function EvaluationContext(symbolValues) {
    if (symbolValues == null) {
      symbolValues = Immutable.Map();
    }
    EvaluationContext.__super__.constructor.call(this, {
      symbolValues: symbolValues
    });
  }

  EvaluationContext.prototype.getSymbolValue = function(symbolName) {
    return this.symbolValues.get(symbolName);
  };

  EvaluationContext.prototype.extend = function(symbolName, symbolValue) {
    return this.set('symbolValues', this.symbolValues.set(symbolName, symbolValue));
  };

  EvaluationContext.prototype.getSymbols = function() {
    return this.symbolValues.keySeq();
  };

  return EvaluationContext;

})(ImmutableRecordFromKeys(['symbolValues']));

TypingContext = (function(_super) {
  __extends(TypingContext, _super);

  function TypingContext(symbolTypes) {
    if (symbolTypes == null) {
      symbolTypes = Immutable.Map();
    }
    TypingContext.__super__.constructor.call(this, {
      symbolTypes: symbolTypes
    });
  }

  TypingContext.prototype.getSymbolType = function(symbolName) {
    return this.symbolTypes.get(symbolName, new UnknownType());
  };

  TypingContext.prototype.extend = function(symbolName, symbolType) {
    if (!symbolType instanceof Type) {
      throw 'Invalid symbol type';
    }
    return this.set('symbolTypes', this.symbolTypes.set(symbolName, symbolType));
  };

  TypingContext.prototype.getSymbols = function() {
    return this.symbolTypes.keySeq();
  };

  return TypingContext;

})(ImmutableRecordFromKeys(['symbolTypes']));

AbstractNode = Immutable.Record({
  typingContext: null,
  type: null,
  path: null,
  evaluate: function(evaluationContext) {
    throw 'Not implemented!';
  },
  getView: function(evaluationContext) {
    return false;
  }
});

addTyping = function(node, typingContext, type, path) {
  return node.merge({
    typingContext: typingContext,
    type: type,
    path: path
  });
};

ForEachNode = ImmutableRecordExtending(AbstractNode, {
  iteratorSymbolName: null,
  domainNode: null,
  expressionNode: null,
  ctor: function(iteratorSymbolName, domainNode, expressionNode) {
    if (!_.isString(iteratorSymbolName)) {
      throw 'Invalid argument';
    }
    if (!(domainNode instanceof AbstractNode)) {
      throw 'Invalid argument';
    }
    if (!(expressionNode instanceof AbstractNode)) {
      throw 'Invalid argument';
    }
    return this["super"]({
      iteratorSymbolName: iteratorSymbolName,
      domainNode: domainNode,
      expressionNode: expressionNode
    });
  },
  evaluate: function(evaluationContext) {
    var evaluatedDomain, evaluatedElement, newEvaluationContext, sets;
    evaluatedDomain = this.domainNode.evaluate(evaluationContext);
    sets = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = evaluatedDomain.length; _i < _len; _i++) {
        evaluatedElement = evaluatedDomain[_i];
        newEvaluationContext = evaluationContext.extend(this.iteratorSymbolName, evaluatedElement);
        _results.push(this.expressionNode.evaluate(newEvaluationContext));
      }
      return _results;
    }).call(this);
    return Array.prototype.concat.apply([], sets);
  },
  applyTypingContext: function(typingContext, path) {
    var typedDomainNode, typedExpressionNode, typingContextForExpressionNode;
    typedDomainNode = this.domainNode.applyTypingContext(typingContext, path.push('domainNode'));
    typingContextForExpressionNode = typingContext.extend(this.iteratorSymbolName, typedDomainNode.type.elementType || new UnknownType());
    typedExpressionNode = this.expressionNode.applyTypingContext(typingContextForExpressionNode, path.push('expressionNode'));
    return addTyping(new this.constructor(this.iteratorSymbolName, typedDomainNode, typedExpressionNode), typingContext, typedExpressionNode.type, path);
  },
  toString: function() {
    return "FOR " + this.iteratorSymbolName + " IN " + (this.domainNode.toString()) + ": " + (this.expressionNode.toString());
  }
});

SymbolReferenceNode = ImmutableRecordExtending(AbstractNode, {
  symbolName: null,
  ctor: function(symbolName) {
    return this["super"]({
      symbolName: symbolName
    });
  },
  evaluate: function(evaluationContext) {
    return evaluationContext.getSymbolValue(this.symbolName);
  },
  applyTypingContext: function(typingContext, path) {
    return addTyping(new this.constructor(this.symbolName), typingContext, typingContext.getSymbolType(this.symbolName), path);
  },
  getView: function(evaluationContext) {
    return [DOM.code({}, this.symbolName)];
  },
  toString: function() {
    return this.symbolName;
  }
});

MysteryNode = ImmutableRecordExtending(AbstractNode, {
  ctor: function() {
    return this["super"]({});
  },
  getView: function(evaluationContext) {
    return '???';
  },
  evaluate: function(evaluationContext) {
    return void 0;
  },
  applyTypingContext: function(typingContext, path) {
    return addTyping(new this.constructor(), typingContext, new UnknownType(), path);
  },
  toString: function() {
    return '???';
  }
});

FunctionNode = ImmutableRecordExtending(AbstractNode, {
  func: null,
  childNodes: null,
  ctor: function(func, childNodes) {
    return this["super"]({
      func: func,
      childNodes: childNodes
    });
  },
  evaluate: function(evaluationContext) {
    var evaluatedChildNodes;
    evaluatedChildNodes = this.childNodes.invoke('evaluate', evaluationContext).toJS();
    return this.func(evaluatedChildNodes);
  },
  applyTypingContext: function(typingContext, path) {
    var typedChildNodes;
    typedChildNodes = this.childNodes.map(function(childNode, key) {
      return childNode.applyTypingContext(typingContext, path.push('nodes', key));
    });
    return addTyping(this.set('childNodes', typedChildNodes), typingContext, this.getTypeFromChildTypes(typedChildNodes.pluck('type')), path);
  },
  getTypeFromChildTypes: function(childTypes) {
    throw 'Not implemented!';
  },
  getView: function(childTypes) {
    throw 'Not implemented!';
  },
  viewForChild: function(childNameOrNode, nodeViewContext) {
    var node;
    node = _.isString(childNameOrNode) ? this.childNodes.get(childNameOrNode) : childNameOrNode;
    return NodeView({
      node: node,
      nodeViewContext: nodeViewContext.forChild()
    });
  }
});

TupleNode = ImmutableRecordExtending(FunctionNode, {
  ctor: function(childNodes) {
    var func;
    func = function(values) {
      return values;
    };
    return this["super"]({
      func: func,
      childNodes: childNodes
    });
  },
  getTypeFromChildTypes: function(childTypes) {
    return new TupleType(childTypes);
  },
  getView: function(nodeViewContext) {
    return [
      '[', this.childNodes.mapToJS((function(_this) {
        return function(childNode, i) {
          return [_this.viewForChild(childNode, nodeViewContext), i < _this.nodes.size - 1 ? ', ' : ''];
        };
      })(this)), ']'
    ];
  },
  toString: function() {
    return 'TUPLE(' + this.childNodes.invoke('toString').join(', ') + ')';
  }
});

SingletonNode = ImmutableRecordExtending(FunctionNode, {
  ctor: function(childNode) {
    var childNodes, func;
    childNodes = Immutable.Map({
      childNode: childNode
    });
    func = function(_arg) {
      var childValue;
      childValue = _arg.childNode;
      return [childValue];
    };
    return this["super"]({
      func: func,
      childNodes: childNodes
    });
  },
  getTypeFromChildTypes: function(childTypes) {
    return new SetType(childTypes.get('childNode'));
  },
  getView: function(nodeViewContext) {
    return ['{', this.viewForChild('childNode', nodeViewContext), '}'];
  },
  toString: function() {
    return "SINGLETON(" + (this.childNodes.get('childNode').toString()) + ")";
  }
});

PickNode = ImmutableRecordExtending(SingletonNode, {
  getView: function(nodeViewContext) {
    return null;
  },
  toString: function() {
    return "PICK(" + (this.childNodes.get('childNode').toString()) + ")";
  }
});

MinusNode = ImmutableRecordExtending(FunctionNode, {
  ctor: function(node1, node2) {
    var childNodes, func;
    childNodes = Immutable.Map({
      node1: node1,
      node2: node2
    });
    func = function(_arg) {
      var value1, value2;
      value1 = _arg.node1, value2 = _arg.node2;
      return _.difference(value1, value2);
    };
    return this["super"]({
      childNodes: childNodes,
      func: func
    });
  },
  getTypeFromChildTypes: function(childTypes) {
    return childTypes.get('node1');
  },
  getName: function() {
    return 'Minus';
  },
  getView: function(nodeViewContext) {
    return [this.viewForChild('node1', nodeViewContext), " - ", this.viewForChild('node2', nodeViewContext)];
  },
  toString: function() {
    return "MINUS(" + (this.childNodes.get('node1').toString()) + ", " + (this.childNodes.get('node2').toString()) + ")";
  }
});

RangeNode = ImmutableRecordExtending(FunctionNode, {
  ctor: function(startNode, endNode) {
    var func, nodes;
    nodes = Immutable.Map({
      startNode: startNode,
      endNode: endNode
    });
    func = (function(_arg) {
      var endValue, startValue, _i, _results;
      startValue = _arg.startNode, endValue = _arg.endNode;
      return (function() {
        _results = [];
        for (var _i = startValue; startValue <= endValue ? _i <= endValue : _i >= endValue; startValue <= endValue ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this);
    });
    return this["super"]({
      func: func,
      nodes: nodes
    });
  },
  getTypeFromChildTypes: function(childTypes) {
    return new SetType(new IntegerType());
  },
  getView: function(nodeViewContext) {
    return ['Count from ', this.viewForChild('startNode', nodeViewContext), ' to ', this.viewForChild('endNode', nodeViewContext)];
  },
  toString: function() {
    return "RANGE(" + (this.childNodes.get('startNode').toString()) + ", " + (this.childNodes.get('endNode').toString()) + ")";
  }
});

NodeViewContext = Immutable.Record({
  selectedNodePath: null,
  forChild: function() {
    return this;
  },
  isSelected: function(node) {
    return false;
  },
  onClick: function(ev, node) {}
});

ToolboxNodeViewContext = ImmutableRecordExtending(NodeViewContext, {
  topLevel: null,
  onTopLevelClick: null,
  ctor: function(topLevel, onTopLevelClick) {
    return this["super"]({
      topLevel: topLevel,
      onTopLevelClick: onTopLevelClick
    });
  },
  forChild: function() {
    return this.set('topLevel', false);
  },
  onClick: function(ev, node) {
    if (this.topLevel) {
      this.onTopLevelClick(node);
      return ev.stopPropagation();
    }
  }
});

EditorNodeViewContext = ImmutableRecordExtending(NodeViewContext, {
  evaluationContext: null,
  selectedNodePath: null,
  doSelectNode: null,
  doSetNodeProperty: null,
  ctor: function(evaluationContext, doSelectNode, doSetNodeProperty, selectedNodePath) {
    return this["super"]({
      evaluationContext: evaluationContext,
      doSelectNode: doSelectNode,
      doSetNodeProperty: doSetNodeProperty,
      selectedNodePath: selectedNodePath
    });
  },
  isSelected: function(node) {
    var _ref;
    return (_ref = this.selectedNodePath) != null ? _ref.equals(node.path) : void 0;
  },
  onClick: function(ev, node) {
    this.doSelectNode(node);
    return ev.stopPropagation();
  }
});

nodeViewPropTypes = {
  node: PT.instanceOf(AbstractNode).isRequired,
  nodeViewContext: PT.instanceOf(NodeViewContext).isRequired
};

NodeView = reactCreateClass('NodeView', {
  propTypes: nodeViewPropTypes,
  render: function() {
    var node, nodeViewContext, view, _ref;
    _ref = this.props, node = _ref.node, nodeViewContext = _ref.nodeViewContext;
    view = node.getView(nodeViewContext);
    if (view) {
      return ExpressionView({
        view: view,
        node: node,
        nodeViewContext: nodeViewContext
      });
    } else if (node instanceof PickNode) {
      return PickNodeView(this.props);
    } else if (node instanceof ForEachNode) {
      return ForEachNodeView(this.props);
    } else if (node instanceof FunctionNode) {
      return FunctionNodeView(this.props);
    } else {
      return DOM.div({}, "UNKNOWN NODE TYPE: " + (JSON.stringify(node)));
    }
  }
});

FanOutView = reactCreateClass('FanOutView', {
  propTypes: {
    heights: PT.arrayOf(PT.number).isRequired,
    curveWidth: PT.number.isRequired,
    flatWidth: PT.number.isRequired,
    labels: PT.arrayOf(PT.string)
  },
  render: function() {
    var curveWidth, diagonal, flatWidth, h, heights, i, labels, totalHeight, y, yOffsets, _i, _len, _ref;
    _ref = this.props, heights = _ref.heights, curveWidth = _ref.curveWidth, flatWidth = _ref.flatWidth, labels = _ref.labels;
    y = 0;
    yOffsets = [];
    for (_i = 0, _len = heights.length; _i < _len; _i++) {
      h = heights[_i];
      yOffsets.push(y + h / 2);
      y += h;
    }
    totalHeight = y;
    return DOM.svg({
      width: curveWidth + flatWidth,
      height: totalHeight,
      style: {
        verticalAlign: 'middle'
      }
    }, (function() {
      var _j, _len1, _results;
      _results = [];
      for (i = _j = 0, _len1 = yOffsets.length; _j < _len1; i = ++_j) {
        y = yOffsets[i];
        diagonal = d3.svg.diagonal().source({
          y: 0,
          x: totalHeight / 2
        }).target({
          y: curveWidth,
          x: y
        }).projection(function(d) {
          return [d.y, d.x];
        });
        _results.push(DOM.g({
          key: i
        }, DOM.path({
          d: diagonal(),
          style: {
            stroke: 'black',
            fill: 'none'
          }
        }), DOM.line({
          x1: curveWidth,
          x2: curveWidth + flatWidth,
          y1: y,
          y2: y,
          style: {
            stroke: 'black',
            fill: 'none'
          }
        }), labels ? DOM.text({
          x: curveWidth,
          y: y - 3
        }, labels[i]) : void 0));
      }
      return _results;
    })());
  }
});

ForEachNodeView = reactCreateClass('ForEachNodeView', {
  propTypes: nodeViewPropTypes,
  getInitialState: function() {
    return {
      childRowHeights: []
    };
  },
  render: function() {
    var doSetNodeProperty, element, evaluatedDomain, evaluationContext, i, labels, newNodeViewContext, node, nodeViewContext, selectedNodePath, _ref;
    _ref = this.props, node = _ref.node, nodeViewContext = _ref.nodeViewContext;
    evaluationContext = nodeViewContext.evaluationContext, selectedNodePath = nodeViewContext.selectedNodePath, doSetNodeProperty = nodeViewContext.doSetNodeProperty;
    if (evaluationContext && (evaluatedDomain = node.domainNode.evaluate(evaluationContext))) {
      this.numChildren = evaluatedDomain.length;
      labels = (function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = evaluatedDomain.length; _i < _len; i = ++_i) {
          element = evaluatedDomain[i];
          _results.push("" + node.iteratorSymbolName + " = " + element);
        }
        return _results;
      })();
    } else {
      evaluatedDomain = [];
      this.numChildren = 0;
    }
    return DOM.table({}, DOM.tbody({}, DOM.tr({
      style: {
        background: nodeViewContext.isSelected(node) ? 'lightgray' : 'white'
      }
    }, DOM.td({
      style: {
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        margin: 0,
        padding: 0,
        cursor: nodeViewContext ? 'pointer' : void 0
      },
      onClick: (function(_this) {
        return function(ev) {
          return nodeViewContext.onClick(ev, node);
        };
      })(this)
    }, DOM.div({
      style: {
        display: 'inline-block',
        padding: 3,
        margin: 0
      }
    }, 'Choose ', DOM.input({
      value: node.iteratorSymbolName,
      onChange: (function(_this) {
        return function(event) {
          return doSetNodeProperty(node, 'iteratorSymbolName', event.target.value);
        };
      })(this),
      style: {
        width: 30
      }
    }), ' from ', NodeView({
      node: node.domainNode,
      nodeViewContext: nodeViewContext.forChild()
    })), ' ', FanOutView({
      curveWidth: 50,
      flatWidth: 60,
      heights: this.state.childRowHeights,
      labels: labels
    })), DOM.td({
      ref: 'contents',
      style: {
        margin: 0
      }
    }, DOM.table({
      style: {
        margin: 0
      }
    }, DOM.tbody({
      style: {
        margin: 0
      }
    }, (function() {
      var _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = evaluatedDomain.length; _i < _len; i = ++_i) {
        element = evaluatedDomain[i];
        newNodeViewContext = nodeViewContext.set('evaluationContext', evaluationContext != null ? evaluationContext.extend(node.iteratorSymbolName, element) : void 0);
        _results.push(DOM.tr({
          ref: 'row' + i,
          key: utils.objHash(element),
          style: {
            margin: 0
          }
        }, DOM.td({
          style: {
            margin: 0
          }
        }, NodeView({
          node: node.expressionNode,
          nodeViewContext: newNodeViewContext
        }))));
      }
      return _results;
    })()))))));
  },
  componentDidMount: function() {
    return this.updateBraceHeight();
  },
  componentDidUpdate: function() {
    return this.updateBraceHeight();
  },
  updateBraceHeight: function() {
    var childRowHeights, h1, h2, i;
    if (this.numChildren) {
      childRowHeights = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.numChildren; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push($(this.refs['row' + i].getDOMNode()).height());
        }
        return _results;
      }).call(this);
      if (!_.all((function() {
        var _i, _len, _ref, _ref1, _results;
        _ref = _.zip(childRowHeights, this.state.childRowHeights);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          _ref1 = _ref[_i], h1 = _ref1[0], h2 = _ref1[1];
          _results.push(h1 === h2);
        }
        return _results;
      }).call(this))) {
        return this.setState({
          childRowHeights: childRowHeights
        });
      }
    }
  }
});

PickNodeView = reactCreateClass('PickNodeView', {
  propTypes: nodeViewPropTypes,
  render: function() {
    var evaluationContext, node, nodeViewContext, selectedNodePath, _ref;
    _ref = this.props, node = _ref.node, nodeViewContext = _ref.nodeViewContext;
    evaluationContext = nodeViewContext.evaluationContext, selectedNodePath = nodeViewContext.selectedNodePath;
    return DOM.span({}, ExpressionView(xtend(this.props, {
      view: [
        'Pick ', NodeView({
          node: node.node,
          nodeViewContext: nodeViewContext.forChild()
        })
      ]
    })), evaluationContext ? ['\u2192 ', JSON.stringify(node.evaluate(evaluationContext)[0])] : void 0);
  }
});

ExpressionView = reactCreateClass('ExpressionView', {
  propTypes: xtend(nodeViewPropTypes, {
    view: PT.node.isRequired
  }),
  render: function() {
    var node, nodeViewContext, view, _ref, _ref1, _ref2;
    _ref = this.props, view = _ref.view, node = _ref.node, nodeViewContext = _ref.nodeViewContext;
    return DOM.span({
      ref: 'expressionBox',
      style: {
        display: 'inline-block',
        border: '1px solid lightgray',
        padding: 3,
        margin: 2,
        background: nodeViewContext.isSelected(node) && ((_ref1 = node.type) != null ? _ref1.equals(new UnknownType()) : void 0) ? 'red' : nodeViewContext.isSelected(node) ? 'lightgray' : ((_ref2 = node.type) != null ? _ref2.equals(new UnknownType()) : void 0) ? 'pink' : 'white',
        cursor: nodeViewContext ? 'pointer' : void 0
      },
      onClick: (function(_this) {
        return function(ev) {
          return nodeViewContext.onClick(ev, node);
        };
      })(this)
    }, view);
  },
  componentDidMount: function() {
    var evaluationContext, node, nodeViewContext, value, _ref;
    _ref = this.props, node = _ref.node, nodeViewContext = _ref.nodeViewContext;
    evaluationContext = nodeViewContext.evaluationContext;
    if (evaluationContext) {
      value = node.evaluate(evaluationContext);
      return $(this.refs.expressionBox.getDOMNode()).qtip({
        content: {
          text: JSON.stringify(value)
        },
        position: {
          my: 'bottom center',
          target: 'mouse',
          adjust: {
            y: -10
          }
        },
        style: {
          classes: 'qtip-dark'
        }
      });
    }
  }
});

NodeHarnessView = reactCreateClass('NodeHarnessView', {
  propTypes: {
    initialNode: PT.instanceOf(AbstractNode).isRequired,
    initialEvaluationContext: PT.instanceOf(EvaluationContext).isRequired,
    initialTypingContext: PT.instanceOf(EvaluationContext).isRequired
  },
  getInitialState: function() {
    return {
      node: this.props.initialNode,
      evaluationContext: this.props.initialEvaluationContext,
      typingContext: this.props.initialTypingContext,
      selectedNodePath: void 0
    };
  },
  render: function() {
    var evaluationContext, node, nodeViewContext, selectedNode, selectedNodePath, toolboxNodeViewContext, typedNode, _ref, _ref1;
    _ref = this.state, node = _ref.node, evaluationContext = _ref.evaluationContext, selectedNodePath = _ref.selectedNodePath;
    nodeViewContext = this.getNodeViewContext();
    console.log('nVC', nodeViewContext);
    typedNode = node.applyTypingContext(this.state.typingContext, Immutable.List());
    selectedNode = this.state.selectedNodePath ? typedNode.getIn(this.state.selectedNodePath) : void 0;
    toolboxNodeViewContext = new ToolboxNodeViewContext(true, (function(_this) {
      return function(node) {
        console.log('u selled', node.toJS());
        return _this.replaceSelectedNodeWith(node);
      };
    })(this));
    return DOM.div({}, DOM.div({}, evaluationContext.symbolValues.mapToJS((function(_this) {
      return function(value, symbol) {
        return DOM.div({}, DOM.label({}, symbol + ': ', DOM.input({
          defaultValue: JSON.stringify(value),
          onChange: function(event) {
            var parsed, valid;
            valid = false;
            try {
              parsed = JSON.parse(event.target.value);
              valid = true;
            } catch (_error) {}
            if (valid) {
              return _this.setState({
                evaluationContext: evaluationContext.extend(symbol, parsed)
              });
            }
          }
        })));
      };
    })(this))), NodeView({
      node: typedNode,
      nodeViewContext: nodeViewContext
    }), DOM.div({
      className: 'right-bar'
    }, DOM.div({}, 'Path: ' + ((_ref1 = this.state.selectedNodePath) != null ? _ref1.toString() : void 0)), selectedNode ? [DOM.div({}, 'Type: ' + selectedNode.type.toString()), DOM.div({}, 'TypingContext: ' + selectedNode.typingContext.toString())] : 'No node selected?', DOM.div({}, DOM.div({}, NodeView({
      node: new MinusNode(new MysteryNode(), new MysteryNode()),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, NodeView({
      node: new TupleNode(Immutable.List([new MysteryNode(), new MysteryNode()])),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, NodeView({
      node: new SingletonNode(new MysteryNode()),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, NodeView({
      node: new RangeNode(new MysteryNode(), new MysteryNode()),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, NodeView({
      node: new PickNode(new MysteryNode()),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, NodeView({
      node: new ForEachNode('?', new MysteryNode(), new MysteryNode()),
      nodeViewContext: toolboxNodeViewContext
    })), DOM.div({}, selectedNode != null ? selectedNode.typingContext.getSymbols().mapToJS((function(_this) {
      return function(symbolName) {
        return NodeView({
          node: new SymbolReferenceNode(symbolName),
          nodeViewContext: toolboxNodeViewContext
        });
      };
    })(this)) : void 0))));
  },
  getNodeViewContext: function() {
    var doSelectNode, doSetNodeProperty, evaluationContext, selectedNodePath, _ref;
    _ref = this.state, evaluationContext = _ref.evaluationContext, selectedNodePath = _ref.selectedNodePath;
    doSelectNode = this.doSelectNode, doSetNodeProperty = this.doSetNodeProperty;
    return new EditorNodeViewContext(evaluationContext, doSelectNode, doSetNodeProperty, selectedNodePath);
  },
  doSelectNode: function(node) {
    console.log('selecting', node, 'with', node.path.toString());
    return this.setState({
      selectedNodePath: node.path
    });
  },
  doSetNodeProperty: function(node, property, newValue) {
    var newNode;
    newNode = this.state.node.setIn(node.path.push(property), newValue);
    return this.setState({
      node: newNode
    });
  },
  replaceSelectedNodeWith: function(node) {
    var newNode;
    newNode = this.state.node.setIn(this.state.selectedNodePath, node);
    return this.setState({
      node: newNode
    });
  }
});

testNode = new ForEachNode('x', new SymbolReferenceNode('s'), new ForEachNode('y', new MinusNode(new SymbolReferenceNode('s'), new SingletonNode(new SymbolReferenceNode('x'))), new PickNode(new TupleNode(Immutable.List([new SymbolReferenceNode('x'), new SymbolReferenceNode('y')])))));

window.testNode = testNode;

testEvaluationContext = new EvaluationContext(Immutable.Map({
  s: [1, 2, 3],
  a: 2,
  b: 3
}));

testTypingContext = new TypingContext(Immutable.Map({
  s: new SetType(new AtomType()),
  a: new IntegerType(),
  b: new IntegerType()
}));

console.log('node', testNode.toString());

console.log('eval', JSON.stringify(testNode.evaluate(testEvaluationContext)));

console.log('type', testNode.applyTypingContext(testTypingContext, Immutable.List()).type.toString());

testView = React.render(NodeHarnessView({
  initialNode: testNode,
  initialEvaluationContext: testEvaluationContext,
  initialTypingContext: testTypingContext
}), d3.select('#workspace').node());

NodeListView = reactCreateClass('NodeListView', {
  propTypes: {
    nodeClasses: PT.arrayOf(PT.object).isRequired
  },
  render: function() {
    var nodeClass;
    return DOM.div({}, (function() {
      var _i, _len, _ref, _results;
      _ref = this.props.nodeClasses;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        nodeClass = _ref[_i];
        _results.push(nodeClass({}));
      }
      return _results;
    }).call(this));
  }
});
