// Generated by CoffeeScript 1.7.1
var DOM, EdgeView, GateEditorSvgView, GateEditorView, GateView, Graph, GraphBase, Node, NodeView, ProbeView, cx, editorView, findColorings, flattn, instanceOf, layout, objHash, reactCreateClass, strHash, xtend,
  __slice = [].slice,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DOM = React.DOM;

DOM.foreignObject = React.createFactory('foreignObject');

instanceOf = React.PropTypes.instanceOf;

cx = React.addons.classSet;

xtend = function(base, xtension) {
  return _.defaults(xtension, base);
};

flattn = function(shallow, arrayOfArrays) {
  return _.flatten(arrayOfArrays, shallow);
};

reactCreateClass = function(name, definition) {
  return React.createFactory(React.createClass(xtend(definition, {
    displayName: name,
    viewName: name
  })));
};

strHash = function(str) {
  var chr, hash, i, _i, _ref;
  hash = 0;
  if (str.length === 0) {
    return hash;
  }
  for (i = _i = 0, _ref = str.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    chr = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + chr;
    hash |= 0;
  }
  return hash;
};

objHash = function(obj) {
  return strHash(JSON.stringify(obj));
};

Immutable.Iterable.prototype.invoke = function() {
  var args, method;
  method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return this.map(function(value) {
    return value[method].apply(value, args);
  });
};

Immutable.Iterable.prototype.cursors = function() {
  return this.map((function(_this) {
    return function(value, index) {
      return Immutable.Cursor.from(_this, index);
    };
  })(this));
};

Immutable.Iterable.prototype.mapToJS = function() {
  return this.map.apply(this, arguments).toJS();
};

findColorings = function(numColors, nodes, edges, coloringSoFar) {
  var allowedColors, color, colorIsForbidden, edge, forbidden, i, neighbor, neighborColor, newColoring, uncoloredNode, _i, _len;
  coloringSoFar || (coloringSoFar = {});
  uncoloredNode = _.find(nodes, function(node) {
    return !(node in coloringSoFar);
  });
  if (!uncoloredNode) {
    return [coloringSoFar];
  } else {
    colorIsForbidden = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= numColors ? _i < numColors : _i > numColors; i = 0 <= numColors ? ++_i : --_i) {
        _results.push(false);
      }
      return _results;
    })();
    for (_i = 0, _len = edges.length; _i < _len; _i++) {
      edge = edges[_i];
      neighbor = null;
      if (edge[0] === uncoloredNode) {
        neighbor = edge[1];
      }
      if (edge[1] === uncoloredNode) {
        neighbor = edge[0];
      }
      if (neighbor) {
        neighborColor = coloringSoFar[neighbor];
        if (_.isNumber(neighborColor)) {
          colorIsForbidden[neighborColor] = true;
        }
      }
    }
    allowedColors = (function() {
      var _j, _len1, _results;
      _results = [];
      for (i = _j = 0, _len1 = colorIsForbidden.length; _j < _len1; i = ++_j) {
        forbidden = colorIsForbidden[i];
        if (!forbidden) {
          _results.push(i);
        }
      }
      return _results;
    })();
    return flattn(true, (function() {
      var _j, _len1, _results;
      _results = [];
      for (_j = 0, _len1 = allowedColors.length; _j < _len1; _j++) {
        color = allowedColors[_j];
        newColoring = _.clone(coloringSoFar);
        newColoring[uncoloredNode] = color;
        _results.push(findColorings(numColors, nodes, edges, newColoring));
      }
      return _results;
    })());
  }
};

Node = Immutable.Record({
  id: '',
  x: 0,
  y: 0,
  draggable: false,
  color: void 0
});

GraphBase = Immutable.Record({
  nodes: Immutable.Map(),
  edges: Immutable.List(),
  onUpdate: function() {}
});

Graph = (function(_super) {
  __extends(Graph, _super);

  function Graph(attributes) {
    Graph.__super__.constructor.call(this, attributes);
  }

  Graph.prototype.addNode = function(x, y) {
    var newNode;
    newNode = Graph.makeNewNode(x, y, true);
    return this.onUpdate(this.set('nodes', this.nodes.set(newNode.id, newNode)));
  };

  Graph.prototype.removeNode = function(nodeId) {
    return this.onUpdate(this.set('nodes', this.nodes["delete"](nodeId)));
  };

  Graph.prototype.updateNodePosition = function(nodeId, x, y) {
    return this.onUpdate(this.set('nodes', this.nodes.updateIn([nodeId, 'x'], function() {
      return x;
    }).updateIn([nodeId, 'y'], function() {
      return y;
    })));
  };

  Graph.prototype.addEdge = function(node1, node2) {
    var newEdge, node1Id, node2Id, _ref;
    node1Id = node1.id;
    node2Id = node2.id;
    if (node1Id > node2Id) {
      _ref = [node2Id, node1Id], node1Id = _ref[0], node2Id = _ref[1];
    }
    newEdge = [node1Id, node2Id];
    return this.onUpdate(this.set('edges', this.edges.push(newEdge)));
  };

  Graph.prototype.removeEdge = function(edge) {
    var edgeIndex;
    edgeIndex = this.edges.indexOf(edge);
    console.log('re ei', edgeIndex);
    return this.onUpdate(this.set('edges', this.edges.remove(edgeIndex)));
  };

  Graph.makeNewNode = function(x, y, draggable, color) {
    return new Node({
      id: _.uniqueId('node_'),
      x: x,
      y: y,
      draggable: draggable,
      color: color
    });
  };

  return Graph;

})(GraphBase);

window.Graph = Graph;

GateEditorSvgView = reactCreateClass('GateEditorSvgView', {
  render: function() {
    var canvasHeight, canvasWidth, margin, probeWidth, _ref;
    _ref = this.props.layout, canvasWidth = _ref.canvasWidth, canvasHeight = _ref.canvasHeight, probeWidth = _ref.probeWidth, margin = _ref.margin;
    return DOM.svg({
      width: canvasWidth + probeWidth + 3 * margin,
      height: canvasHeight + 2 * margin
    }, GateEditorView(this.props));
  }
});

GateEditorView = reactCreateClass('GateEditorView', {
  getInitialState: function() {
    return {
      graph: new Graph({
        nodes: this.getInitialNodes(),
        onUpdate: (function(_this) {
          return function(newGraph) {
            return _this.setState({
              graph: newGraph
            });
          };
        })(this)
      }),
      displayColoring: null
    };
  },
  getInitialNodes: function() {
    var canvasHeight, canvasWidth, i, nodeObjects, _ref;
    _ref = this.props.layout, canvasWidth = _ref.canvasWidth, canvasHeight = _ref.canvasHeight;
    nodeObjects = [].concat((function() {
      var _i, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref1 = this.props.numInputNodes; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        _results.push(Graph.makeNewNode((i + 1) * canvasWidth / (this.props.numInputNodes + 1), 0, false));
      }
      return _results;
    }).call(this), (function() {
      var _i, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref1 = this.props.numOutputNodes; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        _results.push(Graph.makeNewNode((i + 1) * canvasWidth / (this.props.numOutputNodes + 1), canvasHeight, false));
      }
      return _results;
    }).call(this), (function() {
      var _i, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref1 = this.props.numColors; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        _results.push(Graph.makeNewNode(canvasWidth, (i + 1) * canvasHeight / (this.props.numColors + 1), false, i));
      }
      return _results;
    }).call(this));
    return Immutable.Map(_.indexBy(nodeObjects, 'id'));
  },
  render: function() {
    var canvasHeight, canvasWidth, margin, _ref;
    _ref = this.props.layout, canvasWidth = _ref.canvasWidth, canvasHeight = _ref.canvasHeight, margin = _ref.margin;
    return DOM.g({}, DOM.g({
      transform: utils.translate(margin, margin)
    }, GateView({
      layout: this.props.layout,
      graph: this.state.graph,
      displayColoring: this.state.displayColoring
    }), DOM.g({
      transform: utils.translate(canvasWidth + margin, 0)
    }, ProbeView({
      layout: this.props.layout,
      graph: this.state.graph,
      setDisplayColoring: (function(_this) {
        return function(displayColoring) {
          return _this.setState({
            displayColoring: displayColoring
          });
        };
      })(this)
    }))));
  }
});

GateView = reactCreateClass('GateView', {
  getInitialState: function() {
    return {
      selectedNodeId: null,
      lastSelectedNodeId: null
    };
  },
  render: function() {
    var canvasHeight, canvasWidth, lastSelectedNode, lastSelectedNodeId, selectedNode, selectedNodeId, _ref, _ref1;
    _ref = this.state, selectedNodeId = _ref.selectedNodeId, lastSelectedNodeId = _ref.lastSelectedNodeId;
    selectedNode = this.props.graph.nodes.get(selectedNodeId);
    lastSelectedNode = this.props.graph.nodes.get(lastSelectedNodeId);
    _ref1 = this.props.layout, canvasWidth = _ref1.canvasWidth, canvasHeight = _ref1.canvasHeight;
    return DOM.g({}, DOM.rect({
      width: canvasWidth,
      height: canvasHeight,
      x: 0,
      y: 0,
      style: {
        fill: 'white',
        stroke: 'black'
      },
      onDoubleClick: this.onDoubleClick
    }), selectedNode && lastSelectedNode ? EdgeView({
      isEdgeMaker: true,
      node1: selectedNode,
      node2: lastSelectedNode,
      onClick: (function(_this) {
        return function() {
          return _this.props.graph.addEdge(selectedNode, lastSelectedNode);
        };
      })(this)
    }) : void 0, this.props.graph.edges.mapToJS((function(_this) {
      return function(edge) {
        return EdgeView({
          key: edge[0] + ' - ' + edge[1],
          isEdgeMaker: false,
          node1: _this.props.graph.nodes.get(edge[0]),
          node2: _this.props.graph.nodes.get(edge[1]),
          onClick: function() {
            return _this.props.graph.removeEdge(edge);
          }
        });
      };
    })(this)), this.renderNodes());
  },
  renderNodes: function() {
    return this.props.graph.nodes.mapToJS((function(_this) {
      return function(node) {
        var _ref;
        return NodeView({
          key: node.id,
          layout: _this.props.layout,
          node: node,
          selected: _this.state.selectedNodeId === node.id,
          displayColor: (_ref = _this.props.displayColoring) != null ? _ref[node.id] : void 0,
          updatePosition: function(x, y) {
            return _this.props.graph.updateNodePosition(node.id, x, y);
          },
          selectNode: function() {
            return _this.selectNode(node);
          }
        });
      };
    })(this));
  },
  selectNode: function(node) {
    var newLastSelectedNodeId;
    newLastSelectedNodeId = this.state.selectedNodeId;
    return this.setState({
      selectedNodeId: node.id,
      lastSelectedNodeId: newLastSelectedNodeId
    });
  },
  onDoubleClick: function(ev) {
    var x, y;
    x = ev.pageX - $(ev.target).offset().left;
    y = ev.pageY - $(ev.target).offset().top;
    return this.props.graph.addNode(x, y, true);
  }
});

NodeView = reactCreateClass('NodeView', {
  propTypes: {
    layout: React.PropTypes.object.isRequired,
    node: React.PropTypes.object.isRequired,
    selected: React.PropTypes.bool,
    updatePosition: React.PropTypes.func,
    selectNode: React.PropTypes.func
  },
  getDefaultProps: function() {
    return {
      selected: false
    };
  },
  render: function() {
    var color, cssColors, displayColor, nodeRad, selected, x, y, _ref, _ref1, _ref2;
    _ref = this.props, selected = _ref.selected, displayColor = _ref.displayColor;
    _ref1 = this.props.node, x = _ref1.x, y = _ref1.y, color = _ref1.color;
    _ref2 = this.props.layout, nodeRad = _ref2.nodeRad, cssColors = _ref2.cssColors;
    return DOM.circle({
      ref: 'node',
      cx: x,
      cy: y,
      r: nodeRad,
      style: {
        fill: !(_.isNumber(displayColor) || _.isNumber(color)) ? 'white' : _.isNumber(displayColor) ? cssColors[displayColor] : cssColors[color],
        stroke: 'black',
        strokeWidth: selected ? 2 : 1
      },
      onClick: this.props.selectNode
    });
  },
  componentDidMount: function() {
    var canvasHeight, canvasWidth, dragBehavior, nodeRad, _ref;
    _ref = this.props.layout, canvasWidth = _ref.canvasWidth, canvasHeight = _ref.canvasHeight, nodeRad = _ref.nodeRad;
    if (this.props.node.draggable) {
      dragBehavior = d3.behavior.drag().origin((function(_this) {
        return function() {
          return _this.props.node;
        };
      })(this)).on("drag", (function(_this) {
        return function() {
          var x, y;
          x = Math.max(nodeRad + 2, Math.min(canvasWidth - nodeRad - 2, d3.event.x));
          y = Math.max(nodeRad + 2, Math.min(canvasHeight - nodeRad - 2, d3.event.y));
          return _this.props.updatePosition(x, y);
        };
      })(this)).on("dragend", (function(_this) {
        return function() {
          return d3.event.sourceEvent.preventDefault();
        };
      })(this));
      return d3.select(this.refs.node.getDOMNode()).call(dragBehavior);
    }
  }
});

EdgeView = reactCreateClass('EdgeView', {
  getInitialState: function() {
    return {
      hovered: false
    };
  },
  render: function() {
    var hovered, isEdgeMaker, node1, node2, onClick, _ref;
    _ref = this.props, node1 = _ref.node1, node2 = _ref.node2, isEdgeMaker = _ref.isEdgeMaker, onClick = _ref.onClick;
    hovered = this.state.hovered;
    return DOM.g({
      onMouseOver: (function(_this) {
        return function() {
          return _this.setState({
            hovered: true
          });
        };
      })(this),
      onMouseOut: (function(_this) {
        return function() {
          return _this.setState({
            hovered: false
          });
        };
      })(this),
      onClick: onClick
    }, DOM.line({
      x1: node1.x,
      y1: node1.y,
      x2: node2.x,
      y2: node2.y,
      style: {
        stroke: 'rgba(0,0,0,0)',
        strokeWidth: 10
      }
    }), DOM.line({
      x1: node1.x,
      y1: node1.y,
      x2: node2.x,
      y2: node2.y,
      style: isEdgeMaker ? {
        stroke: 'lightgray',
        strokeDasharray: !hovered ? '5, 5' : void 0
      } : {
        stroke: 'black',
        strokeWidth: 3,
        strokeDasharray: hovered ? '5, 5' : void 0
      }
    }));
  }
});

ProbeView = reactCreateClass('ProbeView', {
  render: function() {
    var canvasHeight, cellStyle, color, colorings, nodeLayout, nodeRad, probeWidth, row, _ref;
    _ref = this.props.layout, probeWidth = _ref.probeWidth, canvasHeight = _ref.canvasHeight;
    nodeRad = 6;
    nodeLayout = xtend(this.props.layout, {
      nodeRad: nodeRad
    });
    cellStyle = {
      borderLeft: '1px solid black',
      borderRight: '1px solid black'
    };
    return DOM.foreignObject({
      width: probeWidth,
      height: canvasHeight
    }, DOM.table({
      style: {
        borderCollapse: 'collapse'
      }
    }, DOM.thead({}, DOM.th({
      key: 0,
      style: cellStyle
    }, 'In 1'), DOM.th({
      key: 1,
      style: cellStyle
    }, 'In 2'), DOM.th({
      key: 2,
      style: cellStyle
    }, 'Out')), DOM.tbody({}, (function() {
      var _i, _len, _ref1, _results;
      _ref1 = this.getRows();
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        row = _ref1[_i];
        _results.push(DOM.tr({
          key: objHash(row)
        }, DOM.td({
          key: 0,
          style: cellStyle
        }, this.renderLilNode(row[0])), DOM.td({
          key: 1,
          style: cellStyle
        }, this.renderLilNode(row[1])), DOM.td({
          key: 2,
          style: cellStyle
        }, (function() {
          var _j, _len1, _ref2, _ref3, _results1;
          _ref2 = row[2];
          _results1 = [];
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            _ref3 = _ref2[_j], color = _ref3[0], colorings = _ref3[1];
            _results1.push(this.renderLilNode(+color, colorings[0]));
          }
          return _results1;
        }).call(this))));
      }
      return _results;
    }).call(this))));
  },
  renderLilNode: function(color, hoverCovering) {
    var probeNodeRad;
    probeNodeRad = this.props.layout.probeNodeRad;
    return DOM.svg({
      width: probeNodeRad * 2 + 2,
      height: probeNodeRad * 2 + 2,
      onMouseOver: (function(_this) {
        return function() {
          if (hoverCovering) {
            return _this.props.setDisplayColoring(hoverCovering);
          }
        };
      })(this),
      onMouseOut: (function(_this) {
        return function() {
          return _this.props.setDisplayColoring(null);
        };
      })(this)
    }, NodeView({
      layout: xtend(this.props.layout, {
        nodeRad: probeNodeRad
      }),
      node: {
        x: probeNodeRad + 1,
        y: probeNodeRad + 1,
        color: color
      }
    }));
  },
  getRows: function() {
    var coloringSoFar, colorings, edges, in1, in2, nodeIds, nodes, outColors, _i, _len, _ref, _ref1, _ref2, _results;
    _ref = [[0, 0], [0, 1], [1, 0], [1, 1]];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], in1 = _ref1[0], in2 = _ref1[1];
      _ref2 = this.props.graph, nodes = _ref2.nodes, edges = _ref2.edges;
      nodeIds = nodes.invoke('get', 'id').toJS();
      coloringSoFar = {};
      nodes.forEach((function(_this) {
        return function(node) {
          if (_.isNumber(node.color)) {
            return coloringSoFar[node.id] = node.color;
          }
        };
      })(this));
      coloringSoFar['node_1'] = in1;
      coloringSoFar['node_2'] = in2;
      colorings = findColorings(3, nodeIds, edges.toJS(), coloringSoFar);
      outColors = _.pairs(_.groupBy(colorings, _.property('node_3')));
      _results.push([in1, in2, outColors]);
    }
    return _results;
  }
});

layout = {
  canvasWidth: 400,
  canvasHeight: 300,
  probeWidth: 300,
  margin: 40,
  nodeRad: 10,
  probeNodeRad: 8,
  cssColors: ['red', 'blue', 'green']
};

editorView = React.render(GateEditorSvgView({
  layout: layout,
  numInputNodes: 2,
  numOutputNodes: 1,
  numColors: 3
}), d3.select('#gate-editor').node());
