// Generated by CoffeeScript 1.7.1
var R, desugarPropType, key, value, _ref,
  __hasProp = {}.hasOwnProperty;

window.R = R = {};

_ref = React.DOM;
for (key in _ref) {
  if (!__hasProp.call(_ref, key)) continue;
  value = _ref[key];
  R[key] = value;
}

R.cx = React.addons.classSet;

R.UniversalMixin = {
  ownerView: function() {
    var _ref1;
    return (_ref1 = this._owner) != null ? _ref1 : this.props.__owner__;
  },
  lookup: function(keyName) {
    var _ref1, _ref2;
    return (_ref1 = this[keyName]) != null ? _ref1 : (_ref2 = this.ownerView()) != null ? _ref2.lookup(keyName) : void 0;
  },
  lookupView: function(viewName) {
    var _ref1;
    if (this === viewName || this.viewName() === viewName) {
      return this;
    }
    return (_ref1 = this.ownerView()) != null ? _ref1.lookupView(viewName) : void 0;
  },
  lookupViewWithKey: function(keyName) {
    var _ref1;
    if (this[keyName] != null) {
      return this;
    }
    return (_ref1 = this.ownerView()) != null ? _ref1.lookupViewWithKey(keyName) : void 0;
  },
  setPropsOnSelf: function(nextProps) {
    var propName, propValue, _results;
    _results = [];
    for (propName in nextProps) {
      if (!__hasProp.call(nextProps, propName)) continue;
      propValue = nextProps[propName];
      if (propName === "__owner__") {
        continue;
      }
      _results.push(this[propName] = propValue);
    }
    return _results;
  },
  componentWillMount: function() {
    return this.setPropsOnSelf(this.props);
  },
  componentWillUpdate: function(nextProps) {
    return this.setPropsOnSelf(nextProps);
  },
  componentDidMount: function() {
    var el;
    el = this.getDOMNode();
    return el.dataFor != null ? el.dataFor : el.dataFor = this;
  },
  componentWillUnmount: function() {
    var el;
    el = this.getDOMNode();
    return delete el.dataFor;
  }
};

desugarPropType = function(propType, optional) {
  var required;
  if (optional == null) {
    optional = false;
  }
  if (propType.optional) {
    propType = propType.optional;
    required = false;
  } else if (optional) {
    required = false;
  } else {
    required = true;
  }
  if (propType === Number) {
    propType = React.PropTypes.number;
  } else if (propType === String) {
    propType = React.PropTypes.string;
  } else if (propType === Boolean) {
    propType = React.PropTypes.bool;
  } else if (propType === Function) {
    propType = React.PropTypes.func;
  } else if (propType === Array) {
    propType = React.PropTypes.array;
  } else if (propType === Object) {
    propType = React.PropTypes.object;
  } else if (_.isArray(propType)) {
    propType = React.PropTypes.any;
  } else {
    propType = React.PropTypes.instanceOf(propType);
  }
  if (required) {
    propType = propType.isRequired;
  }
  return propType;
};

R.create = function(name, opts) {
  var propName, propType, _ref1;
  opts.displayName = name;
  opts.viewName = function() {
    return name;
  };
  if (opts.propTypes == null) {
    opts.propTypes = {};
  }
  _ref1 = opts.propTypes;
  for (propName in _ref1) {
    if (!__hasProp.call(_ref1, propName)) continue;
    propType = _ref1[propName];
    opts.propTypes[propName] = desugarPropType(propType);
  }
  if (opts.mixins == null) {
    opts.mixins = [];
  }
  opts.mixins.unshift(R.UniversalMixin);
  return R[name] = React.createClass(opts);
};

require("./ui/TextFieldView");

require("./AppRootView");

require("./ShaderOverlayView");

require("./PaletteView");

require("./PlotLayoutView");

require("./ThumbnailPlotLayoutView");

require("./OutlineView");

require("./InspectorView");

require("./VariableView");

require("./SymbolicView");

require("./plot/GridView");

require("./plot/ShaderCartesianView");
