// Generated by CoffeeScript 1.7.1
var Event, Schedule, ScheduleGrid, events, schedule, scheduleGrid, scheduleGridG, svg;

Event = (function() {
  function Event(start, end) {
    this.start = start;
    this.end = end;
  }

  Event.prototype.intersection = function(otherEvent) {
    var earlierEnd, laterStart;
    laterStart = Math.max(start, otherEvent.start);
    earlierEnd = Math.min(end, otherEvent.end);
    if (laterStart < earlierEnd) {
      return [laterStart, earlierEnd];
    } else {
      return null;
    }
  };

  Event.prototype.intersects = function(otherEvent) {
    return !!this.intersection(otherEvent);
  };

  return Event;

})();

Schedule = (function() {
  function Schedule(events) {
    this.events = events;
    this.coloring = _.range(this.events.length);
  }

  Schedule.prototype.colors = function() {
    return _.uniq(this.coloring);
  };

  Schedule.prototype.colorIndexAt = function(i) {
    return this.colors().indexOf(this.coloring[i]);
  };

  return Schedule;

})();

ScheduleGrid = (function() {
  function ScheduleGrid(elem, schedule, _arg) {
    this.elem = elem;
    this.schedule = schedule;
    this.start = _arg.start, this.end = _arg.end, this.width = _arg.width;
  }

  ScheduleGrid.prototype.render = function() {
    var axis, axisG, barDragger, barHeight, barRadius, bars, barsEnterG, rowHeight, rows, rowsContainer, rowsEnterG, scale;
    rowHeight = 25;
    barHeight = 15;
    barRadius = barHeight / 2;
    scale = d3.scale.linear().domain([this.start, this.end]).range([0, this.width]);
    axis = d3.svg.axis().scale(scale).orient('top').tickFormat(d3.format('0d'));
    axisG = this.elem.append('g').classed('axis', true).call(axis);
    barDragger = d3.behavior.drag().on('dragstart', (function(_this) {
      return function(d, i) {
        barDragger.currentBarIndex = i;
        barDragger.currentRow = null;
        return console.log('dragstart', _this, d3.event);
      };
    })(this)).on('drag', (function(_this) {
      return function() {
        return 3;
      };
    })(this)).on('dragend', (function(_this) {
      return function() {
        console.log('dragend', _this, d3.event, barDragger.currentBarIndex, barDragger.currentRow);
        _this.schedule.coloring[barDragger.currentBarIndex] = barDragger.currentRow;
        return _this.render();
      };
    })(this));
    rowsContainer = this.elem.selectAll('.rows').data([2]);
    rowsContainer.enter().append('g').classed('rows', true);
    console.log('colors', this.schedule.colors());
    rows = rowsContainer.selectAll('.row').data(this.schedule.colors());
    rowsEnterG = rows.enter().append('g').classed('row', true).attr({
      transform: (function(_this) {
        return function(d, i) {
          return utils.translate(0, rowHeight * _this.schedule.coloring[i]);
        };
      })(this)
    });
    rowsEnterG.append('rect').classed('background', true).attr({
      x: 0,
      y: 0,
      width: this.width,
      height: rowHeight
    }).on('mouseover', function(d, i) {
      console.log('mouseover', d, i);
      return barDragger.currentRow = d;
    });
    rowsEnterG.append('line').classed('divider', true).attr({
      x1: 0,
      x2: this.width,
      y1: rowHeight,
      y2: rowHeight
    });
    rowsEnterG.append('text').classed('label', true).attr({
      x: -60,
      y: function(d, i) {
        return rowHeight * 0.5;
      }
    }).style({
      'alignment-baseline': 'central'
    }).text(function(d, i) {
      return "Room " + (i + 1);
    });
    rows.exit().remove();
    bars = this.elem.selectAll('.bar').data(this.schedule.events);
    barsEnterG = bars.enter().append('g').classed('bar', true);
    barsEnterG.append('path').attr({
      d: function(d, i) {
        return ['M', 0, 0, 'h', scale(d.end) - scale(d.start) - 2 * barRadius, 'a', barRadius, barRadius, 180, 0, 1, 0, barHeight, 'h', -(scale(d.end) - scale(d.start) - 2 * barRadius), 'a', barRadius, barRadius, 180, 0, 1, 0, -barHeight].join(' ');
      }
    }).call(barDragger);
    barsEnterG.append('text').text(function(d, i) {
      return i;
    });
    return bars.attr({
      transform: (function(_this) {
        return function(d, i) {
          return utils.translate(scale(d.start) + barRadius, rowHeight * _this.schedule.colorIndexAt(i) + (rowHeight - barHeight) / 2);
        };
      })(this)
    });
  };

  return ScheduleGrid;

})();

events = _.map([[0.5, 3.5], [1, 2], [2.5, 4.5], [3, 5.5], [4, 6]], function(x) {
  return (function(func, args, ctor) {
    ctor.prototype = func.prototype;
    var child = new ctor, result = func.apply(child, args);
    return Object(result) === result ? result : child;
  })(Event, x, function(){});
});

schedule = new Schedule(events);

svg = d3.select('.schedule-grid');

scheduleGridG = svg.append('g').attr({
  transform: utils.translate(100, 30)
});

scheduleGrid = new ScheduleGrid(scheduleGridG, schedule, {
  start: 0,
  end: 7,
  width: 300
});

scheduleGrid.render();
