// Generated by CoffeeScript 1.7.1
var BarView, DOM, DragArrowView, Event, RowView, RowWithBars, RowsView, ScheduleGridAxisView, ScheduleGridSvgView, ScheduleGridView, baseLayout, cx, events, i, instanceOf, names, propTypeLayout, reactCreateClass, scheduleGridSvgView, times,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __slice = [].slice;

DOM = React.DOM;

instanceOf = React.PropTypes.instanceOf;

cx = React.addons.classSet;

reactCreateClass = utils.reactCreateClass;

Event = (function() {
  function Event(id, start, end, name, status) {
    this.id = id;
    this.start = start;
    this.end = end;
    this.name = name;
    this.status = status != null ? status : 'REAL';
  }

  Event.prototype.intersection = function(otherEvent) {
    var earlierEnd, laterStart;
    laterStart = Math.max(this.start, otherEvent.start);
    earlierEnd = Math.min(this.end, otherEvent.end);
    if (laterStart < earlierEnd) {
      return [laterStart, earlierEnd];
    } else {
      return null;
    }
  };

  Event.prototype.intersects = function(otherEvent) {
    return !!this.intersection(otherEvent);
  };

  return Event;

})();

propTypeLayout = React.PropTypes.shape({
  rowWidth: React.PropTypes.number.isRequired,
  rowHeight: React.PropTypes.number.isRequired,
  barHeight: React.PropTypes.number.isRequired
});

RowWithBars = (function() {
  function RowWithBars(color, bars) {
    this.color = color;
    this.bars = bars;
  }

  return RowWithBars;

})();

BarView = reactCreateClass('BarView', {
  propTypes: {
    layout: propTypeLayout.isRequired,
    horizontalScale: React.PropTypes.func.isRequired,
    bar: instanceOf(Event),
    startBarDrag: React.PropTypes.func.isRequired,
    endBarDrag: React.PropTypes.func.isRequired
  },
  render: function() {
    var bar, barHeight, draggableBars, horRadius, innerWidth, outerWidth, rowHeight, scale, verRadius, _ref;
    bar = this.props.bar;
    scale = this.props.horizontalScale;
    _ref = this.props.layout, rowHeight = _ref.rowHeight, barHeight = _ref.barHeight, draggableBars = _ref.draggableBars;
    verRadius = barHeight / 2;
    outerWidth = scale(bar.end) - scale(bar.start);
    innerWidth = Math.max(0, outerWidth - 2 * verRadius);
    horRadius = (outerWidth - innerWidth) / 2;
    return DOM.g({
      className: cx({
        'bar': true,
        'drag-source': this.props.bar.status === 'REAL-DRAG-SOURCE',
        'fake-ok': this.props.bar.status === 'FAKE-OK',
        'fake-not-ok': this.props.bar.status === 'FAKE-NOT-OK',
        'draggable': draggableBars
      })
    }, DOM.path({
      ref: 'path',
      transform: utils.translate(scale(bar.start) + horRadius, (rowHeight - barHeight) / 2),
      d: ['M', 0, 0, 'h', innerWidth, 'a', horRadius, verRadius, 180, 0, 1, 0, barHeight, 'h', -innerWidth, 'a', horRadius, verRadius, 180, 0, 1, 0, -barHeight].join(' ')
    }), this.props.layout.shouldLabelBars ? DOM.text({
      x: scale(bar.end) + this.props.layout.barLabelPadding,
      y: this.props.layout.rowHeight * 0.5,
      style: {
        alignmentBaseline: 'central',
        fontStyle: 'italic',
        fontSize: '70%'
      }
    }, bar.name) : void 0);
  },
  componentDidMount: function() {
    var dragBehavior;
    if (this.props.layout.draggableBars) {
      dragBehavior = d3.behavior.drag().on('dragstart', (function(_this) {
        return function() {
          return _this.props.startBarDrag(_this.props.bar);
        };
      })(this)).on('dragend', (function(_this) {
        return function() {
          return _this.props.endBarDrag(_this.props.bar);
        };
      })(this));
      return d3.select(this.refs.path.getDOMNode()).call(dragBehavior);
    }
  }
});

RowView = reactCreateClass('RowView', {
  propTypes: {
    layout: propTypeLayout.isRequired,
    rowWithBars: React.PropTypes.instanceOf(RowWithBars).isRequired,
    index: React.PropTypes.number.isRequired,
    hoverRow: React.PropTypes.func.isRequired,
    startBarDrag: React.PropTypes.func.isRequired,
    endBarDrag: React.PropTypes.func.isRequired
  },
  render: function() {
    var bar, bars;
    bars = this.getBars();
    return DOM.g({
      className: 'row',
      onMouseEnter: (function(_this) {
        return function() {
          return _this.props.hoverRow(_this.props.rowWithBars.color, true);
        };
      })(this),
      onMouseLeave: (function(_this) {
        return function() {
          return _this.props.hoverRow(_this.props.rowWithBars.color, false);
        };
      })(this)
    }, DOM.rect({
      className: 'background',
      x: 0,
      y: 0,
      width: this.props.layout.rowWidth,
      height: this.props.layout.rowHeight
    }), this.props.layout.draggableBars ? DOM.line({
      className: 'divider',
      x1: 0,
      y1: this.props.layout.rowHeight,
      x2: this.props.layout.rowWidth,
      y2: this.props.layout.rowHeight
    }) : void 0, this.props.layout.shouldLabelRows ? DOM.text({
      x: -this.props.layout.rowLabelOffset,
      y: this.props.layout.rowHeight * 0.5,
      style: {
        alignmentBaseline: 'central'
      }
    }, 'Team ' + (this.props.index + 1)) : void 0, (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = bars.length; _i < _len; _i++) {
        bar = bars[_i];
        _results.push(BarView({
          key: 'baris:' + bar.id,
          layout: this.props.layout,
          horizontalScale: this.props.horizontalScale,
          bar: bar,
          startBarDrag: (function(_this) {
            return function(bar) {
              return _this.props.startBarDrag(bar, _this.props.index);
            };
          })(this),
          endBarDrag: this.props.endBarDrag
        }));
      }
      return _results;
    }).call(this));
  },
  getBars: function() {
    var bars, draggedBar, ok;
    bars = this.props.rowWithBars.bars.slice();
    draggedBar = this.props.draggedBar;
    if ((draggedBar != null) && this.props.hoveredRow === this.props.rowWithBars.color) {
      if (__indexOf.call(bars, draggedBar) < 0) {
        ok = _.all(bars, function(bar) {
          return !bar.intersects(draggedBar);
        });
        bars.push(new Event(_.uniqueId('fake'), draggedBar.start, draggedBar.end, draggedBar.name, ok ? 'FAKE-OK' : 'FAKE-NOT-OK'));
      }
    }
    if ((draggedBar != null) && (__indexOf.call(bars, draggedBar) >= 0)) {
      bars.push(new Event(_.uniqueId('real'), draggedBar.start, draggedBar.end, draggedBar.name, 'REAL-DRAG-SOURCE'));
    }
    return bars;
  }
});

RowsView = reactCreateClass('RowsView', {
  propTypes: {
    rowsWithBars: React.PropTypes.arrayOf(instanceOf(RowWithBars)).isRequired,
    layout: propTypeLayout.isRequired,
    hoverRow: React.PropTypes.func.isRequired,
    startBarDrag: React.PropTypes.func.isRequired,
    endBarDrag: React.PropTypes.func.isRequired
  },
  render: function() {
    var i, rowWithBars;
    return DOM.g({
      className: 'rows'
    }, (function() {
      var _i, _len, _ref, _results;
      _ref = this.props.rowsWithBars;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        rowWithBars = _ref[i];
        _results.push(DOM.g({
          key: 'row:' + rowWithBars.color,
          transform: utils.translate(0, this.props.layout.rowHeight * i)
        }, RowView({
          layout: this.props.layout,
          rowWithBars: rowWithBars,
          index: i,
          horizontalScale: this.props.horizontalScale,
          hoveredRow: this.props.hoveredRow,
          draggedBar: this.props.draggedBar,
          hoverRow: this.props.hoverRow,
          startBarDrag: this.props.startBarDrag,
          endBarDrag: this.props.endBarDrag
        })));
      }
      return _results;
    }).call(this));
  }
});

ScheduleGridAxisView = reactCreateClass('ScheduleGridAxisView', {
  propTypes: {
    horizontalScale: React.PropTypes.func.isRequired
  },
  render: function() {
    return DOM.g({
      ref: 'g',
      className: 'axis'
    });
  },
  componentDidMount: function() {
    var axis;
    axis = d3.svg.axis().scale(this.props.horizontalScale).orient('top').tickFormat(function(x) {
      if (x % 3 === 0) {
        return ((x - 1) % 12 + 1) + (x < 12 ? 'AM' : 'PM');
      }
    });
    return d3.select(this.refs.g.getDOMNode()).call(axis);
  }
});

DragArrowView = reactCreateClass('DragArrowView', {
  render: function() {
    return DOM.g({});
  }
});

ScheduleGridView = reactCreateClass('ScheduleGridView', {
  propTypes: {
    layout: propTypeLayout.isRequired,
    startTime: React.PropTypes.number.isRequired,
    endTime: React.PropTypes.number.isRequired,
    events: React.PropTypes.arrayOf(instanceOf(Event)).isRequired,
    initialColoring: React.PropTypes.arrayOf(React.PropTypes.number)
  },
  getInitialState: function() {
    var _ref;
    return {
      coloring: (_ref = this.props.initialColoring) != null ? _ref : _.range(events.length),
      hoveredRow: null,
      draggedBar: null
    };
  },
  render: function() {
    var dragFromRowIndex, dragToRowIndex, horizontalScale;
    this.rowsWithBars = this.getRowsWithBars();
    horizontalScale = this.getHorizontalScale();
    if (this.state.draggedBar) {
      dragFromRowIndex = this.state.dragFromRowIndex;
      dragToRowIndex = this.rowsWithBars.indexOf(_.findWhere(this.rowsWithBars, {
        color: this.state.hoveredRow
      }));
    }
    return DOM.g({}, ScheduleGridAxisView({
      horizontalScale: horizontalScale
    }), RowsView({
      layout: this.props.layout,
      rowsWithBars: this.rowsWithBars,
      horizontalScale: horizontalScale,
      hoveredRow: this.state.hoveredRow,
      draggedBar: this.state.draggedBar,
      hoverRow: this.hoverRow,
      startBarDrag: this.startBarDrag,
      endBarDrag: this.endBarDrag
    }), this.state.draggedBar ? DragArrowView({
      layout: this.props.layout,
      dragFromRowIndex: dragFromRowIndex,
      dragToRowIndex: dragToRowIndex
    }) : void 0);
  },
  componentDidMount: function() {
    return this.props.setNumRows(this.getRowsWithBars().length);
  },
  componentDidUpdate: function() {
    return this.props.setNumRows(this.getRowsWithBars().length);
  },
  getColorsUsed: function() {
    return _.uniq(this.state.coloring);
  },
  getRowsWithBars: function() {
    var colorsUsed, largestColorUsed, rowsWithBars;
    rowsWithBars = _.chain(_.zip(this.props.events, this.state.coloring)).groupBy(_.property(1)).map(function(groupOfPairs, color) {
      return new RowWithBars(Number(color), _.pluck(groupOfPairs, 0));
    }).value();
    if (this.state.draggedBar) {
      colorsUsed = _.sortBy(this.getColorsUsed());
      largestColorUsed = colorsUsed[colorsUsed.length - 1];
      rowsWithBars.push(new RowWithBars(largestColorUsed + 1, []));
    }
    return rowsWithBars;
  },
  getHorizontalScale: function() {
    return d3.scale.linear().domain([this.props.startTime, this.props.endTime]).range([0, this.props.layout.rowWidth]);
  },
  hoverRow: function(row, status) {
    if (this.state.hoveredRow === row && status === false) {
      return this.setState({
        hoveredRow: null
      });
    } else if (status === true) {
      return this.setState({
        hoveredRow: row
      });
    }
  },
  startBarDrag: function(bar, rowIndex) {
    return this.setState({
      draggedBar: bar,
      dragFromRowIndex: rowIndex
    });
  },
  endBarDrag: function(bar) {
    var draggedBar, index, newColoring, ok;
    draggedBar = this.state.draggedBar;
    if ((draggedBar != null) && (this.state.hoveredRow != null)) {
      ok = _.chain(_.zip(this.props.events, this.state.coloring)).where({
        1: this.state.hoveredRow
      }).all((function(_this) {
        return function(barPair) {
          return !barPair[0].intersects(draggedBar);
        };
      })(this)).value();
      if (ok) {
        index = this.props.events.indexOf(bar);
        newColoring = this.state.coloring.slice();
        newColoring[index] = this.state.hoveredRow;
        this.setState({
          draggedBar: null,
          coloring: newColoring
        });
      }
    }
    return this.setState({
      draggedBar: null
    });
  }
});

ScheduleGridSvgView = reactCreateClass('ScheduleGridSvgView', {
  getInitialState: function() {
    return {
      numRows: this.props.events.length,
      numRowsForHeight: this.props.events.length
    };
  },
  render: function() {
    var marginLeft, marginRight, marginTop, rowHeight, rowWidth, _ref;
    _ref = this.props.layout, marginTop = _ref.marginTop, marginLeft = _ref.marginLeft, marginRight = _ref.marginRight, rowHeight = _ref.rowHeight, rowWidth = _ref.rowWidth;
    return DOM.svg({
      width: marginLeft + rowWidth + marginRight,
      height: marginTop + rowHeight * this.state.numRowsForHeight + 1
    }, DOM.g({
      transform: utils.translate(marginLeft, marginTop)
    }, ScheduleGridView(_.extend({}, this.props, {
      setNumRows: this.setNumRows
    }))));
  },
  setNumRows: function(numRows) {
    if (this.state.numRows !== numRows) {
      return this.setState({
        numRows: numRows
      });
    }
  }
});

names = ["Goth Brunch", "Generic Corporate Shindig", "Power Ultrarave", "Fun With Roadflares", "Benefit Dinner For The Navigationally Inept", "Power Brunch", "Power Luncheon", "Explorable Explanations Hackathon", "Speed-Dating 4 Cats", "Pre-Natal Haircuts"];

times = [[9.5, 12], [15, 17], [12.5, 21], [18, 21], [18, 19.5], [10, 11], [11.5, 13], [10, 17], [16, 18.5], [11.5, 13.5]];

events = _.sortBy((function() {
  var _i, _len, _ref, _results;
  _ref = _.range(10);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    _results.push((function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return Object(result) === result ? result : child;
    })(Event, [i].concat(__slice.call(times[i]), [names[i]]), function(){}));
  }
  return _results;
})(), function(event) {
  return event.start;
});

baseLayout = {
  rowWidth: 450,
  marginTop: 30,
  marginRight: 200,
  rowHeight: 25,
  barHeight: 15,
  barLabelPadding: 10,
  rowLabelOffset: 80
};

React.render(ScheduleGridSvgView({
  layout: _.extend({}, baseLayout, {
    marginLeft: 30,
    shouldLabelBars: true
  }),
  events: events,
  coloring: _.range(events.length),
  startTime: 9,
  endTime: 21
}), d3.select('#caterer-events').node());

scheduleGridSvgView = React.render(ScheduleGridSvgView({
  layout: _.extend({}, baseLayout, {
    marginLeft: 100,
    shouldLabelRows: true,
    draggableBars: true
  }),
  events: events,
  coloring: _.range(events.length),
  startTime: 9,
  endTime: 21
}), d3.select('#caterer-dragging').node());

d3.select('#caterer-done').on('click', function() {
  console.log('done');
  return d3.select('#caterer-done-msg').html("Nice! You got it down to " + scheduleGridSvgView.state.numRows + " teams. Do you think it's possible to do better than that? Give that some thought, and then move on to the probably-totally-unrelated game called&hellip;");
});
