// Generated by CoffeeScript 1.7.1
var utils,
  __slice = [].slice;

utils = {
  translate: function(x, y) {
    return "translate(" + x + "," + y + ") ";
  },
  scale: function(s) {
    return "scale(" + s + ") ";
  },
  scaleAround: function(s, x, y) {
    return utils.translate(x, y) + utils.scale(s) + utils.translate(-x, -y);
  },
  xtend: function(base, xtension) {
    return _.defaults(xtension, base);
  },
  NoExtraPropsMixin: {
    componentWillMount: function() {
      return this.checkForExtraProps();
    },
    componentWillReceiveProps: function() {
      return this.checkForExtraProps();
    },
    checkForExtraProps: function() {
      var propName, propTypes, _results;
      propTypes = this.propTypesCopy || {};
      _results = [];
      for (propName in this.props) {
        if (!propTypes[propName]) {
          _results.push(console.warn("Unknown prop passed to " + this.viewName + ": " + propName));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  },
  reactCreateClass: function(name, definition) {
    return React.createFactory(React.createClass(utils.xtend(definition, {
      displayName: name,
      viewName: name,
      propTypesCopy: definition.propTypes,
      mixins: [React.addons.PureRenderMixin, utils.NoExtraPropsMixin],
      propTypesCopy: definition.propTypes
    })));
  },
  strHash: function(str) {
    var chr, hash, i, _i, _ref;
    hash = 0;
    if (str.length === 0) {
      return hash;
    }
    for (i = _i = 0, _ref = str.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      chr = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + chr;
      hash |= 0;
    }
    return hash;
  },
  objHash: function(obj) {
    return utils.strHash(JSON.stringify(obj));
  },
  ImmutableRecordExtending: function(base, defaultValuesToAdd) {
    var newCtor, newDefaultValues, oldCtor;
    newDefaultValues = _.extend({}, base.prototype._defaultValues, defaultValuesToAdd);
    oldCtor = Immutable.Record(newDefaultValues);
    newCtor = function() {
      newDefaultValues.ctor.apply(this, arguments);
    };
    newCtor.prototype = oldCtor.prototype;
    newCtor.prototype["super"] = oldCtor;
    newCtor.prototype.__proto__ = base.prototype;
    newCtor.prototype.constructor = newCtor;
    return newCtor;
  },
  ImmutableRecordFromKeys: function(keys) {
    return Immutable.Record(_.object(keys, []));
  }
};

Immutable.Iterable.prototype.mapToJS = function() {
  return this.map.apply(this, arguments).toJS();
};

Immutable.Iterable.prototype.invoke = function() {
  var args, method;
  method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return this.map(function(value) {
    return value[method].apply(value, args);
  });
};

Immutable.Iterable.prototype.pluck = function(propName) {
  return this.map(function(value) {
    return value[propName];
  });
};

window.utils = utils;
