// Generated by CoffeeScript 1.6.3
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function() {
  var AdderConstraint, Connector, ConstantConstraint, EqualityConstraint, MultiplierConstraint, PairerConstraint, ProbePseudoconstraint, WatcherPseudoconstraint, constantConnector, dividedSegmentConstraint, equal, partwaysConstraint, probedConnector;
  equal = function(a, b) {
    if (a instanceof Array) {
      return (b instanceof Array) && (a.length === b.length) && a.every(function(elem, i) {
        return elem === b[i];
      });
    } else {
      return a === b;
    }
  };
  Connector = (function() {
    function Connector(name) {
      this.name = name;
      this.value = false;
      this.informant = false;
      this.constraints = [];
    }

    Connector.prototype.hasValue = function() {
      return this.informant !== false;
    };

    Connector.prototype.getValue = function() {
      return this.value;
    };

    Connector.prototype.setValue = function(value, informant) {
      var constraint, _i, _len, _ref, _results;
      if (!this.hasValue()) {
        this.value = value;
        this.informant = informant;
        _ref = this.constraints;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          constraint = _ref[_i];
          if (constraint !== informant) {
            _results.push(constraint.processNewValue());
          }
        }
        return _results;
      } else if (!equal(value, this.value)) {
        throw new Error("inconsistency in connector " + this.name);
      }
    };

    Connector.prototype.forgetValue = function(retractor) {
      var constraint, _i, _len, _ref, _results;
      if (retractor === this.informant) {
        this.informant = false;
        _ref = this.constraints;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          constraint = _ref[_i];
          if (constraint !== retractor) {
            _results.push(constraint.processForgetValue());
          }
        }
        return _results;
      }
    };

    Connector.prototype.connect = function(constraint) {
      if (!(__indexOf.call(this.constraints, constraint) >= 0)) {
        if (!constraint.processNewValue) {
          throw new Error();
        }
        this.constraints.push(constraint);
      }
      if (this.hasValue()) {
        return constraint.processNewValue();
      }
    };

    return Connector;

  })();
  WatcherPseudoconstraint = (function() {
    function WatcherPseudoconstraint(connector, onNew, onForget) {
      this.connector = connector;
      this.onNew = onNew;
      this.onForget = onForget;
      this.connector.connect(this);
    }

    WatcherPseudoconstraint.prototype.processNewValue = function() {
      if (this.onNew) {
        return this.onNew(this.connector.getValue());
      }
    };

    WatcherPseudoconstraint.prototype.processForgetValue = function() {
      if (this.onForget) {
        return this.onForget();
      }
    };

    return WatcherPseudoconstraint;

  })();
  ProbePseudoconstraint = (function(_super) {
    __extends(ProbePseudoconstraint, _super);

    function ProbePseudoconstraint(connector, label) {
      this.connector = connector;
      this.label = label;
      ProbePseudoconstraint.__super__.constructor.call(this, this.connector, function(value) {
        return console.log("PROBE: " + this.label + " = " + value);
      }, function() {
        return console.log("PROBE: " + this.label + " = ?");
      });
    }

    return ProbePseudoconstraint;

  })(WatcherPseudoconstraint);
  ConstantConstraint = (function() {
    function ConstantConstraint(connector, value) {
      this.connector = connector;
      this.value = value;
      this.connector.connect(this);
      this.connector.setValue(this.value, this);
    }

    ConstantConstraint.prototype.processNewValue = function() {
      throw new Exception();
    };

    ConstantConstraint.prototype.processForgetValue = function() {
      throw new Exception();
    };

    return ConstantConstraint;

  })();
  EqualityConstraint = (function() {
    function EqualityConstraint(e1, e2) {
      this.e1 = e1;
      this.e2 = e2;
      this.e1.connect(this);
      this.e2.connect(this);
    }

    EqualityConstraint.prototype.processNewValue = function() {
      if (this.e1.hasValue()) {
        return this.e2.setValue(this.e1.getValue(), this);
      } else if (this.e2.hasValue()) {
        return this.e1.setValue(this.e2.getValue(), this);
      }
    };

    EqualityConstraint.prototype.processForgetValue = function() {
      this.e1.forgetValue(this);
      return this.e2.forgetValue(this);
    };

    return EqualityConstraint;

  })();
  AdderConstraint = (function() {
    function AdderConstraint(a1, a2, sum) {
      this.a1 = a1;
      this.a2 = a2;
      this.sum = sum;
      this.a1.connect(this);
      this.a2.connect(this);
      this.sum.connect(this);
    }

    AdderConstraint.prototype.processNewValue = function() {
      if (this.a1.hasValue() && this.a2.hasValue()) {
        return this.sum.setValue(this.a1.getValue() + this.a2.getValue(), this);
      } else if (this.a1.hasValue() && this.sum.hasValue()) {
        return this.a2.setValue(this.sum.getValue() - this.a1.getValue(), this);
      } else if (this.a2.hasValue() && this.sum.hasValue()) {
        return this.a1.setValue(this.sum.getValue() - this.a2.getValue(), this);
      }
    };

    AdderConstraint.prototype.processForgetValue = function() {
      this.a1.forgetValue(this);
      this.a2.forgetValue(this);
      return this.sum.forgetValue(this);
    };

    return AdderConstraint;

  })();
  MultiplierConstraint = (function() {
    function MultiplierConstraint(m1, m2, product) {
      this.m1 = m1;
      this.m2 = m2;
      this.product = product;
      this.m1.connect(this);
      this.m2.connect(this);
      this.product.connect(this);
    }

    MultiplierConstraint.prototype.processNewValue = function() {
      if (this.m1.hasValue() && this.m2.hasValue()) {
        return this.product.setValue(this.m1.getValue() * this.m2.getValue(), this);
      } else if (this.m1.hasValue() && this.product.hasValue()) {
        return this.m2.setValue(this.product.getValue() / this.m1.getValue(), this);
      } else if (this.m2.hasValue() && this.product.hasValue()) {
        return this.m1.setValue(this.product.getValue() / this.m2.getValue(), this);
      }
    };

    MultiplierConstraint.prototype.processForgetValue = function() {
      this.m1.forgetValue(this);
      this.m2.forgetValue(this);
      return this.product.forgetValue(this);
    };

    return MultiplierConstraint;

  })();
  PairerConstraint = (function() {
    function PairerConstraint(e1, e2, pair) {
      this.e1 = e1;
      this.e2 = e2;
      this.pair = pair;
      this.e1.connect(this);
      this.e2.connect(this);
      this.pair.connect(this);
    }

    PairerConstraint.prototype.processNewValue = function() {
      if (this.e1.hasValue() && this.e2.hasValue()) {
        return this.pair.setValue([this.e1.getValue(), this.e2.getValue()], this);
      } else if (this.pair.hasValue()) {
        this.e1.setValue(this.pair.getValue()[0], this);
        return this.e2.setValue(this.pair.getValue()[1], this);
      }
    };

    PairerConstraint.prototype.processForgetValue = function() {
      this.e1.forgetValue(this);
      this.e2.forgetValue(this);
      return this.pair.forgetValue(this);
    };

    return PairerConstraint;

  })();
  constantConnector = function(value) {
    var toReturn;
    toReturn = new Connector("constant(" + value + ")");
    new ConstantConstraint(toReturn, value);
    return toReturn;
  };
  probedConnector = function(label) {
    var toReturn;
    toReturn = new Connector("probed(" + label + ")");
    return toReturn;
  };
  dividedSegmentConstraint = function(left, right, width, mid, part) {
    var leftWidth;
    if (part == null) {
      part = 0.5;
    }
    new AdderConstraint(left, width, right);
    leftWidth = new Connector("divdedSegment-left-width");
    new MultiplierConstraint(width, constantConnector(part), leftWidth);
    return new AdderConstraint(left, leftWidth, mid);
  };
  partwaysConstraint = function(a, b, part, out) {
    var bigSubtract, smallSubtract;
    bigSubtract = new Connector("partways-big-subtract");
    smallSubtract = new Connector("partways-small-subtract");
    new AdderConstraint(a, bigSubtract, b);
    new AdderConstraint(a, smallSubtract, out);
    return new MultiplierConstraint(bigSubtract, constantConnector(part), smallSubtract);
  };
  return {
    Connector: Connector,
    WatcherPseudoconstraint: WatcherPseudoconstraint,
    ProbePseudoconstraint: ProbePseudoconstraint,
    ConstantConstraint: ConstantConstraint,
    EqualityConstraint: EqualityConstraint,
    AdderConstraint: AdderConstraint,
    MultiplierConstraint: MultiplierConstraint,
    PairerConstraint: PairerConstraint,
    constantConnector: constantConnector,
    probedConnector: probedConnector,
    dividedSegmentConstraint: dividedSegmentConstraint,
    partwaysConstraint: partwaysConstraint
  };
});
