// Generated by CoffeeScript 1.6.3
define(function() {
  var CPMCify, CPMCifyReturnedObjectInsanity;
  CPMCify = function(object, method) {
    " Suppose a class generally has methods written in the\nmethod-chaining style (returning 'this'), but there are\nexceptions, which return a new object as context. (For instance --\nd3's 'selectAll' or 'append'.)\n\nContinuation-passing method-chaining style rewrites that to\nconform to the 'every method returns this' expectation, by adding\na new function argument to the end of the list of arguments. If\nthis argument is provided, it will be called immediately on the\n'new object' (the appended or selected or .... object), but the\nmethod itself will return 'this'. This allows the user to\nconstruct method-tree, where descent to lower levels occurs inside\nthese functions ('continuations'). ";
    " CPMCify takes a prototype object and the name of a method, and\npatches the prototype object with a CPMCified version of that\nmethod. It's pretty hackish. ";
    var m, oldMethod, _i, _len;
    if (typeof method !== "string") {
      for (_i = 0, _len = method.length; _i < _len; _i++) {
        m = method[_i];
        CPMCify(object, m);
      }
      return;
    }
    oldMethod = object[method];
    return object[method] = function() {
      var args, returned;
      args = Array.prototype.slice.call(arguments);
      if (args.length === oldMethod.length) {
        return oldMethod.apply(this, args);
      } else if (args.length === oldMethod.length + 1) {
        returned = oldMethod.apply(this, args.slice(0, args.length - 1));
        args[args.length - 1].apply(returned);
        return this;
      }
    };
  };
  CPMCifyReturnedObjectInsanity = function(object, method, methodOfReturned) {
    " CPMCify relies upon the fact that the method to be CPMCified\nexists on a prototype, where we can mess with it. Suppose,\ninstead, that it is generated dynamically and put onto an object\nreturned from a second method. We then must instead patch this\nsecond method, to make sure whatever object it returns is\nappropriately CPMCified. ";
    " That is what CPMCifyReturnedObjectInsanity does. It is\ninsanely hackish. ";
    var oldMethod;
    oldMethod = object[method];
    return object[method] = function() {
      var returned;
      returned = oldMethod.apply(this, arguments);
      CPMCify(returned, methodOfReturned);
      return returned;
    };
  };
  return {
    ify: CPMCify,
    ifyReturnedObjectInsanity: CPMCifyReturnedObjectInsanity
  };
});
