// Generated by CoffeeScript 1.6.3
var __slice = [].slice,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

require(['pins', 'boxes', 'cpmc'], function(pins, boxes, cpmc) {
  var BoardModel, BoardView, Domino, MatrixView, PermView, SimpleBoard, brace, d3extension, o, remove, _i, _len, _ref;
  _ref = [d3.selection.prototype, d3.selection.enter.prototype];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    o = _ref[_i];
    cpmc.ify(o, ["append", "select", "selectAll"]);
  }
  cpmc.ifyReturnedObjectInsanity(d3.selection.prototype, "data", ["enter", "exit"]);
  pins.install(d3);
  remove = function(array, elem) {
    return array.splice(array.map(String).indexOf(String(elem)), 1);
  };
  d3extension = function(creator) {
    return function() {
      var args, selection;
      selection = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      selection.each(function(d, i) {
        this.selfAttrs = {};
        this.old_setAttribute = this.setAttribute;
        this.old_getAttribute = this.getAttribute;
        this.setAttribute = function(attr, val) {
          var info;
          if (attr in this.selfAttrs) {
            info = this.selfAttrs[attr];
            if (info["var"] != null) {
              this[info["var"]] = val;
            }
            if (info.onSet != null) {
              return info.onSet.call(this, val);
            }
          } else {
            return this.old_setAttribute.call(this, attr, val);
          }
        };
        this.getAttribute = function(attr) {
          var info;
          if (attr in this.selfAttrs) {
            info = this.selfAttrs[attr];
            if (info["var"] != null) {
              return this[info["var"]];
            }
            if (info.onGet != null) {
              return info.onGet.call(this);
            }
          } else {
            return this.old_getAttribute.call(this, attr);
          }
        };
        return creator.call.apply(creator, [this, d, i].concat(__slice.call(args)));
      });
      return selection;
    };
  };
  brace = d3extension(function(d, i, params) {
    if (params == null) {
      params = {};
    }
    if (params.dir == null) {
      params.dir = "right";
    }
    switch (params.dir) {
      case "left":
        this.pattern = [[0, 0], [1, 0.5], [0, 1]];
        break;
      case "right":
        this.pattern = [[1, 0], [0, 0.5], [1, 1]];
        break;
      case "up":
        this.pattern = [[0, 0], [0.5, 1], [1, 0]];
        break;
      case "down":
        this.pattern = [[0, 1], [0.5, 0], [1, 1]];
        break;
      default:
        throw "params.dir must be 'left', 'right', 'up', or 'down'!";
    }
    this.selfAttrs = {
      "x": {
        "var": "x",
        onSet: function() {
          return this.redraw();
        }
      },
      "y": {
        "var": "y",
        onSet: function() {
          return this.redraw();
        }
      },
      "width": {
        "var": "width",
        onSet: function() {
          return this.redraw();
        }
      },
      "height": {
        "var": "height",
        onSet: function() {
          return this.redraw();
        }
      }
    };
    this.polyline = d3.select(this).append("polyline").style("fill", "none");
    return this.redraw = function() {
      var points, x, y;
      if ((this.x != null) && (this.y != null) && (this.width != null) && (this.height != null)) {
        points = ((function() {
          var _j, _len1, _ref1, _ref2, _results;
          _ref1 = this.pattern;
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            _ref2 = _ref1[_j], x = _ref2[0], y = _ref2[1];
            _results.push("" + (this.x + this.width * x) + "," + (this.y + this.height * y));
          }
          return _results;
        }).call(this)).join(" ");
        return this.polyline.attr("points", points);
      }
    };
  });
  Domino = (function() {
    function Domino(_arg) {
      var d1, d2;
      d1 = _arg[0], d2 = _arg[1];
      if ((d1[0] + d1[1]) % 2 === 0) {
        this.d = [d1, d2];
      } else {
        this.d = [d2, d1];
      }
    }

    Domino.prototype.isVertical = function() {
      return this.d[0][0] === this.d[1][0];
    };

    Domino.prototype.tl = function() {
      return [Math.min(this.d[0][0], this.d[1][0]), Math.min(this.d[0][1], this.d[1][1])];
    };

    Domino.prototype.br = function() {
      return [Math.max(this.d[0][0], this.d[1][0]), Math.max(this.d[0][1], this.d[1][1])];
    };

    return Domino;

  })();
  BoardModel = (function() {
    function BoardModel(m, n) {
      var i, j, _ref1;
      this.m = m;
      this.n = n;
      this.partSize = this.m * this.n / 2;
      this.cellCoords = (_ref1 = []).concat.apply(_ref1, (function() {
        var _j, _ref1, _results;
        _results = [];
        for (j = _j = 0, _ref1 = this.n; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
          _results.push((function() {
            var _k, _ref2, _results1;
            _results1 = [];
            for (i = _k = 0, _ref2 = this.m; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; i = 0 <= _ref2 ? ++_k : --_k) {
              _results1.push([i, j]);
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this));
      this.part1 = (function() {
        var _j, _len1, _ref2, _ref3, _results;
        _ref2 = this.cellCoords;
        _results = [];
        for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
          _ref3 = _ref2[_j], i = _ref3[0], j = _ref3[1];
          if ((i + j) % 2 === 0) {
            _results.push([i, j]);
          }
        }
        return _results;
      }).call(this);
      this.part2 = (function() {
        var _j, _len1, _ref2, _ref3, _results;
        _ref2 = this.cellCoords;
        _results = [];
        for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
          _ref3 = _ref2[_j], i = _ref3[0], j = _ref3[1];
          if ((i + j) % 2 === 1) {
            _results.push([i, j]);
          }
        }
        return _results;
      }).call(this);
      this.dominoes = [];
      this.selectedDomino = false;
      this.selectedCell = false;
      this.dragOrigin = false;
      this.events = d3.dispatch(["change"]);
    }

    BoardModel.distance = function(coord1, coord2) {
      return Math.abs(coord1[0] - coord2[0]) + Math.abs(coord1[1] - coord2[1]);
    };

    BoardModel.prototype.validCoord = function(coord) {
      var _ref1, _ref2;
      return ((0 <= (_ref1 = coord[0]) && _ref1 < this.m)) && ((0 <= (_ref2 = coord[1]) && _ref2 < this.n));
    };

    BoardModel.prototype.neighbors = function(coord) {
      var delta, deltas, poss, posses;
      deltas = [[0, 1], [0, -1], [1, 0], [-1, 0]];
      posses = (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = deltas.length; _j < _len1; _j++) {
          delta = deltas[_j];
          _results.push([coord[0] + delta[0], coord[1] + delta[1]]);
        }
        return _results;
      })();
      return (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = posses.length; _j < _len1; _j++) {
          poss = posses[_j];
          if (this.validCoord(poss)) {
            _results.push(poss);
          }
        }
        return _results;
      }).call(this);
    };

    BoardModel.prototype.allTilings = function() {
      var partialTilings, toReturn,
        _this = this;
      toReturn = [];
      partialTilings = function(tilingSoFar, remainingCoords) {
        var cur, n, newRemainingCoords, newTiling, _j, _len1, _ref1, _ref2, _results;
        if (remainingCoords.length === 0) {
          return toReturn.push(tilingSoFar);
        } else {
          cur = remainingCoords[0];
          _ref1 = _this.neighbors(cur);
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            n = _ref1[_j];
            if (_ref2 = String(n), __indexOf.call(remainingCoords.map(String), _ref2) >= 0) {
              newTiling = tilingSoFar.concat([new Domino([cur, n])]);
              newRemainingCoords = remainingCoords.slice(0);
              remove(newRemainingCoords, cur);
              remove(newRemainingCoords, n);
              _results.push(partialTilings(newTiling, newRemainingCoords));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        }
      };
      partialTilings([], this.cellCoords);
      return toReturn;
    };

    return BoardModel;

  })();
  window.BoardModel = BoardModel;
  SimpleBoard = (function() {
    function SimpleBoard(sel, model) {
      this.sel = sel;
      this.model = model;
      this.boardGrid = new boxes.GridBox("boardGrid", [this.model.m, this.model.n]).pin({
        top: sel.pin("top"),
        left: sel.pin("left"),
        bottom: sel.pin("bottom"),
        right: sel.pin("right"),
        aspect: this.model.n / this.model.m,
        width: sel.pin("width"),
        hmid: sel.pin("hmid")
      });
      this.singleVisibleCell = false;
      this.sel.append("rect").boxify("s").pin("all", this.boardGrid.all).style("stroke", "black").style("stroke-width", "1px").style("fill", "transparent");
      this.render();
    }

    SimpleBoard.prototype.render = function() {
      var view;
      view = this;
      return this.sel.selectAll("rect.square").data(this.model.cellCoords).enter(function() {
        return this.append("rect").classed("square", true).boxify("board-square-background").pin("all", function(d) {
          return view.boardGrid.cell(d).all;
        }).style("stroke", "black").style("stroke-width", "1px");
      }).style("fill", function(d) {
        if (!view.singleVisibleCell || (String(view.singleVisibleCell) === String(d))) {
          if ((d[0] + d[1]) % 2) {
            return "black";
          } else {
            return "red";
          }
        } else {
          return "none";
        }
      });
    };

    return SimpleBoard;

  })();
  BoardView = (function() {
    function BoardView(sel, model) {
      var id,
        _this = this;
      this.sel = sel;
      this.model = model;
      this.boardGrid = new boxes.GridBox("boardGrid", [this.model.m, this.model.n]).pin({
        top: sel.pin("top"),
        left: sel.pin("left"),
        bottom: sel.pin("bottom"),
        right: sel.pin("right"),
        aspect: this.model.n / this.model.m,
        width: sel.pin("width"),
        hmid: sel.pin("hmid")
      });
      this.domMargin = 10;
      this.hoverMode = false;
      this.dragMode = false;
      id = Math.floor(Math.random() * 1000000000);
      this.model.events.on("change.BoardView" + id, function() {
        return _this.render();
      });
      this.render();
    }

    BoardView.prototype.render = function() {
      var change, model, view;
      view = this;
      model = this.model;
      change = model.events.change;
      this.sel.selectAll("g.square").data(model.cellCoords).enter(function() {
        return this.append("g").classed("square", true).append("rect", function() {
          return this.classed("background", true).boxify("board-square-background").pin("all", function(d) {
            return view.boardGrid.cell(d).all;
          }).style("fill", function(_arg) {
            var di, dj;
            di = _arg[0], dj = _arg[1];
            if ((di + dj) % 2) {
              return "black";
            } else {
              return "red";
            }
          });
        }).append("rect", function() {
          return this.classed("cover", true).boxify("board-square-cover").pin("all", function(d) {
            return view.boardGrid.cell(d).all;
          }).style("fill", "none");
        }).on("mouseover", function(d) {
          if (view.hoverMode) {
            model.selectedCell = d;
            return change();
          }
        }).on("mouseout", function(d) {
          if (view.hoverMode) {
            model.selectedCell = false;
            return change();
          }
        }).on("mousedown", function(d) {
          if (view.dragMode) {
            model.dragOrigin = d;
            return change();
          }
        }).on("mouseup", function(d) {
          if (view.dragMode && model.dragOrigin) {
            if (BoardModel.distance(d, model.dragOrigin) === 1) {
              model.dominoes.push(new Domino([model.dragOrigin, d]));
              model.dragOrigin = false;
              return change();
            }
          }
        }).style("cursor", view.dragMode ? "pointer" : "auto");
      }).selectAll("rect.cover", function() {
        return this.style("fill", function(d) {
          if (String(d) === String(model.selectedCell)) {
            return "url(#hatch00)";
          } else {
            return "none";
          }
        });
      });
      return this.sel.selectAll("rect.domino").data(model.dominoes, String).enter(function() {
        return this.append("rect").classed("domino", true).boxify("board-domino").pin("tl", function(d) {
          return boxes.translate(view.boardGrid.cell(d.tl()).tl, [view.domMargin, view.domMargin]);
        }).pin("br", function(d) {
          return boxes.translate(view.boardGrid.cell(d.br()).br, [-view.domMargin, -view.domMargin]);
        }).style("stroke", "black").on("mouseover", function(d) {
          if (view.hoverMode) {
            model.selectedDomino = d;
            return change();
          }
        }).on("mouseout", function(d) {
          if (view.hoverMode) {
            model.selectedDomino = false;
            return change();
          }
        }).on("mousedown", function(d) {
          if (view.dragMode) {
            remove(model.dominoes, d);
            return change();
          }
        }).style("cursor", view.dragMode ? "pointer" : "auto");
      }).style("fill", function(d) {
        if (d === model.selectedDomino) {
          return "rgb(150,150,255)";
        } else {
          return "white";
        }
      }).exit(function() {
        return this.remove();
      });
    };

    return BoardView;

  })();
  PermView = (function() {
    function PermView(sel, model) {
      var id,
        _this = this;
      this.sel = sel;
      this.model = model;
      this.textSpace = 20;
      this.permGrid = new boxes.GridBox("permGrid", [1, model.partSize]).pin({
        "tl": boxes.translate(sel.pin("tl"), [0, this.textSpace]),
        "br": boxes.translate(sel.pin("br"), [0, -this.textSpace])
      });
      id = Math.floor(Math.random() * 1000000000);
      this.model.events.on("change.PermView" + id, function() {
        return _this.render();
      });
      this.render();
    }

    PermView.prototype.render = function() {
      var change, model, view, _j, _ref1, _results;
      view = this;
      model = this.model;
      change = model.events.change;
      this.sel.selectAll("line.domino").data(model.dominoes, String).enter(function() {
        return this.append("line").classed("domino", true).boxify().pin("tl", function(d) {
          var index;
          index = model.part1.map(String).indexOf(String(d.d[0]));
          return boxes.translate(view.permGrid.cell([0, index]).tm, [0, 5]);
        }).pin("br", function(d) {
          var index;
          index = model.part2.map(String).indexOf(String(d.d[1]));
          return boxes.translate(view.permGrid.cell([0, index]).bm, [0, -5]);
        }).style("stroke-width", "5px").on("mouseover", function(d) {
          model.selectedDomino = d;
          return change();
        }).on("mouseout", function(d) {
          model.selectedDomino = false;
          return change();
        }).on("mousedown", function(d) {
          model.dominoes.splice(model.dominoes.indexOf(d), 1);
          return change();
        }).style("cursor", "pointer");
      }).style("stroke", function(d) {
        if (d === model.selectedDomino) {
          return "blue";
        } else {
          return "black";
        }
      }).exit(function() {
        return this.remove();
      });
      return this.sel.selectAll("g.labelPair").data((function() {
        _results = [];
        for (var _j = 0, _ref1 = model.partSize; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; 0 <= _ref1 ? _j++ : _j--){ _results.push(_j); }
        return _results;
      }).apply(this)).enter(function() {
        return this.append("g", function() {
          return this.classed("labelPair", true).append("g", function() {
            return this.classed("subboard", true).classed("top", true);
          }).append("g", function() {
            return this.classed("subboard", true).classed("bottom", true);
          }).selectEach("g.subboard", function(d) {
            var is1, part, subModel, subView;
            subModel = new BoardModel(model.m, model.n);
            is1 = this.classed("top");
            part = is1 ? model.part1 : model.part2;
            this.boxify("perm-board-" + (is1 ? 'top' : 'bottom')).pin((is1 ? "bm" : "tm"), function(d) {
              return view.permGrid.cell([0, d])[is1 ? 'tm' : 'bm'];
            }).pin((is1 ? "top" : "bottom"), function(d) {
              return view.sel.pin(is1 ? "top" : "bottom");
            });
            subView = new SimpleBoard(this, subModel);
            subView.singleVisibleCell = part[d];
            subView.render();
            return this.on("mouseover", function(d) {
              model.selectedCell = part[d];
              return change();
            }).on("mouseout", function(d) {
              model.selectedCell = false;
              return change();
            }).on("mousedown", function(d) {
              model.dragOrigin = part[d];
              return d3.event.preventDefault();
            }).on("mouseup", function(d) {
              var dragDest;
              if (model.dragOrigin) {
                dragDest = part[d];
                if (BoardModel.distance(dragDest, model.dragOrigin) === 1) {
                  model.dominoes.push(new Domino([model.dragOrigin, dragDest]));
                  model.dragOrigin = false;
                }
              }
              return change();
            }).style("cursor", "pointer");
          });
        });
      }).selectEach("text", function(d) {
        var part;
        part = this.classed("top") ? model.part1 : model.part2;
        if (String(part[d]) === String(model.selectedCell)) {
          return this.style("fill", "blue").style("font-weight", "bold");
        } else {
          return this.style("fill", "black").style("font-weight", "normal");
        }
      }).selectEach("g.subboard", function(d) {
        var part;
        part = this.classed("top") ? model.part1 : model.part2;
        if (String(part[d]) === String(model.selectedCell)) {
          return this.selectAll("rect").style("stroke", "blue");
        } else {
          return this.selectAll("rect").style("stroke", "black");
        }
      });
    };

    return PermView;

  })();
  MatrixView = (function() {
    function MatrixView(sel, model) {
      var d1, d2, i, j, _ref1,
        _this = this;
      this.sel = sel;
      this.model = model;
      this.matrixGrid = new boxes.GridBox("matrixGrid", [this.model.partSize, this.model.partSize]).pin("all", this.sel.pin("all"));
      this.matrixText = (function() {
        var _j, _ref1, _results;
        _results = [];
        for (i = _j = 0, _ref1 = this.model.partSize; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          _results.push((function() {
            var _k, _ref2, _results1;
            _results1 = [];
            for (j = _k = 0, _ref2 = this.model.partSize; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; j = 0 <= _ref2 ? ++_k : --_k) {
              d1 = this.model.part1[i];
              d2 = this.model.part2[j];
              if (Math.abs(d1[0] - d2[0]) === 1 && Math.abs(d1[1] - d2[1]) === 0) {
                _results1.push(1);
              } else if (Math.abs(d1[0] - d2[0]) === 0 && Math.abs(d1[1] - d2[1]) === 1) {
                _results1.push("i");
              } else {
                _results1.push(0);
              }
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this);
      this.matrixCoords = (_ref1 = []).concat.apply(_ref1, (function() {
        var _j, _ref1, _results;
        _results = [];
        for (i = _j = 0, _ref1 = this.model.partSize; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          _results.push((function() {
            var _k, _ref2, _results1;
            _results1 = [];
            for (j = _k = 0, _ref2 = this.model.partSize; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; j = 0 <= _ref2 ? ++_k : --_k) {
              _results1.push([i, j]);
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this));
      this.model.events.on("change.MatrixView", function() {
        return _this.render();
      });
      this.render();
    }

    MatrixView.prototype.render = function() {
      var change, model, view, _j, _k, _ref1, _ref2, _results, _results1;
      view = this;
      model = this.model;
      change = model.events.change;
      this.sel.selectAll("text.label").data(view.matrixCoords).enter(function() {
        return this.append("text").classed("label", true).boxify("text").text(function(d) {
          return "" + view.matrixText[d[0]][d[1]];
        }).style("text-anchor", "middle").style("dominant-baseline", "central").style("font-style", function(d) {
          if (view.matrixText[d[0]][d[1]] === "i") {
            return "italic";
          } else {
            return "normal";
          }
        }).pin("tl", function(d) {
          return view.matrixGrid.cell(d).mm;
        });
      });
      this.sel.selectAll("circle.mark").data(model.dominoes, String).enter(function() {
        return this.append("circle").classed("mark", true).boxify("domino-circle").pin("mm", function(d) {
          var i, j;
          i = model.part1.map(String).indexOf(String(d.d[0]));
          j = model.part2.map(String).indexOf(String(d.d[1]));
          return view.matrixGrid.cell([i, j]).mm;
        }).pin({
          width: 20,
          height: 20
        }).style("fill", "none").style("stroke", "black").style("stroke-width", "2px");
      }).style("stroke", function(d) {
        if (d.d === model.selectedDomino.d) {
          return "blue";
        } else {
          return "black";
        }
      }).exit(function() {
        return this.remove();
      });
      this.sel.selectAll("rect.row").data((function() {
        _results = [];
        for (var _j = 0, _ref1 = model.partSize; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; 0 <= _ref1 ? _j++ : _j--){ _results.push(_j); }
        return _results;
      }).apply(this)).enter(function() {
        return this.append("rect").classed("row", true).boxify("matrix-row").pin("tl", function(d) {
          return view.matrixGrid.cell([d, 0]).tl;
        }).pin("br", function(d) {
          return view.matrixGrid.cell([d, model.partSize - 1]).br;
        }).style("fill", "none").style("stroke-width", "2px");
      }).style("stroke", function(d) {
        if (String(model.selectedCell) === String(model.part1[d])) {
          return "blue";
        } else {
          return "none";
        }
      });
      return this.sel.selectAll("rect.col").data((function() {
        _results1 = [];
        for (var _k = 0, _ref2 = model.partSize; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; 0 <= _ref2 ? _k++ : _k--){ _results1.push(_k); }
        return _results1;
      }).apply(this)).enter(function() {
        return this.append("rect").classed("col", true).boxify("matrix-row").pin("tl", function(d) {
          return view.matrixGrid.cell([0, d]).tl;
        }).pin("br", function(d) {
          return view.matrixGrid.cell([model.partSize - 1, d]).br;
        }).style("fill", "none").style("stroke-width", "2px");
      }).style("stroke", function(d) {
        if (String(model.selectedCell) === String(model.part2[d])) {
          return "blue";
        } else {
          return "none";
        }
      });
    };

    return MatrixView;

  })();
  d3.select("document").on("dragstart", function() {
    return false;
  });
  return (function() {
    var board, boardModel, boardView, matrix, perm, row, svg;
    svg = d3.select("#diag1 svg");
    row = svg.append("g").classed("row", true).boxify("row").pin({
      height: 120
    });
    board = row.append("g").classed("board", true).boxify("board").pin({
      tl: row.pin("tl"),
      bottom: row.pin("bottom")
    });
    perm = row.append("g").classed("perm", true).boxify("perm").pin({
      tl: boxes.translate(board.pin("tr"), [20, 0]),
      bottom: row.pin("bottom"),
      aspect: 2
    });
    matrix = row.append("g").classed("matrix", true).boxify("matrix").pin({
      tl: boxes.translate(perm.pin("tr"), [20, 0]),
      bottom: row.pin("bottom"),
      aspect: 1
    });
    row.pin("right", matrix.pin("right"));
    svg.boxify("svg").pin({
      tl: boxes.translate(row.pin("tl"), [-10, -10]),
      br: boxes.translate(row.pin("br"), [10, 10])
    });
    boardModel = new BoardModel(3, 4);
    boardView = new BoardView(board, boardModel);
    boardView.hoverMode = true;
    boardView.dragMode = true;
    new PermView(perm, boardModel);
    new MatrixView(matrix, boardModel);
    boardModel.dominoes = [new Domino([[0, 0], [1, 0]])];
    return boardModel.events.change();
  })();
});
