// Generated by CoffeeScript 1.6.3
var addCommas, compare, d3extension, pixel, rowbot, spikeogram, translate, watchForSet,
  __slice = [].slice;

addCommas = function(nStr) {
  var rgx, x, x1, x2;
  nStr += '';
  x = nStr.split('.');
  x1 = x[0];
  x2 = x.length > 1 ? '.' + x[1] : '';
  rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
    x1 = x1.replace(rgx, '$1' + ',' + '$2');
  }
  return x1 + x2;
};

translate = function(x, y) {
  return "translate(" + x + "," + y + ")";
};

compare = function(f) {
  return function(a, b) {
    return f(a) - f(b);
  };
};

pixel = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";

watchForSet = function(object, targetAttr, func) {
  var old_setAttribute;
  old_setAttribute = object.setAttribute;
  return object.setAttribute = function(attr, val) {
    old_setAttribute.call(object, attr, val);
    if (attr === targetAttr) {
      return func.call(object, val);
    }
  };
};

d3extension = function(creator) {
  return function() {
    var args, selection;
    selection = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    selection.each(function(d, i) {
      this.selfAttrs = {};
      this.old_setAttribute = this.setAttribute;
      this.old_getAttribute = this.getAttribute;
      this.setAttribute = function(attr, val) {
        var info;
        if (attr in this.selfAttrs) {
          info = this.selfAttrs[attr];
          if (info["var"] != null) {
            this[info["var"]] = val;
          }
          if (info.onSet != null) {
            return info.onSet.call(this, val);
          }
        } else {
          return this.old_setAttribute.call(this, attr, val);
        }
      };
      this.getAttribute = function(attr) {
        var info;
        if (attr in this.selfAttrs) {
          info = this.selfAttrs[attr];
          if (info["var"] != null) {
            return this[info["var"]];
          }
          if (info.onGet != null) {
            return info.onGet.call(this);
          }
        } else {
          return this.old_getAttribute.call(this, attr);
        }
      };
      return creator.call.apply(creator, [this, d, i].concat(__slice.call(args)));
    });
    return selection;
  };
};

rowbot = d3extension(function(d, i, params) {
  if (params == null) {
    params = {};
  }
  if (params.orient == null) {
    params.orient = "hor";
  }
  switch (params.orient) {
    case "hor":
      this.sizeAttr = "width";
      this.transformer = function(x) {
        return translate(x, 0);
      };
      break;
    case "ver":
      this.sizeAttr = "height";
      this.transformer = function(x) {
        return translate(0, x);
      };
      break;
    default:
      throw "params.orient must be 'hor' or 'ver'!";
  }
  this.selfAttrs = {
    "reorderProgress": {
      "var": "reorderProgress",
      onSet: function() {
        return this.redraw();
      }
    }
  };
  this.reorder = function(orderer) {
    var indices, offset, _i, _j, _len, _ref, _ref1, _results,
      _this = this;
    indices = (function() {
      _results = [];
      for (var _i = 0, _ref = this.childNodes.length; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    this.sortedIndices = indices.sort(compare(function(i) {
      return orderer.call(_this.childNodes[i], _this.childNodes[i].__data__, i);
    }));
    this.oldOffsets = this.curOffsets;
    this.newOffsets = [];
    offset = 0;
    _ref1 = this.sortedIndices;
    for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
      i = _ref1[_j];
      this.newOffsets[i] = offset;
      offset += parseFloat(d3.select(this.childNodes[i]).attr(this.sizeAttr));
    }
    this.offsetInterpolator = d3.interpolateArray(this.oldOffsets, this.newOffsets);
    this.reorderProgress = 0;
    return d3.select(this);
  };
  this.redraw = function() {
    var node, _i, _len, _ref, _results;
    this.curOffsets = this.offsetInterpolator(this.reorderProgress);
    _ref = this.childNodes;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      node = _ref[i];
      _results.push(d3.select(node).attr("transform", this.transformer(this.curOffsets[i])));
    }
    return _results;
  };
  return this.curOffsets = [];
});

spikeogram = d3extension(function(d, i) {
  this.selfAttrs = {
    "width": {
      "var": "width",
      onSet: function() {
        return this.redrawAll();
      }
    },
    "height": {
      "var": "height",
      onSet: function() {
        return this.redrawAll();
      }
    },
    "max-radius": {
      "var": "maxR",
      onSet: function() {
        return this.redrawAll();
      }
    },
    "max-value": {
      "var": "maxY",
      onSet: function() {
        return this.redrawAll();
      }
    },
    "points": {
      "var": "points",
      onSet: function() {
        return this.redrawAll();
      }
    },
    "highlight-radius": {
      "var": "highlightRadius",
      onSet: function() {
        return this.redrawHighlight();
      }
    }
  };
  this.setUp = function() {
    this.d3this = d3.select(this);
    this.d3this.append("svg:path").classed("disk", true);
    this.d3this.append("svg:path").classed("highlightDisk", true);
    this.d3this.append("svg:path").classed("main", true);
    this.d3this.append("svg:path").classed("highlight", true);
    return this.baseDrawn = false;
  };
  this.drawReady = function() {
    return this.width && this.height && this.maxR && this.maxY && this.points;
  };
  this.redrawAll = function() {
    if (this.drawReady()) {
      this.xScale = d3.scale.linear().domain([-this.maxR, this.maxR]).range([0, this.width]);
      this.yScale = d3.scale.linear().domain([0, this.maxY]).range([this.height, 0]);
      this.lineGen = d3.svg.line().interpolate("linear").x(function(p) {
        return this.xScale(p[0]);
      }).y(function(p) {
        return this.yScale(p[1]);
      });
      this.d3this.select("path.main").attr("d", this.spikePoints(this.points));
      this.d3this.select("path.disk").attr("d", this.baseEllipsePath(16));
      this.baseDrawn = true;
      return this.redrawHighlight();
    }
  };
  this.redrawHighlight = function() {
    if (!this.baseDrawn) {
      return this.redrawAll();
    } else {
      if (this.drawReady() && this.highlightRadius) {
        this.d3this.select("path.highlight").attr("d", this.spikeHighlightPoints(this.points, this.highlightRadius));
        return this.d3this.select("path.highlightDisk").attr("d", this.baseEllipsePath(this.highlightRadius));
      }
    }
  };
  this.baseEllipsePath = function(r) {
    var end, rx, start;
    start = this.xScale(-r);
    end = this.xScale(r);
    rx = (end - start) / 2;
    return "M " + start + " " + this.height + " A " + rx + " " + (rx / 2) + " 0 0 0 " + end + " " + this.height;
  };
  this.spikePoints = function(data) {
    var lhsPoints, maxR, points, r, y;
    maxR = d3.max((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        d = data[_i];
        _results.push(d[0]);
      }
      return _results;
    })());
    data.reverse();
    lhsPoints = (function() {
      var _i, _len, _ref, _results;
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        _ref = data[_i], r = _ref[0], y = _ref[1];
        _results.push([-r, y]);
      }
      return _results;
    })();
    data.reverse();
    points = __slice.call(lhsPoints).concat(__slice.call(data), [[maxR, 0]], [[-maxR, 0]]);
    return this.lineGen(points) + "Z";
  };
  this.spikeHighlightPoints = function(data, radius) {
    var filler, lastPt, newData, r, subData, y;
    subData = (function() {
      var _i, _len, _ref, _results;
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        _ref = data[_i], r = _ref[0], y = _ref[1];
        if (r < radius) {
          _results.push([r, y]);
        }
      }
      return _results;
    })();
    lastPt = subData[subData.length - 1];
    filler = (function() {
      var _i, _ref, _ref1, _results;
      _results = [];
      for (i = _i = _ref = subData.length, _ref1 = data.length; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; i = _ref <= _ref1 ? ++_i : --_i) {
        _results.push(lastPt);
      }
      return _results;
    })();
    newData = __slice.call(subData).concat(__slice.call(filler));
    return this.spikePoints(newData);
  };
  return this.setUp();
});

d3.json("data.json", function(data) {
  var PI, avgRadius, citiesList, city, cityBoxes, fontScale, graph, h, highlightR, i, inRadii, kv, labelSvg, labelsHeight, lastPop, lastRadius, lineGen, nameWidth, onclick, onmouseover, order, popDens, popdens, pops, pow, preWidth, pt, r, radii, rankLabels, rankToNameWidth, rankWidth, rankings, rowHeight, setMapToCity, sortHighlight, sortLabelHighlight, spikeH, spikeW, svg, w, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n, _o, _p, _ref, _ref1, _results;
  inRadii = [2, 4, 8, 16];
  rankLabels = ["Limits"].concat(__slice.call((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = inRadii.length; _i < _len; _i++) {
        r = inRadii[_i];
        _results.push("" + r + "mi");
      }
      return _results;
    })()));
  radii = [16].concat(__slice.call(inRadii));
  data = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      city = data[_i];
      if (!city.ignore && !city.error) {
        _results.push(city);
      }
    }
    return _results;
  })();
  window.data = data;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    city = data[_i];
    city.pops = (function() {
      var _j, _len1, _ref, _results;
      _ref = city.data;
      _results = [];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        pt = _ref[_j];
        _results.push([pt.distance, pt.population]);
      }
      return _results;
    })();
  }
  kv = function(pairs, key) {
    var k, matches, v;
    matches = (function() {
      var _j, _len1, _ref, _results;
      _results = [];
      for (_j = 0, _len1 = pairs.length; _j < _len1; _j++) {
        _ref = pairs[_j], k = _ref[0], v = _ref[1];
        if (k === key) {
          _results.push([k, v]);
        }
      }
      return _results;
    })();
    if (matches) {
      return matches[0][1];
    } else {
      return false;
    }
  };
  for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
    city = data[_j];
    city.rankings = [];
  }
  for (i = _k = 0, _len2 = inRadii.length; _k < _len2; i = ++_k) {
    r = inRadii[i];
    data.sort(compare(function(city) {
      return -kv(city.pops, r);
    }));
    for (order = _l = 0, _len3 = data.length; _l < _len3; order = ++_l) {
      city = data[order];
      city.rankings[i + 1] = {
        rank: order + 1,
        order: order,
        population: Math.floor(kv(city.pops, r)),
        city: city
      };
    }
  }
  data.sort(function(city1, city2) {
    return city2.properPopulation - city1.properPopulation;
  });
  for (order = _m = 0, _len4 = data.length; _m < _len4; order = ++_m) {
    city = data[order];
    city.rankings[0] = {
      rank: city.properRank,
      order: order,
      population: city.properPopulation,
      city: city
    };
  }
  PI = Math.PI;
  pow = Math.pow;
  for (_n = 0, _len5 = data.length; _n < _len5; _n++) {
    city = data[_n];
    pops = city.pops;
    popdens = (city.popdens = []);
    for (i = _o = 0, _ref = pops.length; 0 <= _ref ? _o < _ref : _o > _ref; i = 0 <= _ref ? ++_o : --_o) {
      lastRadius = i > 0 ? pops[i - 1][0] : 0;
      lastPop = i > 0 ? pops[i - 1][1] : 0;
      avgRadius = (pops[i][0] + lastRadius) / 2;
      popDens = (pops[i][1] - lastPop) / (PI * (pow(pops[i][0], 2) - pow(lastRadius, 2)));
      popdens.push([avgRadius, popDens]);
    }
  }
  highlightR = 16;
  rowHeight = 50;
  preWidth = 180;
  rankWidth = 40;
  rankToNameWidth = 10;
  nameWidth = 190;
  fontScale = d3.scale.pow().exponent(0.5).domain([1, 50]).range([30, 8]);
  spikeW = rowHeight - 5;
  spikeH = 600;
  w = 1100;
  h = rowHeight * data.length;
  labelsHeight = 80;
  d3.select("#labels").style("height", "" + labelsHeight + "px");
  d3.select("#labels-holder").style("height", "" + labelsHeight + "px");
  labelSvg = d3.select("#labels").append("svg:svg").attr("width", w).attr("height", labelsHeight);
  lineGen = d3.svg.line().x(function(p) {
    return p[0];
  }).y(function(p) {
    return p[1];
  });
  sortLabelHighlight = labelSvg.append("svg:path").classed("sortLabelHighlight", true).attr("d", lineGen([[0, labelsHeight], [rankWidth, labelsHeight], [rankWidth - labelsHeight, 0], [-labelsHeight, 0]]));
  labelSvg.append("svg:text").attr("transform", translate(0, labelsHeight - 20)).text("Rank by:").style("font-size", "30px");
  labelSvg.append("svg:text").attr("transform", translate(preWidth + rankWidth * rankLabels.length - 20, labelsHeight - 50)).text("(radius)").style("font-size", "20px");
  labelSvg.append("svg:path").attr("d", lineGen([[preWidth, labelsHeight - 1], [preWidth + rankWidth * rankLabels.length, labelsHeight - 1]])).style("stroke", "black");
  labelSvg.selectAll("path.sep").data((function() {
    _results = [];
    for (var _p = 0, _ref1 = rankLabels.length; 0 <= _ref1 ? _p <= _ref1 : _p >= _ref1; 0 <= _ref1 ? _p++ : _p--){ _results.push(_p); }
    return _results;
  }).apply(this)).enter().append("svg:path").classed("sep", true).attr("d", function(d, i) {
    return lineGen([[preWidth + rankWidth * d, labelsHeight], [preWidth + rankWidth * d - labelsHeight, 0]]);
  }).style("stroke", "black");
  labelSvg.selectAll("text.radiusLabel").data(rankLabels).enter().append("svg:text").classed("radiusLabel", true).text(function(d, i) {
    return d;
  }).attr("transform", function(d, i) {
    return translate(preWidth + rankWidth * (0.5 + i) - 20, labelsHeight - 10) + " rotate(45)";
  }).style("text-anchor", "end").style("font-size", "24px").on("click", function(d, i) {
    return onclick(i);
  }).style("cursor", "pointer");
  $.waypoints.settings.scrollThrottle = 30;
  $('#labels').waypoint(function(event, direction) {
    $(this).toggleClass('sticky', direction === "down");
    return event.stopPropagation();
  });
  svg = d3.select("#chart").append("svg:svg").attr("width", w).attr("height", h);
  graph = svg.append("svg:g").attr("transform", translate(0, 0));
  sortHighlight = graph.append("svg:rect").classed("sortHighlight", true).attr("width", rankWidth).attr("height", rowHeight * data.length);
  onclick = function(index, durationMult) {
    if (durationMult == null) {
      durationMult = 1;
    }
    if (isNaN(index)) {
      return;
    }
    highlightR = radii[index];
    sortHighlight.transition().duration(700 * durationMult).attr("transform", translate(preWidth + rankWidth * index, 0));
    sortLabelHighlight.transition().duration(700 * durationMult).attr("transform", translate(preWidth + rankWidth * index, 0));
    return graph.selectAll("g.city g.spike").transition().duration(700 * durationMult).attr("highlight-radius", highlightR).each("end", function() {
      return citiesList.node().reorder(function(d, i) {
        return d.rankings[index].order;
      }).transition().duration(1200 * durationMult).attr("reorderProgress", 1);
    });
  };
  setMapToCity = function(city) {
    var d;
    d3.select("#map").attr("src", "maps/" + city.longName + ".png");
    d3.select("#overlay1").attr("src", "maps/combined/" + city.longName + ".png").style("opacity", 0.3);
    d3.select("#overlay2").attr("src", pixel);
    d3.select("#city-name").text(city.longName);
    return d3.select("#stats").html(((function() {
      var _len6, _q, _ref2, _results1;
      _ref2 = city.rankings;
      _results1 = [];
      for (i = _q = 0, _len6 = _ref2.length; _q < _len6; i = ++_q) {
        d = _ref2[i];
        _results1.push("<div>In " + (rankLabels[i] === 'Limits' ? 'city limits' : 'a ' + rankLabels[i] + ' radius') + ", there are " + (addCommas(d.population)) + " people, putting this city at \#" + d.rank + ".</div>");
      }
      return _results1;
    })()).join(""));
  };
  onmouseover = function(data, index) {
    setMapToCity(data.city);
    return d3.select("#overlay2").attr("src", "maps/" + data.city.longName + "-" + radii[index] + ".png");
  };
  citiesList = graph.append("svg:g").classed("citiesList", true).call(rowbot, {
    orient: 'ver'
  });
  cityBoxes = citiesList.selectAll("g.city").data(data).enter().append("svg:g").classed("city", true).attr("height", rowHeight);
  rankings = cityBoxes.selectAll("text.ranking").data(function(d) {
    return d.rankings;
  }).enter().append("svg:text").classed("rankText", true).text(function(d) {
    return "" + d.rank;
  }).style("dominant-baseline", "central").style("text-anchor", "middle").style("font-size", function(d, i) {
    return "" + (fontScale(d.rank)) + "pt";
  }).attr("transform", function(d, i) {
    return translate(preWidth + rankWidth * (0.5 + i), rowHeight / 2);
  }).on("click", function(d, i) {
    return onclick(i);
  }).style("cursor", "pointer").on("mouseover", function(d, i) {
    return onmouseover(d, i);
  }).append("svg:title").text(function(d, i) {
    return addCommas(d.population);
  });
  cityBoxes.append("svg:text").text(function(d) {
    return d.longName;
  }).style("dominant-baseline", "central").style("text-anchor", "start").style("font-size", "16pt").attr("transform", translate(preWidth + rankWidth * rankLabels.length + rankToNameWidth, rowHeight / 2)).on("mouseover", function(d, i) {
    return setMapToCity(d);
  });
  cityBoxes.append("svg:g").classed("spike", true).call(spikeogram).attr("width", spikeW).attr("height", spikeH).attr("max-radius", 16).attr("max-value", 100000).attr("points", function(d, i) {
    return d.popdens;
  }).attr("transform", "matrix(0,1,-1,0," + (preWidth + rankWidth * rankLabels.length + rankToNameWidth + nameWidth + spikeH) + ",0)");
  return onclick(0, 0);
});
