// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

require(['pins', 'boxes', 'cpmc'], function(pins, boxes, cpmc) {
  var DotGrid, brace, d3extension, o, remove, stage, _i, _len, _ref;
  _ref = [d3.selection.prototype, d3.selection.enter.prototype];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    o = _ref[_i];
    cpmc.ify(o, ["append", "select", "selectAll"]);
  }
  cpmc.ifyReturnedObjectInsanity(d3.selection.prototype, "data", ["enter", "exit"]);
  pins.install(d3);
  remove = function(array, elem) {
    return array.splice(array.map(String).indexOf(String(elem)), 1);
  };
  d3extension = function(creator) {
    return function() {
      var args, selection;
      selection = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      selection.each(function(d, i) {
        this.selfAttrs = {};
        this.old_setAttribute = this.setAttribute;
        this.old_getAttribute = this.getAttribute;
        this.setAttribute = function(attr, val) {
          var info;
          if (attr in this.selfAttrs) {
            info = this.selfAttrs[attr];
            if (info["var"] != null) {
              this[info["var"]] = val;
            }
            if (info.onSet != null) {
              return info.onSet.call(this, val);
            }
          } else {
            return this.old_setAttribute.call(this, attr, val);
          }
        };
        this.getAttribute = function(attr) {
          var info;
          if (attr in this.selfAttrs) {
            info = this.selfAttrs[attr];
            if (info["var"] != null) {
              return this[info["var"]];
            }
            if (info.onGet != null) {
              return info.onGet.call(this);
            }
          } else {
            return this.old_getAttribute.call(this, attr);
          }
        };
        return creator.call.apply(creator, [this, d, i].concat(__slice.call(args)));
      });
      return selection;
    };
  };
  brace = d3extension(function(d, i, params) {
    if (params == null) {
      params = {};
    }
    if (params.dir == null) {
      params.dir = "right";
    }
    switch (params.dir) {
      case "left":
        this.pattern = [[0, 0], [1, 0.5], [0, 1]];
        break;
      case "right":
        this.pattern = [[1, 0], [0, 0.5], [1, 1]];
        break;
      case "up":
        this.pattern = [[0, 0], [0.5, 1], [1, 0]];
        break;
      case "down":
        this.pattern = [[0, 1], [0.5, 0], [1, 1]];
        break;
      default:
        throw "params.dir must be 'left', 'right', 'up', or 'down'!";
    }
    this.selfAttrs = {
      "x": {
        "var": "x",
        onSet: function() {
          return this.redraw();
        }
      },
      "y": {
        "var": "y",
        onSet: function() {
          return this.redraw();
        }
      },
      "width": {
        "var": "width",
        onSet: function() {
          return this.redraw();
        }
      },
      "height": {
        "var": "height",
        onSet: function() {
          return this.redraw();
        }
      }
    };
    this.polyline = d3.select(this).append("polyline").style("fill", "none");
    return this.redraw = function() {
      var points, x, y;
      if ((this.x != null) && (this.y != null) && (this.width != null) && (this.height != null)) {
        points = ((function() {
          var _j, _len1, _ref1, _ref2, _results;
          _ref1 = this.pattern;
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            _ref2 = _ref1[_j], x = _ref2[0], y = _ref2[1];
            _results.push("" + (this.x + this.width * x) + "," + (this.y + this.height * y));
          }
          return _results;
        }).call(this)).join(" ");
        return this.polyline.attr("points", points);
      }
    };
  });
  DotGrid = (function() {
    function DotGrid(sel, m, n) {
      this.sel = sel;
      this.m = m;
      this.n = n;
      this.gridBox = new boxes.GridBox("boardGrid", [this.m, this.n]).pin({
        top: sel.pin("top"),
        left: sel.pin("left"),
        bottom: sel.pin("bottom"),
        right: sel.pin("right"),
        aspect: n / m,
        width: sel.pin("width"),
        hmid: sel.pin("hmid")
      });
      this.render();
    }

    DotGrid.prototype.render = function() {
      var gridBox, i, j, _ref1;
      gridBox = this.gridBox;
      return this.sel.selectAll("rect.dot").data((_ref1 = []).concat.apply(_ref1, (function() {
        var _j, _ref1, _results;
        _results = [];
        for (j = _j = 0, _ref1 = this.n; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
          _results.push((function() {
            var _k, _ref2, _results1;
            _results1 = [];
            for (i = _k = 0, _ref2 = this.m; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; i = 0 <= _ref2 ? ++_k : --_k) {
              _results1.push([i, j]);
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this))).enter(function() {
        return this.append("rect").classed("dot", true).boxify("rect-dot").pin("tl", function(d) {
          return boxes.translate(gridBox.cell(d).tl, [1, 1]);
        }).pin("br", function(d) {
          return boxes.translate(gridBox.cell(d).br, [-1, -1]);
        });
      }).style("fill", "black");
    };

    return DotGrid;

  })();
  d3.select("document").on("dragstart", function() {
    return false;
  });
  stage = 2;
  return (function() {
    var board, braceMargin, gridBox, h, line, nBrace, svg, w;
    svg = d3.select("#diag0 svg");
    w = 50;
    h = 20;
    board = svg.append("g").boxify("g").pin({
      top: 0,
      height: h * 8
    });
    gridBox = (new DotGrid(board, h, w)).gridBox;
    board.selectAll("rect").style("fill", function(_arg) {
      var m, n;
      m = _arg[0], n = _arg[1];
      if (n < 0.9 * w) {
        if (m < 0.8 * h || stage < 2) {
          return "#ffcc61";
        } else {
          return "#b7baa4";
        }
      } else {
        if (m >= 0.2 * h || stage < 2) {
          return "#8ba802";
        } else {
          return "#ed4702";
        }
      }
    });
    braceMargin = svg.append("g").boxify().pin({
      tl: board.pin("bl"),
      tr: board.pin("br"),
      height: 5
    });
    (function() {
      var nBrace, nText;
      nBrace = svg.append("g").boxify("brace").call(brace, {
        dir: "up"
      }).style("stroke", "black").pin({
        left: boxes.translate(gridBox.cell([h - 1, 0]).left, 1),
        right: boxes.translate(gridBox.cell([h - 1, 0.9 * w - 1]).right, -1),
        top: braceMargin.pin("bottom"),
        height: 10
      });
      return nText = svg.append("text").boxify("text").pin({
        tl: boxes.translate(nBrace.pin("bm"), [0, 10])
      }).text("false things").style("text-anchor", "middle").style("dominant-baseline", "central");
    })();
    nBrace = (function() {
      var nText;
      nBrace = svg.append("g").boxify("brace").call(brace, {
        dir: "up"
      }).style("stroke", "black").pin({
        left: boxes.translate(gridBox.cell([h - 1, 0.9 * w]).left, 1),
        right: boxes.translate(gridBox.cell([h - 1, w - 1]).right, -1),
        top: braceMargin.pin("bottom"),
        height: 10
      });
      nText = svg.append("text").boxify("text").pin({
        tl: boxes.translate(nBrace.pin("bm"), [0, 10])
      }).text("true things").style("text-anchor", "middle").style("dominant-baseline", "central");
      return nBrace;
    })();
    line = svg.append("line").boxify("line").pin({
      right: boxes.translate(gridBox.left, -5),
      bottom: gridBox.cell([h * 0.8, 0]).top,
      size: [10, 0],
      left: 150
    }).style("stroke", "black");
    svg.append("text").boxify("text").pin({
      tl: boxes.translate(line.pin("tl"), [-5, 0])
    }).text("type I rate = 20%").style("text-anchor", "end").style("dominant-baseline", "central");
    line = svg.append("line").boxify("line").pin({
      tl: boxes.translate(gridBox.cell([h * 0.2, w - 1]).tr, [5, 0]),
      size: [10, 0]
    }).style("stroke", "black");
    svg.append("text").boxify("text").pin({
      tl: boxes.translate(line.pin("br"), [5, 0])
    }).text("statistical power = 80%").style("text-anchor", "start").style("dominant-baseline", "central");
    return svg.boxify("svg").pin({
      tl: [0, 0],
      right: boxes.translate(line.pin("right"), 150),
      bottom: boxes.translate(nBrace.pin("bottom"), 20)
    });
  })();
});
