// Generated by CoffeeScript 1.6.3
define(['boxes', 'constraints'], function(boxes, constraints) {
  var debug, install;
  debug = false;
  install = function(d3) {
    var attachBox, attachBoxes, d3sp;
    d3sp = d3.selection.prototype;
    attachBoxes = function(sel, box) {
      return sel.each(function(d, i) {
        return attachBox(this, d3.functor(box)(d, i));
      });
    };
    attachBox = function(elem, box) {
      var d3elem,
        _this = this;
      elem.box = box;
      d3elem = d3.select(elem);
      switch (elem.nodeName) {
        case "rect":
        case "image":
        case "g":
          new constraints.WatcherPseudoconstraint(elem.box.tl, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("x", x).attr("y", y);
          });
          new constraints.WatcherPseudoconstraint(elem.box.size, function(_arg) {
            var h, w;
            w = _arg[0], h = _arg[1];
            return d3elem.attr("width", w).attr("height", h);
          });
          break;
        case "svg":
          new constraints.WatcherPseudoconstraint(elem.box.size, function(_arg) {
            var h, w;
            w = _arg[0], h = _arg[1];
            return d3elem.attr("width", w).attr("height", h);
          });
          break;
        case "text":
          new constraints.WatcherPseudoconstraint(elem.box.tl, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("x", x).attr("y", y);
          });
          break;
        case "ellipse":
          new constraints.WatcherPseudoconstraint(elem.box.mm, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("cx", x).attr("cy", y);
          });
          new constraints.WatcherPseudoconstraint(elem.box.size, function(_arg) {
            var h, w;
            w = _arg[0], h = _arg[1];
            return d3elem.attr("rx", w / 2).attr("ry", h / 2);
          });
          break;
        case "circle":
          new constraints.WatcherPseudoconstraint(elem.box.mm, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("cx", x).attr("cy", y);
          });
          new constraints.WatcherPseudoconstraint(elem.box.size, function(_arg) {
            var h, w;
            w = _arg[0], h = _arg[1];
            return d3elem.attr("r", Math.min(w, h) / 2);
          });
          break;
        case "line":
          new constraints.WatcherPseudoconstraint(elem.box.tl, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("x1", x).attr("y1", y);
          });
          new constraints.WatcherPseudoconstraint(elem.box.br, function(_arg) {
            var x, y;
            x = _arg[0], y = _arg[1];
            return d3elem.attr("x2", x).attr("y2", y);
          });
      }
      if (debug) {
        elem.rect = d3elem.append("rect").style('fill', 'none').style('stroke', 'black');
        elem.text = d3elem.append("text").text(box.label).style("dominant-baseline", "hanging");
        new constraints.WatcherPseudoconstraint(elem.box.size, function(_arg) {
          var height, width;
          width = _arg[0], height = _arg[1];
          return elem.rect.attr("width", width).attr("height", height);
        });
        return new constraints.WatcherPseudoconstraint(elem.box.tl, function(_arg) {
          var x, y;
          x = _arg[0], y = _arg[1];
          elem.rect.attr("x", x).attr("y", y);
          return elem.text.attr("x", x).attr("y", y);
        });
      }
    };
    d3sp.boxify = function(label) {
      var _this = this;
      this.label = label;
      attachBoxes(this, function() {
        return new boxes.Box(_this.label);
      });
      return this;
    };
    d3sp.pin = function(source, target) {
      var obj;
      if (target == null) {
        target = void 0;
      }
      if (target === void 0) {
        if (typeof source === "string") {
          return this.node().box[source];
        } else {
          obj = source;
          for (source in obj) {
            target = obj[source];
            this.pin(source, target);
          }
        }
      } else {
        this.each(function(d, i) {
          return this.box.pin(source, d3.functor(target)(d, i));
        });
      }
      return this;
    };
    return d3sp.selectEach = function(selector, func) {
      this.selectAll(selector).each(function(d, i) {
        return func.call(d3.select(this), d, i);
      });
      return this;
    };
  };
  return {
    install: install
  };
});
