// Generated by CoffeeScript 1.6.3
var func1, func2, func3;

func1 = function() {
  return cow.onMoo(function() {
    return console.log("cow is mooing!");
  }).doCowThings();
};

console.log("should be in func1, but isn't!");

func2 = function() {
  cow.onMoo().doCowThings();
  return console.log("in func2!");
};

func3 = function() {
  cow.onMoo(function() {
    return console.log("cow is mooing!");
  });
  return console.log("in func3!");
};

cow.onMoo(function() {
  return this.on("mousedown", function(d) {
    dominoes.splice(dominoes.indexOf(d), 1);
    return renderDominoes();
  }).style("fill", 3);
});

cow.onMoo(function() {
  return this.on("mousedown");
}).style("fill", 3);

cow.onMoo().style("fill", 3);
