// Generated by CoffeeScript 1.6.3
var Domino, board, coords, domH, domL, domMargin, domPos, domS, domW, dominoes, dragOrigin, i, j, m, matrix, n, part1, part2, partSize, perm, permIndexScale, renderDominoes, sqPos, sqSize, svg, translate, _ref;

translate = function(x, y) {
  return "translate(" + x + ", " + y + ")";
};

d3.select("document").on("dragstart", function() {
  return false;
});

svg = d3.select("#diag1 svg");

svg.attr("width", 1000).attr("height", 400);

board = svg.append("g").classed("board", true);

perm = svg.append("g").classed("perm", true);

matrix = svg.append("g").classed("matrix", true);

perm.attr("transform", translate(300, 0));

matrix.attr("transform", translate(600, 0));

dragOrigin = false;

m = 2;

n = 4;

partSize = m * n / 2;

sqSize = 50;

coords = (_ref = []).concat.apply(_ref, (function() {
  var _i, _results;
  _results = [];
  for (j = _i = 0; 0 <= n ? _i < n : _i > n; j = 0 <= n ? ++_i : --_i) {
    _results.push((function() {
      var _j, _results1;
      _results1 = [];
      for (i = _j = 0; 0 <= m ? _j < m : _j > m; i = 0 <= m ? ++_j : --_j) {
        _results1.push([i, j]);
      }
      return _results1;
    })());
  }
  return _results;
})());

sqPos = function(_arg) {
  var di, dj;
  di = _arg[0], dj = _arg[1];
  return [dj * sqSize, di * sqSize];
};

Domino = (function() {
  function Domino(d) {
    if ((d[0][0] + d[0][1]) % 2 === 0) {
      this.d = d;
    } else {
      this.d = [d[1], d[0]];
    }
  }

  Domino.prototype.isVertical = function() {
    return this.d[0][0] === this.d[1][0];
  };

  Domino.prototype.topLeft = function() {
    return [Math.min(this.d[0][0], this.d[1][0]), Math.min(this.d[0][1], this.d[1][1])];
  };

  return Domino;

})();

board.selectAll("rect.square").data(coords).enter().append("rect").classed("square", true).attr("height", sqSize).attr("width", sqSize).attr("x", function(d) {
  return sqPos(d)[0];
}).attr("y", function(d) {
  return sqPos(d)[1];
}).style("fill", function(_arg) {
  var di, dj;
  di = _arg[0], dj = _arg[1];
  if ((di + dj) % 2) {
    return "black";
  } else {
    return "red";
  }
}).style("stroke-width", "3px").on("mouseover", function() {
  return d3.select(this).style("stroke", "white");
}).on("mouseout", function() {
  return d3.select(this).style("stroke", "none");
}).on("mousedown", function(d) {
  var dragging;
  console.log("mousedown");
  dragOrigin = d;
  return dragging = true;
}).on("mouseup", function(d) {
  console.log("mouseup");
  if (dragOrigin) {
    if (Math.abs(d[0] - dragOrigin[0]) + Math.abs(d[1] - dragOrigin[1]) === 1) {
      dominoes.push(new Domino([dragOrigin, d]));
    }
    dragOrigin = false;
  }
  console.log(dominoes);
  return renderDominoes();
});

domMargin = 10;

domS = sqSize - 2 * domMargin;

domL = 2 * sqSize - 2 * domMargin;

domPos = function(dom) {
  var x, y, _ref1;
  _ref1 = sqPos(dom.topLeft()), x = _ref1[0], y = _ref1[1];
  return [x + domMargin, y + domMargin];
};

domW = function(dom) {
  if (dom.isVertical()) {
    return domL;
  } else {
    return domS;
  }
};

domH = function(dom) {
  if (dom.isVertical()) {
    return domS;
  } else {
    return domL;
  }
};

dominoes = [new Domino([[0, 0], [1, 0]])];

renderDominoes = function() {
  var boardSel, bottom, labelsSel, marksSel, matrixCoords, matrixText, permSel, top, _i, _ref1, _results;
  boardSel = board.selectAll("rect.domino").data(dominoes, String);
  boardSel.enter().append("rect").classed("domino", true).attr("height", domH).attr("width", domW).attr("x", function(d) {
    return domPos(d)[0];
  }).attr("y", function(d) {
    return domPos(d)[1];
  }).style("stroke", "black").style("fill", "white").on("mouseover", function() {
    return d3.select(this).style("fill", "rgb(255,200,200)");
  }).on("mouseout", function() {
    return d3.select(this).style("fill", "white");
  }).on("mousedown", function(d) {
    dominoes.splice(dominoes.indexOf(d), 1);
    return renderDominoes();
  });
  boardSel.exit().remove();
  top = 20;
  bottom = 80;
  permSel = perm.selectAll("line.domino").data(dominoes, String);
  permSel.enter().append("line").classed("domino", true).attr("x1", function(d) {
    return permIndexScale(part1.indexOf(String(d.d[0])));
  }).attr("x2", function(d) {
    return permIndexScale(part2.indexOf(String(d.d[1])));
  }).attr("y1", top).attr("y2", bottom).style("stroke", "black").style("stroke-width", "5px");
  permSel.exit().remove();
  labelsSel = perm.selectAll("g.labelPair").data((function() {
    _results = [];
    for (var _i = 0; 0 <= partSize ? _i < partSize : _i > partSize; 0 <= partSize ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this)).enter().append("g").classed("labelPair", true);
  console.log(labelsSel);
  labelsSel.append("text").text(function(d) {
    return "" + (d + 1);
  }).style("text-anchor", "middle").style("dominant-baseline", "hanging").attr("x", function(d) {
    return permIndexScale(d);
  }).attr("y", bottom + 5);
  labelsSel.append("text").text(function(d) {
    return "" + (d + 1);
  }).style("text-anchor", "middle").attr("x", function(d) {
    return permIndexScale(d);
  }).attr("y", top - 5);
  i = "i";
  matrixText = [[1, i, 0, 0], [i, 1, i, 0], [0, i, 1, i], [0, 0, i, 1]];
  matrixCoords = (_ref1 = []).concat.apply(_ref1, (function() {
    var _j, _results1;
    _results1 = [];
    for (j = _j = 0; 0 <= partSize ? _j < partSize : _j > partSize; j = 0 <= partSize ? ++_j : --_j) {
      _results1.push((function() {
        var _k, _results2;
        _results2 = [];
        for (i = _k = 0; 0 <= partSize ? _k < partSize : _k > partSize; i = 0 <= partSize ? ++_k : --_k) {
          _results2.push([i, j]);
        }
        return _results2;
      })());
    }
    return _results1;
  })());
  matrix.selectAll("text.label").data(matrixCoords).enter().append("text").classed("label", true).text(function(d) {
    return "" + matrixText[d[0]][d[1]];
  }).style("text-anchor", "middle").style("dominant-baseline", "central").style("font-style", function(d) {
    if (matrixText[d[0]][d[1]] === "i") {
      return "italic";
    } else {
      return "normal";
    }
  }).attr("x", function(d) {
    return d[1] * 25;
  }).attr("y", function(d) {
    return 10 + d[0] * 25;
  });
  marksSel = matrix.selectAll("circle.mark").data(dominoes, String);
  marksSel.enter().append("circle").classed("mark", true).attr("cx", function(d) {
    return part2.indexOf(String(d.d[1])) * 25;
  }).attr("cy", function(d) {
    return 10 + part1.indexOf(String(d.d[0])) * 25;
  }).attr("r", 10).style("fill", "none").style("stroke", "black").style("stroke-width", "2px");
  return marksSel.exit().remove();
};

part1 = ((function() {
  var _i, _len, _ref1, _results;
  _results = [];
  for (_i = 0, _len = coords.length; _i < _len; _i++) {
    _ref1 = coords[_i], i = _ref1[0], j = _ref1[1];
    if ((i + j) % 2 === 0) {
      _results.push([i, j]);
    }
  }
  return _results;
})()).map(String);

part2 = ((function() {
  var _i, _len, _ref1, _results;
  _results = [];
  for (_i = 0, _len = coords.length; _i < _len; _i++) {
    _ref1 = coords[_i], i = _ref1[0], j = _ref1[1];
    if ((i + j) % 2 === 1) {
      _results.push([i, j]);
    }
  }
  return _results;
})()).map(String);

permIndexScale = d3.scale.linear().domain([0, partSize]).range([0, 200]);

renderDominoes();
