// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['constraints'], function(constraints) {
  var Box, GridBox, constant, translate;
  constant = constraints.constantConnector;
  Box = (function() {
    function Box(label) {
      this.label = label;
      this.top = constraints.probedConnector("" + this.label + " top");
      this.bottom = constraints.probedConnector("" + this.label + " bottom");
      this.height = constraints.probedConnector("" + this.label + " height");
      this.vmid = constraints.probedConnector("" + this.label + " vmid");
      this.left = constraints.probedConnector("" + this.label + " left");
      this.right = constraints.probedConnector("" + this.label + " right");
      this.width = constraints.probedConnector("" + this.label + " width");
      this.hmid = constraints.probedConnector("" + this.label + " hmid");
      this.size = constraints.probedConnector("" + this.label + " size");
      this.aspect = constraints.probedConnector("" + this.label + " aspect");
      constraints.dividedSegmentConstraint(this.top, this.bottom, this.height, this.vmid);
      constraints.dividedSegmentConstraint(this.left, this.right, this.width, this.hmid);
      new constraints.PairerConstraint(this.width, this.height, this.size);
      new constraints.MultiplierConstraint(this.height, this.aspect, this.width);
      this.tl = constraints.probedConnector("" + this.label + " tl");
      new constraints.PairerConstraint(this.left, this.top, this.tl);
      this.tm = constraints.probedConnector("" + this.label + " tm");
      new constraints.PairerConstraint(this.hmid, this.top, this.tm);
      this.tr = constraints.probedConnector("" + this.label + " tr");
      new constraints.PairerConstraint(this.right, this.top, this.tr);
      this.ml = constraints.probedConnector("" + this.label + " ml");
      new constraints.PairerConstraint(this.left, this.vmid, this.ml);
      this.mm = constraints.probedConnector("" + this.label + " mm");
      new constraints.PairerConstraint(this.hmid, this.vmid, this.mm);
      this.mr = constraints.probedConnector("" + this.label + " mr");
      new constraints.PairerConstraint(this.right, this.vmid, this.mr);
      this.bl = constraints.probedConnector("" + this.label + " bl");
      new constraints.PairerConstraint(this.left, this.bottom, this.bl);
      this.bm = constraints.probedConnector("" + this.label + " bm");
      new constraints.PairerConstraint(this.hmid, this.bottom, this.bm);
      this.br = constraints.probedConnector("" + this.label + " br");
      new constraints.PairerConstraint(this.right, this.bottom, this.br);
      this.all = constraints.probedConnector("" + this.label + " all");
      new constraints.PairerConstraint(this.tl, this.br, this.all);
      this.pinnable = ['top', 'bottom', 'height', 'vmid', 'left', 'right', 'width', 'hmid', 'size', 'aspect', 'tl', 'tm', 'tr', 'ml', 'mm', 'mr', 'bl', 'bm', 'br', 'all'];
    }

    Box.prototype.pin = function(source, target) {
      var dict;
      if (target == null) {
        target = void 0;
      }
      if (target === void 0) {
        if (typeof source === "string") {
          return this[source];
        } else {
          dict = source;
          for (source in dict) {
            target = dict[source];
            this.pin(source, target);
          }
        }
      } else {
        if (!(target instanceof constraints.Connector)) {
          target = constraints.constantConnector(target);
        }
        new constraints.EqualityConstraint(this[source], target);
      }
      return this;
    };

    return Box;

  })();
  GridBox = (function(_super) {
    __extends(GridBox, _super);

    function GridBox(label, _arg) {
      var cell, i, j;
      this.label = label;
      this.m = _arg[0], this.n = _arg[1];
      GridBox.__super__.constructor.call(this, this.label);
      this.cells = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.m; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (j = _j = 0, _ref1 = this.n; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
              cell = new Box();
              new constraints.MultiplierConstraint(cell.height, constant(this.m), this.height);
              new constraints.MultiplierConstraint(cell.width, constant(this.n), this.width);
              constraints.partwaysConstraint(this.top, this.bottom, i / this.m, cell.top);
              constraints.partwaysConstraint(this.left, this.right, j / this.n, cell.left);
              _results1.push(cell);
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this);
      this.pinnable.push("cells");
      this.pinnable.push("cell");
    }

    GridBox.prototype.cell = function(_arg) {
      var i, j;
      i = _arg[0], j = _arg[1];
      return this.cells[i][j];
    };

    return GridBox;

  })(Box);
  translate = function(connector, vector) {
    var i, splitConnector, splitToReturn, toReturn, _i, _len, _ref;
    if (vector.length != null) {
      splitConnector = [new constraints.Connector("translate-in-x"), new constraints.Connector("translate-in-y")];
      new constraints.PairerConstraint(splitConnector[0], splitConnector[1], connector);
      splitToReturn = [new constraints.Connector("translate-out-x"), new constraints.Connector("translate-out-y")];
      _ref = [0, 1];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        new constraints.AdderConstraint(splitConnector[i], constant(vector[i]), splitToReturn[i]);
      }
      toReturn = new constraints.Connector("translate-out-pair");
      new constraints.PairerConstraint(splitToReturn[0], splitToReturn[1], toReturn);
      return toReturn;
    } else {
      toReturn = new constraints.Connector("translate-out");
      new constraints.AdderConstraint(connector, constant(vector), toReturn);
      return toReturn;
    }
  };
  return {
    Box: Box,
    GridBox: GridBox,
    translate: translate
  };
});
