// Generated by CoffeeScript 1.6.3
window.addEventListener("load", function() {
  var SquareShuffler, c, canvas, colors, cols, context, draw, func_concat, hstack, i, j, last_press, mod, mul, offsetM, offsetN, onResize, onZoom, period, rawSize, root, rows, seq, seq2, sigmoid, sign, sit, swirl, translate, zigzag;
  mod = function(x, y) {
    return ((x % y) + y) % y;
  };
  "func_concat = (seq) ->\n  (x) -> (if seq.length then seq[0](func_concat(seq.slice(1))(x)) else x)";
  func_concat = function(seq) {
    return function(x) {
      var i, _i, _ref;
      for (i = _i = _ref = seq.length - 1; _ref <= -1 ? _i < -1 : _i > -1; i = _ref <= -1 ? ++_i : --_i) {
        x = seq[i](x);
      }
      return x;
    };
  };
  "func_concat = (seq) ->\n  (x) -> (if seq.length then func_concat(seq.slice(0, seq.length-1))(seq[seq.length-1](x))";
  hstack = function(seq, spacing) {
    if (spacing == null) {
      spacing = 0;
    }
  };
  SquareShuffler = (function() {
    function SquareShuffler(perm, icon) {
      this.perm = perm;
      this.icon = icon;
    }

    SquareShuffler.concat = function(seq) {
      var s;
      return new SquareShuffler(func_concat((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = seq.length; _i < _len; _i++) {
          s = seq[_i];
          _results.push(s.perm);
        }
        return _results;
      })()), hstack((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = seq.length; _i < _len; _i++) {
          s = seq[_i];
          _results.push(s.icon);
        }
        return _results;
      })(), 1));
    };

    SquareShuffler.transpose = function(shuffler) {
      var flip;
      flip = function(_arg) {
        var i, j;
        i = _arg[0], j = _arg[1];
        return [j, i];
      };
      return new SquareShuffler((function(pt) {
        return flip(shuffler.perm(flip(pt)));
      }), null);
    };

    return SquareShuffler;

  })();
  swirl = function(ni, nj, r) {
    var a, b, perm;
    a = {
      '00': [0, 1],
      '01': [1, 0],
      '11': [0, -1],
      '10': [-1, 0]
    };
    b = {
      '00': [1, 0],
      '10': [0, 1],
      '11': [-1, 0],
      '01': [0, -1]
    };
    perm = function(_arg) {
      var di, dj, i, j, _ref;
      i = _arg[0], j = _arg[1];
      _ref = (r ? a : b)["" + mod(i + ni, 2) + mod(j + nj, 2)], di = _ref[0], dj = _ref[1];
      return [i + di, j + dj];
    };
    return new SquareShuffler(perm, null);
  };
  translate = function(di, dj) {
    return new SquareShuffler((function(_arg) {
      var i, j;
      i = _arg[0], j = _arg[1];
      return [i + di, j + dj];
    }), null);
  };
  rows = function(seq) {
    return new SquareShuffler((function(_arg) {
      var i, j;
      i = _arg[0], j = _arg[1];
      return [i, j + seq[mod(i, seq.length)]];
    }), null);
  };
  cols = function(seq) {
    return new SquareShuffler.transpose(rows(seq));
  };
  sit = function() {
    return new SquareShuffler((function(x) {
      return x;
    }), null);
  };
  zigzag = function(ni, nj) {
    var a, perm;
    a = {
      '00': [0, 1],
      '01': [1, -1],
      '11': [1, -1],
      '10': [0, 1]
    };
    perm = function(_arg) {
      var di, dj, i, j, _ref;
      i = _arg[0], j = _arg[1];
      _ref = a["" + mod(i + ni, 2) + mod(j + nj, 2)], di = _ref[0], dj = _ref[1];
      return [i + di, j + dj];
    };
    return new SquareShuffler(perm, null);
  };
  seq = [SquareShuffler.concat([translate(1, 0), swirl(0, 0, false)]), rows([-1, 1]), SquareShuffler.concat([translate(0, 1), swirl(0, 1, true)]), cols([-1, 1]), SquareShuffler.concat([translate(-1, 0), swirl(1, 1, false)]), rows([1, -1]), swirl(0, 0, true), cols([1, 2]), SquareShuffler.concat([translate(0, -1), swirl(1, 0, true)]), cols([1, -1]), swirl(1, 1, true), rows([1, 2])];
  seq2 = [rows([-1, 1]), cols([-1, 1]), rows([1, -1]), cols([1, 2]), cols([1, -1]), rows([1, 2])];
  sign = function(a) {
    if (a > 0) {
      return 1;
    } else {
      return -1;
    }
  };
  root = function(a) {
    return sign(a) * Math.pow(Math.abs(a), 0.8);
  };
  sigmoid = function(a) {
    return (root(2 * a - 1) + 1) / 2;
  };
  last_press = 0;
  period = 1000;
  rawSize = 100;
  mul = 100;
  colors = (function() {
    var _i, _results;
    _results = [];
    for (j = _i = 0; _i < 100; j = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (i = _j = 0; _j < 100; i = ++_j) {
          _results1.push((function() {
            var _k, _results2;
            _results2 = [];
            for (c = _k = 0; _k < 3; c = ++_k) {
              _results2.push(Math.random() * 256);
            }
            return _results2;
          })());
        }
        return _results1;
      })());
    }
    return _results;
  })();
  offsetM = 50;
  offsetN = 50;
  canvas = document.getElementById("canvas");
  context = canvas.getContext('2d');
  draw = function() {
    var bg_l, color, cur, di, dj, halfM, halfN, now, o, rawSpacing, retime, size, spacing, t, x, y, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    if (!canvas) {
      requestAnimationFrame(draw);
      return;
    }
    now = Date.now();
    retime = (now - last_press) / period;
    o = sigmoid(mod(retime, 1));
    t = Math.floor(retime);
    bg_l = 50 + 50 * Math.cos(now / 1000);
    context.fillStyle = "hsl(0,0%," + bg_l + "%)";
    context.fillRect(0, 0, canvas.width, canvas.height);
    rawSpacing = 180 + 20 * Math.cos(now / 500);
    size = rawSize * mul / 100;
    spacing = rawSpacing * mul / 100;
    cur = seq[mod(t, seq.length)];
    halfM = Math.min(Math.ceil(canvas.width / spacing + 2), offsetM - 3);
    halfN = Math.min(Math.ceil(canvas.height / spacing + 2), offsetN - 3);
    for (i = _i = _ref = offsetM - halfM, _ref1 = offsetM + halfM; _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = _ref <= _ref1 ? ++_i : --_i) {
      for (j = _j = _ref2 = offsetN - halfN, _ref3 = offsetN + halfN; _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; j = _ref2 <= _ref3 ? ++_j : --_j) {
        if (true) {
          _ref4 = cur.perm([i, j]), di = _ref4[0], dj = _ref4[1];
        } else {
          _ref5 = cur.perm([Math.floor(i / 2), Math.floor(j / 2)]), di = _ref5[0], dj = _ref5[1];
          di = di * 2 + i % 2;
          dj = dj * 2 + j % 2;
        }
        x = spacing * ((1 - o) * i + o * di - offsetM) + canvas.width / 2;
        y = spacing * ((1 - o) * j + o * dj - offsetN) + canvas.height / 2;
        color = [0, 0, 0];
        for (c = _k = 0; _k < 3; c = ++_k) {
          color[c] = Math.floor((1 - o) * colors[i][j][c] + o * colors[di][dj][c]);
        }
        context.fillStyle = "rgb(" + color[0] + "," + color[1] + "," + color[2] + ")";
        context.fillRect(10 + x, 10 + y, size, size);
      }
    }
    requestAnimationFrame(draw);
  };
  requestAnimationFrame(draw);
  onResize = function() {
    canvas = document.getElementById("canvas");
    if (canvas) {
      canvas.width = window.innerWidth;
      return canvas.height = window.innerHeight;
    }
  };
  window.addEventListener('resize', onResize);
  onResize();
  onZoom = function(e) {
    var delta;
    e = window.event || e;
    delta = Math.max(-1, Math.min(1, e.wheelDelta || -e.detail));
    mul = Math.max(mul + delta, 1);
    return console.log(mul);
  };
  canvas.addEventListener('mousewheel', onZoom);
  return canvas.addEventListener('DOMMouseScroll', onZoom);
});
