// Generated by CoffeeScript 1.7.1
var after, cartesianExp, changeHandler, extend, fill, gcd, join, necklace, necklaceBox, necklaceGrid, necklacesWithSymmetry, rotator, rotatorBox, table, update,
  __slice = [].slice,
  __hasProp = {}.hasOwnProperty;

extend = function() {
  var arg, args, key, obj, value, _i, _len;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  obj = {};
  for (_i = 0, _len = args.length; _i < _len; _i++) {
    arg = args[_i];
    for (key in arg) {
      if (!__hasProp.call(arg, key)) continue;
      value = arg[key];
      obj[key] = value;
    }
  }
  return obj;
};

fill = d3.scale.ordinal().range(["#000", "#fff", "#00f", "#0f0", "#f00"].concat(d3.scale.category20().range()));

table = d3.select("#vis").append("table");

after = d3.select("#vis").append("div");

necklace = function(elem, colors, kwargs) {
  var bead, beadR, d3elem, i, line, r;
  if (kwargs) {
    r = kwargs.r, beadR = kwargs.beadR, line = kwargs.line, i = kwargs.i;
  }
  d3elem = elem.append != null ? elem : d3.select(elem);
  d3elem.classed("necklace", true);
  d3elem.append("circle").attr("r", r);
  if (line) {
    d3elem.append("path").classed("tick", true).attr("d", "M 0 0 L 0 " + (-r)).style("stroke", "gray").style("stroke-opacity", 1);
    d3elem.append("path").classed("tick2", true).attr("d", "M 0 0 L 0 " + (-r)).style("stroke", "gray").style("stroke-opacity", 0);
  }
  bead = d3elem.selectAll("circle.bead").data(Object);
  bead.enter().append("circle");
  bead.exit().remove();
  return bead.attr("class", "bead").attr("r", beadR).attr("transform", function(d, i) {
    var n;
    n = colors.length;
    return "translate(0, " + (-r) + ") rotate(" + [i * 360 / n, 0, r] + ")";
  }).style("fill", fill);
};

necklaceBox = function(elem, colors, kwargs) {
  var d3elem, halfSize, padding, r, transElem;
  d3elem = elem.append != null ? elem : d3.select(elem);
  r = kwargs.r, padding = kwargs.padding;
  halfSize = r + padding;
  transElem = d3elem.append("g").attr("transform", "translate(" + halfSize + ", " + halfSize + ")");
  return necklace(transElem.append("g"), colors, kwargs);

  /*
  d3elem.append("rect").attr("width", 2 * halfSize).attr("height", 2 * halfSize)
        .style("fill", "none").style("stroke", "black")
   */
};

necklaceGrid = function(elem, necklaces, kwargs) {
  var d3elem, padding, r, rowSize;
  d3elem = elem.append != null ? elem : d3.select(elem);
  r = kwargs.r, padding = kwargs.padding, rowSize = kwargs.rowSize;
  necklaces = elem.selectAll("g").data(necklaces, function(d) {
    return d.join("");
  });
  necklaces.enter().append("g").attr("transform", function(d, i) {
    return "translate(" + ((2 * r + 2 * padding) * (i % rowSize)) + ",\n          " + ((2 * r + 2 * padding) * ~~(i / rowSize)) + ")";
  }).each(function(d) {
    return necklaceBox(this, d, kwargs);
  });
  return necklaces.exit().remove();
};

rotator = function(elem, n, i, kwargs) {
  var angle, big, d3elem, fInX, fInY, fOutX, fOutY, path, r, rIn, rOut;
  d3elem = elem.append != null ? elem : d3.select(elem);
  d3elem.classed("rotator", true);
  r = kwargs.r;
  d3elem.append("circle").attr("r", r);
  angle = 2 * Math.PI * i / n;
  rOut = r + 5;
  rIn = r - 5;
  fOutX = rOut * Math.sin(angle);
  fOutY = -rOut * Math.cos(angle);
  fInX = rIn * Math.sin(angle);
  fInY = -rIn * Math.cos(angle);
  big = angle > Math.PI ? 1 : 0;
  path = "M 0 " + (-rIn) + " L 0 " + (-rOut) + " A " + rOut + " " + rOut + " 0 " + big + " 1 " + fOutX + " " + fOutY + " L " + fInX + " " + fInY + " A " + rIn + " " + rIn + " 0 " + big + " 0 0 " + (-rIn);
  d3elem.append("path").attr("d", path).style("stroke", "none").style("fill", "black");
  d3elem.append("path").classed("tick", true).attr("d", "M 0 0 L 0 " + (-r)).style("stroke", "gray").style("stroke-opacity", 0);
  return d3elem.append("path").classed("tick2", true).attr("d", "M 0 0 L 0 " + (-r)).style("stroke", "gray").style("stroke-opacity", 0);
};

rotatorBox = function(elem, n, i, kwargs) {
  var d3elem, halfSize, padding, r, transElem;
  d3elem = elem.append != null ? elem : d3.select(elem);
  r = kwargs.r, padding = kwargs.padding;
  halfSize = r + padding;
  transElem = d3elem.append("g").attr("transform", "translate(" + halfSize + ", " + halfSize + ")");
  return rotator(transElem, n, i, kwargs);
};

join = function(listOfLists) {
  var _ref;
  return (_ref = []).concat.apply(_ref, listOfLists);
};

gcd = function(x, y) {
  if (y === 0) {
    return x;
  } else {
    return gcd(y, x % y);
  }
};

cartesianExp = function(list, exp) {
  var elem, sub;
  if (exp === 0) {
    return [[]];
  } else {
    return join((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        elem = list[_i];
        _results.push((function() {
          var _j, _len1, _ref, _results1;
          _ref = cartesianExp(list, exp - 1);
          _results1 = [];
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            sub = _ref[_j];
            _results1.push([elem].concat(__slice.call(sub)));
          }
          return _results1;
        })());
      }
      return _results;
    })());
  }
};

necklacesWithSymmetry = function(n, k, r) {
  var seq, seqs, size, x, _, _i, _results;
  size = gcd(n, r);
  seqs = cartesianExp((function() {
    _results = [];
    for (var _i = 0; 0 <= k ? _i < k : _i > k; 0 <= k ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this), size);
  return (function() {
    var _j, _len, _results1;
    _results1 = [];
    for (_j = 0, _len = seqs.length; _j < _len; _j++) {
      seq = seqs[_j];
      _results1.push(join((function() {
        var _k, _ref, _results2;
        _results2 = [];
        for (_ = _k = 0, _ref = n / size; 0 <= _ref ? _k < _ref : _k > _ref; _ = 0 <= _ref ? ++_k : --_k) {
          _results2.push((function() {
            var _l, _len1, _results3;
            _results3 = [];
            for (_l = 0, _len1 = seq.length; _l < _len1; _l++) {
              x = seq[_l];
              _results3.push(x);
            }
            return _results3;
          })());
        }
        return _results2;
      })()));
    }
    return _results1;
  })();
};

update = function() {
  var b, beadR, h, heading, i, k, kwargs, n, necklaceSets, necklaces, p, r, rowSize, rr, summary, svg, totalCount, w, _fn, _i, _len;
  w = 500;
  h = 600;
  p = 8;
  beadR = 5;
  r = 20;
  rowSize = 10;
  w = rowSize * (2 * r + 2 * p);
  n = +d3.select("#n").property("value");
  k = +d3.select("#k").property("value");
  b = d3.select("#b").property("checked");
  fill.domain(d3.range(k));
  necklaceSets = (function() {
    var _i, _results;
    _results = [];
    for (rr = _i = 0; 0 <= n ? _i < n : _i > n; rr = 0 <= n ? ++_i : --_i) {
      _results.push(necklacesWithSymmetry(n, k, rr));
    }
    return _results;
  })();
  table.selectAll("tr").remove();
  heading = table.append("tr");
  heading.append("td").html("g");
  heading.append("td").html("X<sub>g</sub>");
  heading.append("td").html("|X<sub>g</sub>|");
  heading.selectAll("td").style("border-bottom", "solid");
  kwargs = {
    r: r,
    beadR: beadR,
    padding: p,
    rowSize: rowSize,
    line: true
  };
  totalCount = 0;
  _fn = function(necklaces, i) {
    var cell, rotatorSvg, row;
    row = table.append("tr");
    rotatorSvg = row.append("td").append("svg").attr("width", 2 * r + 2 * p).attr("height", 2 * r + 2 * p).attr("transform", "translate(" + [r + p, r + p] + ")");
    rotatorBox(rotatorSvg, n, i, kwargs);
    rotatorSvg.style("cursor", "pointer").on("click", function() {
      row.selectAll(".necklace .tick2").attr("transform", "rotate(" + (-i * 360 / n) + ")");
      return row.transition().duration(200).ease(d3.ease("linear")).call(function() {
        return this.selectAll(".rotator .tick").style("stroke-opacity", 1);
      }).transition().duration(200 + i * 1000 / n).call(function() {
        var rotatingTween;
        rotatingTween = function() {
          return d3.interpolateString("rotate(0)", "rotate(" + (i * 360 / n) + ")");
        };
        this.selectAll(".necklace").attrTween("transform", rotatingTween);
        return this.selectAll(".rotator .tick").attrTween("transform", rotatingTween);
      }).transition().duration(300).call(function() {
        this.selectAll(".tick").style("stroke-opacity", 0);
        return this.selectAll(".necklace .tick2").style("stroke-opacity", 1);
      }).transition().duration(300).call(function() {
        return this.selectAll(".rotator .tick2").style("stroke-opacity", 0);
      }).transition().duration(0).each("end", function() {
        row.selectAll(".rotator .tick").attr("transform", "rotate(0)");
        row.selectAll(".necklace .tick").style("stroke-opacity", 1);
        row.selectAll(".tick2").style("stroke-opacity", 0);
        return row.selectAll(".necklace").attr("transform", "rotate(0)");
      });
    });
    cell = row.append("td").append("svg").classed("pics", true).attr("width", rowSize * (2 * r + 2 * p)).attr("height", Math.ceil(necklaces.length / rowSize) * (2 * r + 2 * p)).attr("transform", "translate(" + [r + p, r + p] + ")");
    necklaceGrid(cell, necklaces, kwargs);
    row.append("td").html("" + necklaces.length + " (=" + k + "<sup>" + (gcd(n, i)) + "</sup>)");
    return totalCount += necklaces.length;
  };
  for (i = _i = 0, _len = necklaceSets.length; _i < _len; i = ++_i) {
    necklaces = necklaceSets[i];
    _fn(necklaces, i);
  }
  summary = table.append("tr");
  summary.append("td");
  summary.append("td");
  summary.append("td").text(totalCount);
  summary.selectAll("td").style("border-top", "solid");
  necklaces = generate_necklaces(n, k);
  after.selectAll("svg").remove();
  svg = after.append("svg").attr("width", w + 2 * p).attr("height", Math.ceil(necklaces.length / rowSize) * (2 * r + 4 * p) + r).attr("transform", "translate(" + [r + p, r + p] + ")");
  return necklaceGrid(svg, necklaces, extend(kwargs, {
    line: false
  }));
};

changeHandler = function(action) {
  return function() {
    var a, b;
    a = "value";
    b = "defaultValue";
    if (this.type === "checkbox") {
      a = "checked";
      b = "defaultChecked";
    }
    if (this[a] === this[b]) {
      return;
    }
    action();
    return this[b] = this[a];
  };
};

d3.selectAll("#n, #k, #b").on("change", changeHandler(update)).on("click", changeHandler(update));

update();
