// Generated by CoffeeScript 2.0.3

/*
bead = d3elem.selectAll("rect.bead")
             .data(colors)
bead.enter().append("rect").classed("bead", true)
bead.exit().remove()
bead.attr("x", -beadR).attr("y", -beadR).attr("width", 2*beadR).attr("height", 2*beadR)
    .attr("transform", (d, i) ->
      n = colors.length
      return "translate(0, #{-r}) rotate(#{[i * 360 / n, 0, r]})")
    .style("fill", fill).style("stroke", "black")
*/
             /*
             d3elem.append("rect").attr("width", 2 * halfSize).attr("height", 2 * halfSize)
                   .style("fill", "none").style("stroke", "black")
             */
var cartesianExp, dist, drawActionTable, drawFixedSetTable, drawRotDiagram, extend, fill, gcd, getParent, join, lyndonesque, necklace, necklaceBox, necklaceGrid, necklacesWithSymmetry, partition, radiusFromThreePoints, rotateNecklace, rotator, rotatorBox, square,
  hasProp = {}.hasOwnProperty,
  indexOf = [].indexOf;

extend = function(...args) {
  var arg, key, len, m, obj, value;
  obj = {};
  for (m = 0, len = args.length; m < len; m++) {
    arg = args[m];
    for (key in arg) {
      if (!hasProp.call(arg, key)) continue;
      value = arg[key];
      obj[key] = value;
    }
  }
  return obj;
};

lyndonesque = function(string) {
  var i, rots;
  rots = (function() {
    var m, ref, results;
    results = [];
    for (i = m = 0, ref = string.length; 0 <= ref ? m < ref : m > ref; i = 0 <= ref ? ++m : --m) {
      results.push(string.slice(i) + string.slice(0, i));
    }
    return results;
  })();
  rots.sort();
  return rots[0];
};

fill = d3.scale.ordinal().range(["#000", "#fff", "#f00", "#0f0", "#00f"].concat(d3.scale.category20().range()));

necklace = function(elem, colors, kwargs) {
  var bead, beadR, d3elem, i, line, r;
  if (kwargs) {
    ({r, beadR, line, i} = kwargs);
  }
  d3elem = elem.data != null ? elem : d3.select(elem);
  d3elem.classed("necklace", true).classed(`lyndonesque-${lyndonesque(colors.join(""))}`, true);
  d3elem.append("circle").attr("r", r).classed("main", true);
  if (line) {
    d3elem.append("path").classed("tick", true).attr("d", `M 0 0 L 0 ${-r}`).style("stroke", "gray").style("stroke-opacity", 1);
    d3elem.append("path").classed("tick2", true).attr("d", `M 0 0 L 0 ${-r}`).style("stroke", "gray").style("stroke-opacity", 0);
  }
  bead = d3elem.selectAll("circle.bead").data(colors);
  bead.enter().append("circle").classed("bead", true);
  bead.exit().remove();
  return bead.attr("r", beadR).attr("transform", function(d, i) {
    var n;
    n = colors.length;
    return `translate(0, ${-r}) rotate(${[i * 360 / n, 0, r]})`;
  }).style("fill", fill);
};

necklaceBox = function(elem, colors, kwargs) {
  var d3elem, halfSizeX, halfSizeY, orientation, padding, paddingPrimary, paddingSecondary, paddingX, paddingY, r, transElem;
  d3elem = elem.data != null ? elem : d3.select(elem);
  ({r, padding, orientation} = kwargs);
  if (orientation) {
    if (Array.isArray(padding)) {
      [paddingPrimary, paddingSecondary] = padding;
    } else {
      paddingPrimary = paddingSecondary = padding;
    }
    if (orientation === 'hor') {
      [paddingX, paddingY] = [paddingSecondary, paddingPrimary];
    } else {
      [paddingX, paddingY] = [paddingPrimary, paddingSecondary];
    }
  } else {
    paddingX = paddingY = padding;
  }
  halfSizeX = r + paddingX;
  halfSizeY = r + paddingY;
  transElem = d3elem.append("g").attr("transform", `translate(${halfSizeX}, ${halfSizeY})`);
  return necklace(transElem.append("g"), colors, kwargs);
};

partition = function(list, size) {
  var i;
  return (function() {
    var m, ref, results;
    results = [];
    for (i = m = 0, ref = Math.ceil(list.length / size); 0 <= ref ? m < ref : m > ref; i = 0 <= ref ? ++m : --m) {
      results.push(list.slice(size * i, size * (i + 1)));
    }
    return results;
  })();
};

necklaceGrid = function(elem, necklaceArray, kwargs) {
  var d3elem, orientation, padding, paddingPrimary, paddingSecondary, primaries, r, rowSize;
  d3elem = elem.data != null ? elem : d3.select(elem);
  ({r, padding, rowSize, orientation} = kwargs);
  if (Array.isArray(padding)) {
    [paddingPrimary, paddingSecondary] = padding;
  } else {
    paddingPrimary = paddingSecondary = padding;
  }
  if (orientation == null) {
    orientation = "hor"; // can also be "ver"
  }
  if (rowSize) {
    necklaceArray = partition(necklaceArray, rowSize);
  }
  primaries = elem.selectAll("g.primary").data(necklaceArray, function(d) {
    return "" + d;
  });
  primaries.enter().append("g").classed("primary", true).attr("transform", function(d, i) {
    var shift;
    shift = (2 * r + 2 * paddingPrimary) * i;
    if (orientation === "hor") {
      return `translate(0, ${shift})`;
    } else {
      return `translate(${shift}, 0)`;
    }
  }).each(function(d) {
    var secondaries;
    secondaries = d3.select(this).selectAll("g.secondary").data(d, function(d) {
      return "" + d;
    });
    return secondaries.enter().append("g").classed("secondary", true).attr("transform", function(d, i) {
      var shift;
      shift = (2 * r + 2 * paddingSecondary) * i;
      if (orientation === "hor") {
        return `translate(${shift}, 0)`;
      } else {
        return `translate(0, ${shift})`;
      }
    }).each(function(d) {
      return necklaceBox(this, d, kwargs);
    });
  });
  return primaries.exit().remove();
};

rotator = function(elem, n, i, kwargs) {
  var arc1, arc2, d3elem, r;
  d3elem = elem.data != null ? elem : d3.select(elem);
  d3elem.classed("rotator", true);
  ({r} = kwargs);
  d3elem.append("circle").attr("r", r);
  arc1 = d3.svg.arc().innerRadius(r - 5).outerRadius(r + 5).startAngle(0).endAngle(2 * Math.PI * i / n);
  arc2 = d3.svg.arc().innerRadius(r - 5).outerRadius(r + 5).endAngle(2 * Math.PI).startAngle(2 * Math.PI * i / n);
  d3elem.append("path").attr("d", arc1()).style("stroke", "none").style("fill", "black");
  d3elem.append("path").attr("d", arc2()).style("stroke", "none").style("fill", "lightgray");
  d3elem.append("path").classed("tick", true).attr("d", `M 0 0 L 0 ${-r}`).style("stroke", "gray").style("stroke-opacity", 0);
  return d3elem.append("path").classed("tick2", true).attr("d", `M 0 0 L 0 ${-r}`).style("stroke", "gray").style("stroke-opacity", 0);
};

rotatorBox = function(elem, n, i, kwargs) {
  var d3elem, halfSize, padding, r, transElem;
  d3elem = elem.data != null ? elem : d3.select(elem);
  ({r, padding} = kwargs);
  halfSize = r + padding;
  transElem = d3elem.append("g").attr("transform", `translate(${halfSize}, ${halfSize})`);
  return rotator(transElem, n, i, kwargs);
};

join = function(listOfLists) {
  return [].concat(...listOfLists);
};

gcd = function(x, y) {
  if (y === 0) {
    return x;
  } else {
    return gcd(y, x % y);
  }
};

cartesianExp = function(list, exp) {
  var elem, sub;
  if (exp === 0) {
    return [[]];
  } else {
    return join((function() {
      var len, m, results;
      results = [];
      for (m = 0, len = list.length; m < len; m++) {
        elem = list[m];
        results.push((function() {
          var len1, o, ref, results1;
          ref = cartesianExp(list, exp - 1);
          results1 = [];
          for (o = 0, len1 = ref.length; o < len1; o++) {
            sub = ref[o];
            results1.push([elem, ...sub]);
          }
          return results1;
        })());
      }
      return results;
    })());
  }
};

necklacesWithSymmetry = function(n, k, r) {
  var _, m, results, seq, seqs, size, x;
  size = gcd(n, r);
  seqs = cartesianExp((function() {
    results = [];
    for (var m = 0; 0 <= k ? m < k : m > k; 0 <= k ? m++ : m--){ results.push(m); }
    return results;
  }).apply(this), size);
  return (function() {
    var len, o, results1;
    results1 = [];
    for (o = 0, len = seqs.length; o < len; o++) {
      seq = seqs[o];
      results1.push(join((function() {
        var q, ref, results2;
        results2 = [];
        for (_ = q = 0, ref = n / size; 0 <= ref ? q < ref : q > ref; _ = 0 <= ref ? ++q : --q) {
          results2.push((function() {
            var len1, results3, s;
            results3 = [];
            for (s = 0, len1 = seq.length; s < len1; s++) {
              x = seq[s];
              results3.push(x);
            }
            return results3;
          })());
        }
        return results2;
      })()));
    }
    return results1;
  })();
};

rotateNecklace = function(nl, i) {
  i = nl.length - i;
  return nl.slice(i).concat(nl.slice(0, i));
};

drawActionTable = function(selector, necklaces, kwargs = {}) {
  var cumSum, drawFixedPoints, groupEnds, i, l, len, lengths, m, n, o, r, ref, results, size, table;
  groupEnds = [];
  ({drawFixedPoints} = kwargs);
  if (_.isArray(necklaces[0][0])) {
    // we have groups! ungroup!
    lengths = _.pluck(necklaces, 'length');
    necklaces = _.flatten(necklaces, true);
    cumSum = 0;
    for (m = 0, len = lengths.length; m < len; m++) {
      l = lengths[m];
      cumSum += l;
      groupEnds.push(cumSum);
    }
  }
  n = necklaces[0].length;
  r = 12;
  kwargs = {
    r: r,
    beadR: 0.3 * r,
    padding: 0.6 * r,
    line: false
  };
  size = 2 * r + 2 * kwargs.padding;
  table = d3.select(selector).append("table").classed("multiplication-table", true);
  results = [];
  for (i = o = -1, ref = n; -1 <= ref ? o < ref : o > ref; i = -1 <= ref ? ++o : --o) {
    results.push((function(i) {
      var elem, j, len1, necklaceCell, necklaceSvg, nl, q, ref1, results1, rotated, rotatorCell, rotatorSvg, row;
      row = table.append("tr");
      rotatorCell = row.append(i === -1 ? "th" : "td").classed("rotator-cell", true);
      rotatorSvg = rotatorCell.append("svg").attr("width", size).attr("height", size);
      if (i > -1) {
        rotatorBox(rotatorSvg, n, i, kwargs);
      }
      results1 = [];
      for (j = q = 0, len1 = necklaces.length; q < len1; j = ++q) {
        nl = necklaces[j];
        elem = i > -1 ? i : 0;
        necklaceCell = row.append(i === -1 ? "th" : "td");
        necklaceSvg = necklaceCell.append("svg").attr("width", size).attr("height", size);
        if (ref1 = j + 1, indexOf.call(groupEnds, ref1) >= 0) {
          necklaceCell.classed("rotator-cell", true);
        }
        rotated = rotateNecklace(nl, elem);
        if (drawFixedPoints && (i > -1) && _.isEqual(nl, rotated)) {
          necklaceCell.classed("fixed-point", true);
        }
        results1.push(necklaceBox(necklaceSvg, rotated, kwargs));
      }
      return results1;
    })(i));
  }
  return results;
};

drawFixedSetTable = function(visSelector, nSelector, kSelector) {
  var changeHandler, update;
  update = function() {
    var after, beadR, beadROverR, cellSize, container, fn, h, heading, hoverHandler, i, k, kwargs, len, m, n, necklaceSets, necklaces, p, pOverR, r, rowSize, rr, summary, svg, table, totalCount, w;
    container = d3.select(visSelector);
    container.selectAll("*").remove();
    table = container.append("table");
    after = container.append("div");
    n = +d3.select(nSelector).property("value"); // number of beads
    k = +d3.select(kSelector).property("value"); // number of colours
    fill.domain(d3.range(k));
    necklaceSets = (function() {
      var m, ref, results;
      results = [];
      for (rr = m = 0, ref = n; 0 <= ref ? m < ref : m > ref; rr = 0 <= ref ? ++m : --m) {
        results.push(necklacesWithSymmetry(n, k, rr));
      }
      return results;
    })();
    w = 600;
    h = 200;
    cellSize = Math.min(Math.sqrt(w * h / Math.pow(k, n)), 50);
    beadROverR = 0.30; // 0.40 for circles
    pOverR = 0.60;
    r = cellSize / (2 + 2 * pOverR);
    p = pOverR * r;
    beadR = beadROverR * r;
    rowSize = Math.ceil(w / cellSize);
    //rowSize = 10
    heading = table.append("tr");
    heading.append("td").html("<i>g</i>");
    heading.append("td").html("<i>X</i><sub><i>g</i></sub> &mdash; pictures fixed by <i>g</i>");
    heading.append("td").html("|<i>X</i><sub><i>g</i></sub>|");
    heading.selectAll("td").style("border-bottom", "solid").style("font-size", "20pt");
    kwargs = {
      r: r,
      beadR: beadR,
      padding: p,
      rowSize: rowSize,
      line: true
    };
    totalCount = 0;
    fn = function(necklaces, i) {
      var isAnimated, necklacesCell, necklacesSvg, rotatorCell, rotatorSvg, row;
      isAnimated = false;
      row = table.append("tr");
      rotatorCell = row.append("td");
      rotatorSvg = rotatorCell.append("svg").attr("width", 2 * r + 2 * p).attr("height", 2 * r + 2 * p);
      rotatorBox(rotatorSvg, n, i, kwargs);
      rotatorSvg.style("cursor", "pointer").on("click", function() {
        var backwardRotTween, forwardRotTween;
        if (isAnimated) {
          return;
        }
        isAnimated = true;
        // Set the necklace's second ticks to the right position (function of row)
        row.selectAll(".necklace .tick2").attr("transform", `rotate(${-i * 360 / n})`);
        forwardRotTween = function() {
          return d3.interpolateString("rotate(0)", `rotate(${i * 360 / n})`);
        };
        backwardRotTween = function() {
          return d3.interpolateString(`rotate(${i * 360 / n})`, "rotate(0)");
        };
        // Fade /in/ the rotator tick
        return row.transition().duration(200).ease(d3.ease("linear")).call(function() {
          return this.selectAll(".rotator .tick").style("stroke-opacity", 1);
        // Rotate the necklace and the rotator tick
        }).transition().duration(200 + i * 800 / n).call(function() {
          this.selectAll(".necklace").attrTween("transform", forwardRotTween);
          return this.selectAll(".rotator .tick").attrTween("transform", forwardRotTween);
        // Reset the necklace, switching ticks to maintain tick-continuity
        }).transition().duration(0).each("start", function() {
          row.selectAll(".necklace .tick").style("stroke-opacity", 0).attr("transform", "rotate(0)");
          row.selectAll(".necklace .tick2").style("stroke-opacity", 1);
          return row.selectAll(".necklace").attr("transform", "rotate(0)");
        // Rotate ticks right back
        }).transition().duration(200 + i * 800 / n).call(function() {
          this.selectAll(".necklace .tick2").attrTween("transform", backwardRotTween);
          return this.selectAll(".rotator .tick").attrTween("transform", backwardRotTween);
        // Swap necklace ticks
        }).transition().duration(0).each("start", function() {
          row.selectAll(".necklace .tick").style("stroke-opacity", 1);
          return row.selectAll(".necklace .tick2").style("stroke-opacity", 0);
        // Fade /out/ the rotator tick
        }).transition().duration(200).call(function() {
          return this.selectAll(".rotator .tick").style("stroke-opacity", 0);
        }).each("end", function() {
          return isAnimated = false;
        });
      });
      necklacesCell = row.append("td");
      necklacesSvg = necklacesCell.append("svg").classed("pics", true).attr("width", rowSize * (2 * r + 2 * p)).attr("height", Math.ceil(necklaces.length / rowSize) * (2 * r + 2 * p));
      necklaceGrid(necklacesSvg, necklaces, kwargs);
      row.append("td").html(`${necklaces.length // (=#{k}<sup>#{gcd(n,i)}</sup>)")
}`).style("font-size", "30pt");
      if (i !== 0) {
        row.selectAll("td").style("border-top", "dotted 2pt");
      }
      return totalCount += necklaces.length;
    };
    for (i = m = 0, len = necklaceSets.length; m < len; i = ++m) {
      necklaces = necklaceSets[i];
      fn(necklaces, i);
    }
    summary = table.append("tr");
    summary.append("td");
    summary.append("td");
    summary.append("td").text(totalCount).style("font-size", "30pt");
    summary.selectAll("td").style("border-top", "solid");
    necklaces = generate_necklaces(n, k);
    after.selectAll("svg").remove();
    svg = after.append("svg").attr("width", rowSize * (2 * r + 2 * p)).attr("height", Math.ceil(necklaces.length / rowSize) * (2 * r + 2 * p) + r);
    necklaceGrid(svg, necklaces, extend(kwargs, {
      line: false
    }));
    hoverHandler = function() {
      var clss, fillStyle;
      clss = ((function() {
        var len1, o, ref, results;
        ref = this.classList;
        results = [];
        for (o = 0, len1 = ref.length; o < len1; o++) {
          clss = ref[o];
          if (clss.indexOf("lyndonesque") === 0) {
            results.push(clss);
          }
        }
        return results;
      }).call(this))[0];
      fillStyle = d3.event.type === "mouseover" ? "lightgray" : "none";
      return container.selectAll(`.${clss} circle.main`).style("fill", fillStyle);
    };
    return container.selectAll(".necklace").on("mouseover", hoverHandler).on("mouseout", hoverHandler);
  };
  changeHandler = function(action) {
    return function() {
      var a, b;
      a = "value";
      b = "defaultValue";
      if (this.type === "checkbox") {
        a = "checked";
        b = "defaultChecked";
      }
      if (this[a] === this[b]) {
        return;
      }
      action();
      return this[b] = this[a];
    };
  };
  d3.selectAll(`${nSelector}, ${kSelector}`).on("change", changeHandler(update)).on("click", changeHandler(update));
  return update();
};

square = function(x) {
  return x * x;
};

dist = function(a, b) {
  return Math.sqrt(square(b.x - a.x) + square(b.y - a.y));
};

radiusFromThreePoints = function(a, b, c) {
  return dist(a, b) * dist(b, c) * dist(c, a) / (2 * Math.abs(a.x * b.y + b.x * c.y + c.x * a.y - a.x * c.y - b.x * a.y - c.x * b.y));
};

drawRotDiagram = function(elem, n, kwargs = {}) {
  var beadR, bigG, d3elem, forwardRotTween, g, g2, i, m, outerR, ref, ringR, toReturn;
  d3elem = elem.data != null ? elem : d3.select(elem);
  ({outerR, ringR, beadR} = kwargs);
  d3elem.append("svg:defs").append("svg:marker").attr({
    id: "arrowhead",
    viewBox: "0 0 10 10",
    refX: 3,
    refY: 5,
    markerWidth: 13,
    markerHeight: 13,
    orient: "auto",
    markerUnits: "userSpaceOnUse"
  }).append("svg:path").style({
    stroke: "none",
    fill: "gray"
  }).attr("d", "M 0 0 L 10 5 L 0 10 z");
  bigG = d3elem.append("g").attr("transform", `translate(${outerR}, ${outerR})`);
  g = bigG.append("g");
  g.append("circle").attr("r", ringR);
  for (i = m = 0, ref = n; 0 <= ref ? m < ref : m > ref; i = 0 <= ref ? ++m : --m) {
    g2 = g.append("g").attr("transform", `rotate(${360 * i / n})`);
    g2.append("circle").attr({
      cx: 0,
      cy: -ringR,
      r: beadR
    }).style({
      fill: 'white'
    });
  }
  forwardRotTween = function() {
    return d3.interpolateString("rotate(0)", `rotate(${360 * k / n})`);
  };
  d3elem.on("click", function() {
    // Rotate the necklace and the rotator tick
    return g.transition().duration(700).call(function() {
      return this.attrTween("transform", forwardRotTween);
    });
  });
  return toReturn = {
    arc: function(i, j, midR, kwargs = {}) {
      var dashed, dr, dstX, dstY, flipped, midX, midY, path, srcX, srcY;
      ({dashed, flipped} = kwargs);
      srcX = 0;
      srcY = -ringR;
      midX = midR * Math.sin(6.2831 * (j - i) / n / 2);
      midY = -midR * Math.cos(6.2831 * (j - i) / n / 2);
      dstX = ringR * Math.sin(6.2831 * (j - i) / n);
      dstY = -ringR * Math.cos(6.2831 * (j - i) / n);
      dr = radiusFromThreePoints({
        x: srcX,
        y: srcY
      }, {
        x: midX,
        y: midY
      }, {
        x: dstX,
        y: dstY
      });
      path = ["M", srcX, srcY, "A", dr, dr, 0, 0, (flipped ? 1 : 0), midX, midY, "A", dr, dr, 0, 0, (flipped ? 1 : 0), dstX, dstY].join(" ");
      g2 = g.insert("g", ":first-child").attr("transform", `rotate(${360 * i / n})`);
      path = g2.append("path").attr("d", path).attr("marker-mid", "url(#arrowhead)").style({
        fill: "none",
        stroke: "gray",
        "stroke-width": "3px"
      });
      if (dashed) {
        path.attr("stroke-dasharray", "3,2");
      }
      return toReturn;
    },
    text: function(i, text) {
      g2 = g.append("g").attr("transform", `rotate(${360 * i / n})`);
      g2.append("text").attr({
        x: 0,
        y: -ringR
      }).style({
        'font-style': 'italic',
        'text-anchor': 'middle',
        'dominant-baseline': 'central'
      }).text(text);
      return toReturn;
    }
  };
};

getParent = function(selector) {
  return d3.select(d3.select(selector).node().parentNode);
};
